import assert from "node:assert/strict";
import { execFile, execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const exec = promisify(execFile);
const CLI = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "cli", "stdd.mjs");

function tmpRepo() {
	return fs.mkdtempSync(path.join(os.tmpdir(), "stdd-test-"));
}

async function run(args, opts = {}) {
	try {
		const { stdout, stderr } = await exec("node", [CLI, ...args], opts);
		return { code: 0, stdout, stderr };
	} catch (err) {
		return { code: err.code ?? 1, stdout: err.stdout ?? "", stderr: err.stderr ?? "" };
	}
}

test("init installs .stdd, Claude skills, and the AGENTS snippet", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "claude,codex"]);
	assert.equal(res.code, 0);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "method.md")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "config.json")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "AGENTS-snippet.md")));
	const skills = fs.readdirSync(path.join(dir, ".claude", "skills"));
	assert.ok(skills.includes("stdd-brainstorming"));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-brainstorming", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /^---\nname: stdd-brainstorming\ndescription: .+\n---\n/);
	assert.match(skill, /generated by stdd v/);
});

test("init installs the pr-green playbook as a skill and lists it for codex", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "playbooks", "pr-green.md")));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-pr-green", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /terminal-green|terminal green/i);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /pr-green\.md/);
});

test("init --hooks writes a user-owned pre-push hook running stdd check", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "codex", "--hooks"]);
	assert.equal(res.code, 0);
	const hookPath = path.join(dir, ".stdd", "hooks", "pre-push");
	const hook = fs.readFileSync(hookPath, "utf8");
	assert.match(hook, /stdd check/);
	assert.ok(!/gh |check-pr/.test(hook), "the hook stays fast and offline");
	assert.ok(fs.statSync(hookPath).mode & 0o111, "the hook is executable");
	assert.match(res.stdout, /core\.hooksPath/);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.ok(!(".stdd/hooks/pre-push" in manifest.files), "user-owned — not manifest-tracked");
});

test("init --hooks never overwrites an existing hook", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex", "--hooks"]);
	const hookPath = path.join(dir, ".stdd", "hooks", "pre-push");
	fs.appendFileSync(hookPath, "npm run my-own-step\n");
	await run(["init", dir, "--tools", "codex", "--hooks"]);
	assert.match(fs.readFileSync(hookPath, "utf8"), /my-own-step/);
});

test("plain init writes no hooks; doctor reports hook wiring informationally", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex"]);
	assert.ok(!fs.existsSync(path.join(dir, ".stdd", "hooks")));
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "a.md"), "Present tense.\n");
	const without = await run(["doctor", dir]);
	assert.equal(without.code, 0, without.stdout + without.stderr);
	assert.match(without.stdout, /hook not installed|no pre-push hook/i);
	await run(["init", dir, "--tools", "codex", "--hooks"]);
	const withHook = await run(["doctor", dir]);
	assert.equal(withHook.code, 0, withHook.stdout + withHook.stderr);
	assert.match(withHook.stdout, /pre-push hook/i);
});

test("init installs the investigation playbook as a skill and lists it for codex", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "playbooks", "investigation.md")));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-investigation", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /read-only|no file edits/i);
	assert.match(skill, /hypothesis is not a diagnosis/i);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /investigation\.md/);
});

test("init generates the project-log retrieval rule for agents", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex"]);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /[Dd]o not search the project log/);
	assert.match(snippet, /explicitly asks/);
});

test("init is idempotent and preserves an existing config", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const configPath = path.join(dir, ".stdd", "config.json");
	fs.writeFileSync(configPath, JSON.stringify({ temporalPhrases: ["formerly"] }));
	const res = await run(["init", dir, "--tools", "claude"]);
	assert.equal(res.code, 0);
	assert.deepEqual(JSON.parse(fs.readFileSync(configPath, "utf8")).temporalPhrases, ["formerly"]);
});

test("init --ci github writes the stdd workflow with a live body fetch", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "claude", "--ci", "github"]);
	assert.equal(res.code, 0);
	const wf = fs.readFileSync(path.join(dir, ".github", "workflows", "stdd.yml"), "utf8");
	assert.match(wf, /generated by stdd v/);
	assert.match(wf, /types: \[opened, edited, synchronize, reopened\]/);
	assert.match(wf, /fetch-depth: 0/);
	assert.match(wf, /set -o pipefail/);
	assert.match(wf, /node --input-type=module/);
	assert.ok(!wf.includes("gh api"), "the generated workflow must not depend on the gh CLI");
	assert.ok(!/\$\{(?!\{)/.test(wf), "no JS template literals in the shell script (SC2016)");
	assert.ok(
		!wf.includes("github.event.pull_request.body"),
		"the generated workflow must not read the frozen event payload body",
	);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.match(manifest.files[".github/workflows/stdd.yml"], /^sha256:/);
});

test("plain init never touches .github", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	assert.ok(!fs.existsSync(path.join(dir, ".github")));
});

test("init rejects an unknown --ci value; --ci is init-only", async () => {
	const dir = tmpRepo();
	const bad = await run(["init", dir, "--ci", "gitlab"]);
	assert.equal(bad.code, 1);
	assert.match(bad.stderr, /unknown ci/i);
	assert.equal((await run(["check", dir, "--ci", "github"])).code, 1);
});

test("doctor flags a workflow validating the frozen payload body without an edited trigger", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
	const stale = [
		"on:",
		"  pull_request:",
		"    types: [opened, synchronize]",
		"jobs:",
		"  stdd:",
		"    steps:",
		"      - env:",
		"          PR_BODY: ${{ github.event.pull_request.body }}",
		"        run: printf '%s' \"$PR_BODY\" | npx @stdd/cli check-pr -",
		"",
	].join("\n");
	fs.writeFileSync(path.join(dir, ".github", "workflows", "ci.yml"), stale);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .*frozen event payload|✗ .*body edits will not be re-checked/i);

	fs.writeFileSync(
		path.join(dir, ".github", "workflows", "ci.yml"),
		stale.replace("types: [opened, synchronize]", "types: [opened, edited, synchronize]"),
	);
	const ok = await run(["doctor", dir]);
	assert.ok(!/body edits will not be re-checked/i.test(ok.stdout));
});

test("doctor flags a PR template whose placeholder would pass the evidence gate", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".github"), { recursive: true });
	const tpl = path.join(dir, ".github", "pull_request_template.md");
	fs.writeFileSync(tpl, "## Summary\n\nDocs updated first: <fill in>\n");
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .*pull_request_template.*evidence/i);

	fs.writeFileSync(tpl, "## Summary\n\n> Docs updated first: <fill in>\n");
	const ok = await run(["doctor", dir]);
	assert.ok(!/pull_request_template.*evidence/i.test(ok.stdout));
});

test("check reports artifacts and temporal narrative, exits 1", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.mkdirSync(path.join(dir, "docs", "plans"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, "docs", "domain", "order.md"),
		"The order previously shipped.\nno longer-lived tokens are fine.\n",
	);
	fs.writeFileSync(path.join(dir, "docs", "plans", "p.md"), "step 1\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/plans\/p\.md: committed working artifact/);
	assert.match(res.stderr, /order\.md:1: temporal narrative .* \("previously"\)/);
	assert.ok(!res.stderr.includes(":2:"), "hyphenated compound must not match");
});

test("check passes on a clean repo", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Orders ship after review.\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /stdd check: OK/);
});

test("init records generated files in .stdd/manifest.json", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.equal(manifest.generatedBy, "stdd");
	assert.ok(manifest.version.length > 0);
	assert.match(manifest.files[".stdd/method.md"], /^sha256:[0-9a-f]{64}$/);
	assert.ok(manifest.files[".claude/skills/stdd-debugging/SKILL.md"]);
	assert.ok(manifest.files[".stdd/AGENTS-snippet.md"]);
	assert.equal(manifest.files[".stdd/config.json"], undefined, "config is user-owned");
});

test("check passes right after init and flags hand-edited generated files", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	assert.equal((await run(["check", dir])).code, 0);

	const playbook = path.join(dir, ".stdd", "playbooks", "debugging.md");
	fs.appendFileSync(playbook, "\nlocal tweak\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /\.stdd\/playbooks\/debugging\.md: .*edited by hand or stale/);
});

test("check flags generated files missing from disk", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	fs.rmSync(path.join(dir, ".stdd", "method.md"));
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /\.stdd\/method\.md: .*missing/);
});

test("check flags stale generated-file stamps", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skillPath = path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md");
	fs.writeFileSync(
		skillPath,
		fs.readFileSync(skillPath, "utf8").replace(/generated by stdd v[^\s]+/, "generated by stdd v0.0.0"),
	);
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /re-run stdd init/);
});

test("check rejects invalid config with a useful error", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "config.json"), '{"canonicalDocs": "oops"}');
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /"canonicalDocs" must be an array of strings/);
});

test("strict argument parsing fails loudly", async () => {
	const dir = tmpRepo();
	assert.equal((await run(["check", dir, "--unknown"])).code, 1);
	assert.equal((await run(["check", dir, "--tools", "claude"])).code, 1);
	const badTool = await run(["init", dir, "--tools", "nope"]);
	assert.equal(badTool.code, 1);
	assert.match(badTool.stderr, /unknown tool\(s\): nope/);
	assert.equal((await run(["check", dir, "extra"])).code, 1);
});

test("check-pr accepts exactly one evidence line", async () => {
	const dir = tmpRepo();
	const ok = path.join(dir, "ok.md");
	fs.writeFileSync(ok, "Body\nDocs not applicable: lint only\n");
	assert.equal((await run(["check-pr", ok])).code, 0);

	const missing = path.join(dir, "missing.md");
	fs.writeFileSync(missing, "no evidence\n");
	const res = await run(["check-pr", missing]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no docs evidence line/);

	const double = path.join(dir, "double.md");
	fs.writeFileSync(double, "Docs updated first: a\nDocs not applicable: b\n");
	const dres = await run(["check-pr", double]);
	assert.equal(dres.code, 1);
	assert.match(dres.stderr, /2 docs evidence lines \(lines 1, 2\)/);
});

test("doctor reports missing readiness paths with their hints", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({
			readiness: {
				required: [
					{ path: "node_modules", hint: "pnpm install --frozen-lockfile" },
					{ path: "apps/api/.env" },
				],
			},
		}),
	);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ node_modules missing — pnpm install --frozen-lockfile/);
	assert.match(res.stdout, /✗ apps\/api\/\.env missing/);
});

test("doctor --readiness runs only the readiness section", async () => {
	const dir = tmpRepo(); // no .stdd install, no docs — full doctor would fail loudly
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.mkdirSync(path.join(dir, "node_modules"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ readiness: { required: [{ path: "node_modules", hint: "install" }] } }),
	);
	const res = await run(["doctor", dir, "--readiness"]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /✓ worktree ready \(1\/1 present\)/);
	assert.ok(!res.stdout.includes("canonical docs"), "--readiness must skip adoption checks");

	const empty = tmpRepo();
	const none = await run(["doctor", empty, "--readiness"]);
	assert.equal(none.code, 0);
	assert.match(none.stdout, /no readiness contract declared/);
});

test("--readiness is only valid for doctor", async () => {
	const dir = tmpRepo();
	assert.equal((await run(["check", dir, "--readiness"])).code, 1);
});

test("doctor reports findings on a messy repo and exits 1", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "plans"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "plans", "old-plan.md"), "step 1\n");
	fs.writeFileSync(path.join(dir, "AGENTS.md"), "# Rules\n");
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .stdd\/ is not installed/);
	assert.match(res.stdout, /✗ no canonical docs found/);
	assert.match(res.stdout, /✗ 1 committed working artifact/);
	assert.match(res.stdout, /✗ AGENTS\.md has no STDD section/);
});

test("doctor passes on a healthy stdd repo and exits 0", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Orders ship after review.\n");
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	fs.writeFileSync(path.join(dir, "AGENTS.md"), `# Rules\n\n${snippet}`);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /✓ .stdd\/ installed/);
	assert.match(res.stdout, /✓ canonical docs present/);
	assert.match(res.stdout, /✓ no committed working artifacts/);
	assert.match(res.stdout, /✓ AGENTS\.md carries the STDD section/);
});

test("doctor counts temporal narrative and stale generated files", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Previously orders shipped.\n");
	const skillPath = path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md");
	fs.writeFileSync(
		skillPath,
		fs.readFileSync(skillPath, "utf8").replace(/generated by stdd v[^\s]+/, "generated by stdd v0.0.0"),
	);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ 1 canonical doc contains temporal narrative/);
	assert.match(res.stdout, /✗ 1 generated file is stale/);
});

async function tmpGitRepo() {
	const dir = tmpRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("init", "-q", "-b", "main");
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are net.\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("checkout", "-qb", "feature");
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are gross.\n");
	fs.writeFileSync(path.join(dir, "impl.js"), "export {};\n");
	await git("add", ".");
	await git("commit", "-qm", "change");
	return dir;
}

test("check-pr --base passes when claimed docs really changed", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/pricing.md\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
});

test("check-pr --base fails when a claimed doc is not in the diff", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/unrelated.md\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/domain\/unrelated\.md/);
	assert.match(res.stderr, /not changed/);
});

test("check-pr --base fails when 'updated first' names no path at all", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: see the description\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no doc paths/i);
});

test("check-pr --base verifies 'checked, no change needed' paths exist", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs checked, no change needed: docs/domain/pricing.md — covered\n");
	assert.equal((await run(["check-pr", body, "--base", "main"], { cwd: dir })).code, 0);

	fs.writeFileSync(body, "Docs checked, no change needed: docs/domain/ghost.md — covered\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /ghost\.md/);
	assert.match(res.stderr, /does not exist/);
});

test("check-pr without --base keeps text-only behavior", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/unrelated.md\n");
	assert.equal((await run(["check-pr", body], { cwd: dir })).code, 0);
});

test("check-pr failure points at a near-miss line with a corrected form", async () => {
	const dir = tmpRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Summary\n\n**Docs updated first:** docs/domain/orgs.md\n");
	const res = await run(["check-pr", body]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /near-miss/);
	assert.match(res.stderr, /line 3/);
	assert.match(res.stderr, /found: \*\*Docs updated first:\*\* docs\/domain\/orgs\.md/);
	assert.match(res.stderr, /fix: {3}Docs updated first: docs\/domain\/orgs\.md/);
	assert.match(res.stderr, /column 0/);
});

test("check-pr failure without a near-miss keeps the generic message", async () => {
	const dir = tmpRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "no evidence here\n");
	const res = await run(["check-pr", body]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no docs evidence line/);
	assert.ok(!res.stderr.includes("near-miss"));
});

test("check-pr --base suggests the correct label for sentinel content", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: not applicable\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no doc paths/i);
	assert.match(res.stderr, /Docs not applicable: <why implementation-only>/);
});

/**
 * A repo with a real `origin` (bare sibling): main pushed, a feature branch
 * with a docs change checked out. Returns paths plus a PATH prefix holding a
 * fake `gh` that prints the JSON written to `ghOutput`.
 */
async function tmpGitRepoWithOrigin() {
	const root = tmpRepo();
	const origin = path.join(root, "origin.git");
	const dir = path.join(root, "work");
	fs.mkdirSync(dir);
	await exec("git", ["init", "-q", "--bare", origin]);
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("init", "-q", "-b", "main");
	await git("remote", "add", "origin", origin);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are net.\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("push", "-q", "origin", "main");
	await git("checkout", "-qb", "feature");
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are gross.\n");
	await git("add", ".");
	await git("commit", "-qm", "change");

	const bin = path.join(root, "bin");
	fs.mkdirSync(bin);
	const ghOutput = path.join(root, "gh.json");
	fs.writeFileSync(path.join(bin, "gh"), `#!/bin/sh\ncat "${ghOutput}"\n`, { mode: 0o755 });
	const env = {
		...process.env,
		PATH: `${bin}${path.delimiter}${path.dirname(process.execPath)}${path.delimiter}${process.env.PATH}`,
	};
	const headSha = (await git("rev-parse", "HEAD")).stdout.trim();
	return { dir, git, ghOutput, env, headSha };
}

test("check-pr --pr validates the live body against the PR's base and head", async () => {
	const { dir, ghOutput, env, headSha } = await tmpGitRepoWithOrigin();
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: headSha,
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 0);
	assert.match(res.stdout, /OK \(PR #7 body, base origin\/main, head [0-9a-f]{7}\)/);
});

test("check-pr --pr diffs the PR head, not a diverged local checkout", async () => {
	const { dir, git, ghOutput, env, headSha } = await tmpGitRepoWithOrigin();
	await git("update-ref", "refs/heads/tmp-pr", headSha);
	await git("push", "-q", "origin", "refs/heads/tmp-pr:refs/pull/7/head");
	await git("checkout", "-q", "main"); // local HEAD no longer matches the PR head
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: headSha,
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 0, res.stderr);
});

test("check-pr --pr fails when the PR head cannot be resolved", async () => {
	const { dir, git, ghOutput, env } = await tmpGitRepoWithOrigin();
	await git("checkout", "-q", "main");
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: "0123456789abcdef0123456789abcdef01234567",
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /local HEAD differs from PR head/);
});

test("check-pr --pr is exclusive with the body file and --base, and needs gh", async () => {
	const { dir, env } = await tmpGitRepoWithOrigin();
	const both = await run(["check-pr", "body.md", "--pr", "7"], { cwd: dir, env });
	assert.equal(both.code, 1);
	assert.match(both.stderr, /--pr replaces/);

	const withBase = await run(["check-pr", "--pr", "7", "--base", "main"], { cwd: dir, env });
	assert.equal(withBase.code, 1);
	assert.match(withBase.stderr, /--pr derives the base/);

	const noGh = await run(["check-pr", "--pr", "7"], {
		cwd: dir,
		env: { ...process.env, PATH: path.dirname(process.execPath) },
	});
	assert.equal(noGh.code, 1);
	assert.match(noGh.stderr, /GitHub CLI|gh/);
});

test("evidence prints a finished 'Docs updated first' line when canonical docs changed", async () => {
	const dir = await tmpGitRepo();
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
	assert.equal(res.stdout, "Docs updated first: docs/domain/pricing.md\n");
});

test("evidence lists every changed canonical doc on one line", async () => {
	const dir = await tmpGitRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	fs.writeFileSync(path.join(dir, "docs", "domain", "auth.md"), "Sessions expire.\n");
	await git("add", ".");
	await git("commit", "-qm", "more docs");
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
	assert.equal(res.stdout, "Docs updated first: docs/domain/auth.md, docs/domain/pricing.md\n");
});

test("evidence exits nonzero with templates on stderr when no canonical docs changed", async () => {
	const dir = await tmpGitRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("checkout", "-qb", "impl-only", "main");
	fs.writeFileSync(path.join(dir, "util.js"), "export {};\n");
	await git("add", ".");
	await git("commit", "-qm", "impl");
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.equal(res.stdout, "", "stdout must stay empty so $(...) cannot embed a template");
	assert.match(res.stderr, /Docs checked, no change needed: <docs \+ reason>/);
	assert.match(res.stderr, /Docs not applicable: <why implementation-only>/);
});

test("evidence requires a base: --base flag or config baseRef", async () => {
	const dir = await tmpGitRepo();
	const missing = await run(["evidence"], { cwd: dir });
	assert.equal(missing.code, 1);
	assert.match(missing.stderr, /--base|baseRef/);

	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "config.json"), '{"baseRef": "main"}');
	const fromConfig = await run(["evidence"], { cwd: dir });
	assert.equal(fromConfig.code, 0);
	assert.equal(fromConfig.stdout, "Docs updated first: docs/domain/pricing.md\n");
});

test("check-pr rejects a bare evidence label", async () => {
	const dir = tmpRepo();
	const bare = path.join(dir, "bare.md");
	fs.writeFileSync(bare, "Summary\nDocs updated first:\n");
	const res = await run(["check-pr", bare]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /name/i);
});

test("check-pr ignores quoted templates and code fences", async () => {
	const dir = tmpRepo();
	const quoted = path.join(dir, "quoted.md");
	fs.writeFileSync(
		quoted,
		"> Docs updated first: template\n```\nDocs not applicable: example\n```\nDocs not applicable: lint only\n",
	);
	assert.equal((await run(["check-pr", quoted])).code, 0);
});

// --- forgiving errors: unknown commands suggest the intended one ---

test("an unknown command suggests the closest known one", async () => {
	const light = await run(["light-ci-status"]);
	assert.equal(light.code, 1);
	assert.match(light.stderr, /unknown command "light-ci-status"/);
	assert.match(light.stderr, /did you mean "status"/);

	const typo = await run(["evidnce"]);
	assert.equal(typo.code, 1);
	assert.match(typo.stderr, /did you mean "evidence"/);
});

test("an unknown command without a close match still prints usage", async () => {
	const res = await run(["frobnicate"]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /unknown command "frobnicate"/);
	assert.ok(!/did you mean/.test(res.stderr));
	assert.match(res.stdout, /Usage: stdd/);
});

test("the AGENTS snippet names the package-runner fallback for stdd", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex"]);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /pnpm exec stdd|npx --no stdd/);
	assert.match(snippet, /not on PATH/i);
});

// --- config gates: contentRules and branchPattern (V1 review, proposals 8/9) ---

async function tmpGitDir() {
	const dir = tmpRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("init", "-q", "-b", "main");
	return { dir, git };
}

test("contentRules: forbid flags matching lines with the repo-authored message", async () => {
	const { dir, git } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({
			contentRules: [
				{
					name: "idempotent migrations",
					files: "migrations/*.sql",
					forbid: "ADD COLUMN (?!IF NOT EXISTS)",
					message: "use IF NOT EXISTS",
				},
			],
		}),
	);
	fs.mkdirSync(path.join(dir, "migrations"));
	fs.writeFileSync(path.join(dir, "migrations", "0001.sql"), "ALTER TABLE t ADD COLUMN a int;\n");
	fs.writeFileSync(path.join(dir, "other.sql"), "ADD COLUMN b int;\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /migrations\/0001\.sql:1: idempotent migrations — use IF NOT EXISTS/);
	assert.ok(!/other\.sql/.test(res.stderr), "files outside the glob are not graded");
});

test("contentRules: require flags a file missing the pattern", async () => {
	const { dir, git } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({
			contentRules: [
				{ name: "log frontmatter", files: "docs/project/*.md", require: "authority: non-canonical" },
			],
		}),
	);
	fs.mkdirSync(path.join(dir, "docs", "project"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "project", "2026-01-01-x.md"), "just prose\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/project\/2026-01-01-x\.md: log frontmatter/);
});

test("contentRules: newFilesOnly grades only files added against baseRef", async () => {
	const { dir, git } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({
			baseRef: "main",
			contentRules: [
				{
					name: "replay-safe",
					files: "migrations/*.sql",
					forbid: "ADD COLUMN (?!IF NOT EXISTS)",
					newFilesOnly: true,
				},
			],
		}),
	);
	fs.mkdirSync(path.join(dir, "migrations"));
	fs.writeFileSync(path.join(dir, "migrations", "0001.sql"), "ADD COLUMN old int;\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("checkout", "-qb", "feat/x");
	fs.writeFileSync(path.join(dir, "migrations", "0002.sql"), "ADD COLUMN fresh int;\n");
	await git("add", ".");
	await git("commit", "-qm", "new migration");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /0002\.sql/);
	assert.ok(!/0001\.sql/.test(res.stderr), "pre-existing files are grandfathered");
});

test("contentRules: invalid entries are rejected with an actionable message", async () => {
	const { dir } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ contentRules: [{ name: "broken", files: "x/*" }] }),
	);
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /contentRules/);
	assert.match(res.stderr, /forbid or require/);
});

test("branchPattern: a non-matching branch fails check; detached HEAD skips it", async () => {
	const { dir, git } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ branchPattern: "^(main|feat/|fix/)" }),
	);
	fs.writeFileSync(path.join(dir, "a.txt"), "x\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("checkout", "-qb", "worktree-shipping-uiux");
	const bad = await run(["check", dir]);
	assert.equal(bad.code, 1);
	assert.match(bad.stderr, /branch "worktree-shipping-uiux" does not match branchPattern/);

	await git("checkout", "-qb", "feat/good-name");
	assert.equal((await run(["check", dir])).code, 0);

	await git("checkout", "-q", "--detach");
	assert.equal((await run(["check", dir])).code, 0, "detached checkouts (CI) skip the rule");
});

test("check-pr names the line numbers when the body carries duplicate evidence lines", async () => {
	const body = path.join(tmpRepo(), "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/a.md\n\nDocs not applicable: also this\n");
	const res = await run(["check-pr", body]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /2 docs evidence lines \(lines 1, 3\)/);
});

// --- the init configurator: capability profile, local recipes, interview, session hook ---

test("init compiles playbooks against the capability profile", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ capabilities: { subagents: false, crossCli: true, worktrees: false } }),
	);
	const res = await run(["init", dir, "--tools", "claude,codex"]);
	assert.equal(res.code, 0, res.stderr);
	const slice = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-delegate-slice", "SKILL.md"),
		"utf8",
	);
	assert.ok(!/never your session history/.test(slice), "subagents-off block is stripped");
	assert.match(slice, /codex exec/, "crossCli-on block survives");
	assert.ok(!/cap:/.test(slice), "no marker residue");
	const copy = fs.readFileSync(path.join(dir, ".stdd", "playbooks", "delegate-slice.md"), "utf8");
	assert.ok(!/never your session history/.test(copy), "the agent-neutral copy is compiled too");
	assert.ok(
		!fs.existsSync(path.join(dir, ".claude", "skills", "stdd-worktrees")),
		"requires: worktrees playbook is skipped",
	);
	assert.ok(!fs.existsSync(path.join(dir, ".stdd", "playbooks", "worktrees.md")));
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.ok(!/worktrees\.md/.test(snippet), "skipped playbook is not listed");
});

test("init with default capabilities keeps today's output", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const slice = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-delegate-slice", "SKILL.md"),
		"utf8",
	);
	assert.match(slice, /never your session history/);
	assert.ok(!/codex exec/.test(slice), "crossCli defaults off");
	assert.ok(fs.existsSync(path.join(dir, ".claude", "skills", "stdd-worktrees", "SKILL.md")));
});

test("init --capabilities writes the profile into the config, keeping other keys", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex", "--capabilities", "crossCli,worktrees"]);
	const config = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "config.json"), "utf8"));
	assert.deepEqual(config.capabilities, { subagents: false, crossCli: true, worktrees: true });

	const dir2 = tmpRepo();
	fs.mkdirSync(path.join(dir2, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir2, ".stdd", "config.json"), JSON.stringify({ baseRef: "origin/main" }));
	await run(["init", dir2, "--tools", "codex", "--capabilities", "subagents"]);
	const config2 = JSON.parse(fs.readFileSync(path.join(dir2, ".stdd", "config.json"), "utf8"));
	assert.equal(config2.baseRef, "origin/main", "existing config keys survive");
	assert.deepEqual(config2.capabilities, { subagents: true, crossCli: false, worktrees: false });

	const bad = await run(["init", tmpRepo(), "--capabilities", "teleport"]);
	assert.equal(bad.code, 1);
	assert.match(bad.stderr, /teleport/);
});

test("re-init removes generated files the new profile no longer produces", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const wt = path.join(dir, ".claude", "skills", "stdd-worktrees", "SKILL.md");
	assert.ok(fs.existsSync(wt));
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ capabilities: { worktrees: false } }),
	);
	await run(["init", dir, "--tools", "claude"]);
	assert.ok(!fs.existsSync(wt), "stale generated skill is removed");
	const check = await run(["check", dir]);
	assert.equal(check.code, 0, check.stderr);
});

test("local recipes compile to skills, land in the snippet, and override the kit by name", async () => {
	const dir = tmpRepo();
	const local = path.join(dir, ".stdd", "playbooks", "local");
	fs.mkdirSync(local, { recursive: true });
	fs.writeFileSync(
		path.join(local, "deploy.md"),
		"---\nname: acme-deploy\ndescription: Deploy the acme stack\nwhen: Releasing to production.\n---\n\nRun the deploy pipeline.\n",
	);
	fs.writeFileSync(
		path.join(local, "debugging.md"),
		"---\nname: stdd-debugging\ndescription: Project debugging override\n---\n\nProject-specific debugging.\n",
	);
	const res = await run(["init", dir, "--tools", "claude,codex"]);
	assert.equal(res.code, 0, res.stderr);
	const deploy = fs.readFileSync(path.join(dir, ".claude", "skills", "acme-deploy", "SKILL.md"), "utf8");
	assert.match(deploy, /Deploy the acme stack/);
	const dbg = fs.readFileSync(path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md"), "utf8");
	assert.match(dbg, /Project-specific debugging/);
	assert.match(res.stdout, /overrides/);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /deploy\.md/);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.equal(manifest.files[".stdd/playbooks/local/deploy.md"], undefined, "sources are user-owned");
	assert.ok(manifest.files[".claude/skills/acme-deploy/SKILL.md"], "generated skills are manifested");
});

test("a local recipe without frontmatter fails init with the file named", async () => {
	const dir = tmpRepo();
	const local = path.join(dir, ".stdd", "playbooks", "local");
	fs.mkdirSync(local, { recursive: true });
	fs.writeFileSync(path.join(local, "bad.md"), "no frontmatter here\n");
	const res = await run(["init", dir, "--tools", "claude"]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /bad\.md/);
});

test("init --interview asks one question at a time and applies the answers", async () => {
	const dir = tmpRepo();
	// tools=claude, subagents=default(Y), crossCli=y, worktrees=n, ci=n, hooks=n, session-hook=n
	const answers = "claude\n\ny\nn\nn\nn\nn\n";
	const out = execFileSync(process.execPath, [CLI, "init", dir, "--interview"], {
		input: answers,
		encoding: "utf8",
	});
	assert.match(out, /\[Y\/n\]/, "the recommended answer leads");
	const config = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "config.json"), "utf8"));
	assert.deepEqual(config.capabilities, { subagents: true, crossCli: true, worktrees: false });
	assert.ok(fs.existsSync(path.join(dir, ".claude", "skills", "stdd-planning", "SKILL.md")));
	assert.ok(!fs.existsSync(path.join(dir, ".stdd", "AGENTS-snippet.md")), "codex not selected");
	assert.ok(!fs.existsSync(path.join(dir, ".github", "workflows", "stdd.yml")), "ci declined");
	assert.ok(!fs.existsSync(path.join(dir, ".stdd", "hooks", "pre-push")), "hooks declined");
	assert.ok(!fs.existsSync(path.join(dir, ".claude", "settings.json")), "session hook declined");

	const conflict = await run(["init", dir, "--interview", "--tools", "codex"]);
	assert.equal(conflict.code, 1);
	assert.match(conflict.stderr, /--interview/);
});

test("init --session-hook merges a SessionStart hook without duplicating or clobbering", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude", "--session-hook"]);
	const settingsPath = path.join(dir, ".claude", "settings.json");
	const settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
	const entry = settings.hooks.SessionStart[0];
	assert.equal(entry.matcher, "startup|clear|compact");
	assert.match(entry.hooks[0].command, /stdd status/);

	await run(["init", dir, "--tools", "claude", "--session-hook"]);
	const again = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
	assert.equal(again.hooks.SessionStart.length, 1, "idempotent");

	fs.writeFileSync(
		settingsPath,
		JSON.stringify({ model: "opus", hooks: { PreToolUse: [] } }, null, "\t"),
	);
	await run(["init", dir, "--tools", "claude", "--session-hook"]);
	const merged = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
	assert.equal(merged.model, "opus", "existing settings survive the merge");
	assert.ok(Array.isArray(merged.hooks.PreToolUse));
	assert.equal(merged.hooks.SessionStart.length, 1);

	fs.writeFileSync(settingsPath, "{broken");
	const res = await run(["init", dir, "--tools", "claude", "--session-hook"]);
	assert.equal(res.code, 0);
	assert.equal(fs.readFileSync(settingsPath, "utf8"), "{broken", "unparseable settings untouched");
	assert.match(`${res.stdout}${res.stderr}`, /does not parse/i);
});

// --- the durable plan: check bans committing stdd's own bookkeeping ---

test("check fails when the plan or the ledger is a tracked file", async () => {
	const { dir, git } = await tmpGitDir();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "plan.md"), "- [ ] step\n");
	fs.writeFileSync(path.join(dir, ".stdd", "ledger.jsonl"), "");
	fs.writeFileSync(path.join(dir, "readme.md"), "hi\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /\.stdd\/plan\.md: committed stdd working artifact/);
	assert.match(res.stderr, /\.stdd\/ledger\.jsonl: committed stdd working artifact/);
});

test("check ignores an untracked plan", async () => {
	const { dir, git } = await tmpGitDir();
	fs.writeFileSync(path.join(dir, "readme.md"), "hi\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "plan.md"), "- [ ] step\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 0);
});

// --- delegation choreography lands in the generated playbooks ---

test("the delegate-slice skill carries the worker protocol and review verdicts", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-delegate-slice", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /DONE \| DONE_WITH_CONCERNS \| BLOCKED \| NEEDS_CONTEXT/);
	assert.match(skill, /before starting|before the first edit/i);
	assert.match(skill, /missing.*extra.*misunderstood/is);
	assert.match(skill, /never your session history/);
	assert.match(skill, /model explicitly/i);
});

test("the pr-green skill centers on stdd ci --watch with a recognition table", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-pr-green", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /stdd ci --watch/);
	assert.match(skill, /Recognition table/);
	assert.match(skill, /current head/);
});

test("the planning skill closes with the execution choice and the closing review", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-planning", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /Delegated.*delegate-slice/s);
	assert.match(skill, /Inline/);
	assert.match(skill, /one batched question/);
	assert.ok(
		!/the default when steps are independent/.test(skill),
		"delegation is an optimization, never mandated",
	);
	assert.match(skill, /## The closing review/);
	assert.match(skill, /never the implementing\s+session's history/);
	assert.match(skill, /fresh read-only subagent/); // cap:subagents default on
});

test("skill descriptions carry the playbook's when line", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-delegate-slice", "SKILL.md"),
		"utf8",
	);
	const description = skill.match(/^description: (.*)$/m)?.[1] ?? "";
	assert.match(description, /Use when: Before implementing a multi-step change/);
});

test("init creates AGENTS.md with the managed STDD section when absent", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex"]);
	const agents = fs.readFileSync(path.join(dir, "AGENTS.md"), "utf8");
	assert.match(agents, /<!-- stdd:begin/);
	assert.match(agents, /^## STDD$/m);
	assert.match(agents, /<!-- stdd:end -->/);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.equal(manifest.files["AGENTS.md"], undefined, "AGENTS.md is user-owned");
});

test("init replaces only the marked STDD section of an existing AGENTS.md", async () => {
	const dir = tmpRepo();
	fs.writeFileSync(path.join(dir, "AGENTS.md"), "# House rules\n\nBe kind.\n");
	await run(["init", dir, "--tools", "codex"]);
	const first = fs.readFileSync(path.join(dir, "AGENTS.md"), "utf8");
	assert.match(first, /# House rules/);
	assert.match(first, /Be kind\./);
	assert.match(first, /<!-- stdd:begin/);

	await run(["init", dir, "--tools", "codex"]);
	assert.equal(fs.readFileSync(path.join(dir, "AGENTS.md"), "utf8"), first, "re-init is a no-op");

	fs.writeFileSync(path.join(dir, "AGENTS.md"), first.replace("Be kind.", "Be kind. Ship small."));
	await run(["init", dir, "--tools", "codex"]);
	const third = fs.readFileSync(path.join(dir, "AGENTS.md"), "utf8");
	assert.match(third, /Ship small\./, "user content outside the markers survives");
	assert.equal(third.match(/<!-- stdd:begin/g).length, 1, "replaced in place, not appended");

	// a CRLF checkout still replaces the section instead of appending a twin
	fs.writeFileSync(path.join(dir, "AGENTS.md"), third.replaceAll("\n", "\r\n"));
	await run(["init", dir, "--tools", "codex"]);
	const crlf = fs.readFileSync(path.join(dir, "AGENTS.md"), "utf8");
	assert.equal(crlf.match(/<!-- stdd:begin/g).length, 1, "CRLF section is replaced, not duplicated");
});
