import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const exec = promisify(execFile);
const CLI = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "cli", "stdd.mjs");

function tmpRepo() {
	return fs.mkdtempSync(path.join(os.tmpdir(), "stdd-test-"));
}

async function run(args, opts = {}) {
	try {
		const { stdout, stderr } = await exec("node", [CLI, ...args], opts);
		return { code: 0, stdout, stderr };
	} catch (err) {
		return { code: err.code ?? 1, stdout: err.stdout ?? "", stderr: err.stderr ?? "" };
	}
}

test("init installs .stdd, Claude skills, and the AGENTS snippet", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "claude,codex"]);
	assert.equal(res.code, 0);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "method.md")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "config.json")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "AGENTS-snippet.md")));
	const skills = fs.readdirSync(path.join(dir, ".claude", "skills"));
	assert.ok(skills.includes("stdd-brainstorming"));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-brainstorming", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /^---\nname: stdd-brainstorming\ndescription: .+\n---\n/);
	assert.match(skill, /generated by stdd v/);
});

test("init is idempotent and preserves an existing config", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const configPath = path.join(dir, ".stdd", "config.json");
	fs.writeFileSync(configPath, JSON.stringify({ temporalPhrases: ["formerly"] }));
	const res = await run(["init", dir, "--tools", "claude"]);
	assert.equal(res.code, 0);
	assert.deepEqual(JSON.parse(fs.readFileSync(configPath, "utf8")).temporalPhrases, ["formerly"]);
});

test("check reports artifacts and temporal narrative, exits 1", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.mkdirSync(path.join(dir, "docs", "plans"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, "docs", "domain", "order.md"),
		"The order previously shipped.\nno longer-lived tokens are fine.\n",
	);
	fs.writeFileSync(path.join(dir, "docs", "plans", "p.md"), "step 1\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/plans\/p\.md: committed working artifact/);
	assert.match(res.stderr, /order\.md:1: temporal narrative .* \("previously"\)/);
	assert.ok(!res.stderr.includes(":2:"), "hyphenated compound must not match");
});

test("check passes on a clean repo", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Orders ship after review.\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /stdd check: OK/);
});

test("check flags stale generated-file stamps", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skillPath = path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md");
	fs.writeFileSync(
		skillPath,
		fs.readFileSync(skillPath, "utf8").replace(/generated by stdd v[^\s]+/, "generated by stdd v0.0.0"),
	);
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /re-run stdd init/);
});

test("check rejects invalid config with a useful error", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "config.json"), '{"canonicalDocs": "oops"}');
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /"canonicalDocs" must be an array of strings/);
});

test("strict argument parsing fails loudly", async () => {
	const dir = tmpRepo();
	assert.equal((await run(["check", dir, "--unknown"])).code, 1);
	assert.equal((await run(["check", dir, "--tools", "claude"])).code, 1);
	const badTool = await run(["init", dir, "--tools", "nope"]);
	assert.equal(badTool.code, 1);
	assert.match(badTool.stderr, /unknown tool\(s\): nope/);
	assert.equal((await run(["check", dir, "extra"])).code, 1);
});

test("check-pr accepts exactly one evidence line", async () => {
	const dir = tmpRepo();
	const ok = path.join(dir, "ok.md");
	fs.writeFileSync(ok, "Body\nDocs not applicable: lint only\n");
	assert.equal((await run(["check-pr", ok])).code, 0);

	const missing = path.join(dir, "missing.md");
	fs.writeFileSync(missing, "no evidence\n");
	const res = await run(["check-pr", missing]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no docs evidence line/);

	const double = path.join(dir, "double.md");
	fs.writeFileSync(double, "Docs updated first: a\nDocs not applicable: b\n");
	const dres = await run(["check-pr", double]);
	assert.equal(dres.code, 1);
	assert.match(dres.stderr, /more than one/);
});
