import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const exec = promisify(execFile);
const CLI = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "cli", "stdd.mjs");

function tmpRepo() {
	return fs.mkdtempSync(path.join(os.tmpdir(), "stdd-test-"));
}

async function run(args, opts = {}) {
	try {
		const { stdout, stderr } = await exec("node", [CLI, ...args], opts);
		return { code: 0, stdout, stderr };
	} catch (err) {
		return { code: err.code ?? 1, stdout: err.stdout ?? "", stderr: err.stderr ?? "" };
	}
}

test("init installs .stdd, Claude skills, and the AGENTS snippet", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "claude,codex"]);
	assert.equal(res.code, 0);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "method.md")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "config.json")));
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "AGENTS-snippet.md")));
	const skills = fs.readdirSync(path.join(dir, ".claude", "skills"));
	assert.ok(skills.includes("stdd-brainstorming"));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-brainstorming", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /^---\nname: stdd-brainstorming\ndescription: .+\n---\n/);
	assert.match(skill, /generated by stdd v/);
});

test("init installs the pr-green playbook as a skill and lists it for codex", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	assert.ok(fs.existsSync(path.join(dir, ".stdd", "playbooks", "pr-green.md")));
	const skill = fs.readFileSync(
		path.join(dir, ".claude", "skills", "stdd-pr-green", "SKILL.md"),
		"utf8",
	);
	assert.match(skill, /terminal-green|terminal green/i);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /pr-green\.md/);
});

test("init generates the project-log retrieval rule for agents", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "codex"]);
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	assert.match(snippet, /[Dd]o not search the project log/);
	assert.match(snippet, /explicitly asks/);
});

test("init is idempotent and preserves an existing config", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const configPath = path.join(dir, ".stdd", "config.json");
	fs.writeFileSync(configPath, JSON.stringify({ temporalPhrases: ["formerly"] }));
	const res = await run(["init", dir, "--tools", "claude"]);
	assert.equal(res.code, 0);
	assert.deepEqual(JSON.parse(fs.readFileSync(configPath, "utf8")).temporalPhrases, ["formerly"]);
});

test("init --ci github writes the stdd workflow with a live body fetch", async () => {
	const dir = tmpRepo();
	const res = await run(["init", dir, "--tools", "claude", "--ci", "github"]);
	assert.equal(res.code, 0);
	const wf = fs.readFileSync(path.join(dir, ".github", "workflows", "stdd.yml"), "utf8");
	assert.match(wf, /generated by stdd v/);
	assert.match(wf, /types: \[opened, edited, synchronize, reopened\]/);
	assert.match(wf, /fetch-depth: 0/);
	assert.match(wf, /set -o pipefail/);
	assert.match(wf, /node --input-type=module/);
	assert.ok(!wf.includes("gh api"), "the generated workflow must not depend on the gh CLI");
	assert.ok(!/\$\{(?!\{)/.test(wf), "no JS template literals in the shell script (SC2016)");
	assert.ok(
		!wf.includes("github.event.pull_request.body"),
		"the generated workflow must not read the frozen event payload body",
	);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.match(manifest.files[".github/workflows/stdd.yml"], /^sha256:/);
});

test("plain init never touches .github", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	assert.ok(!fs.existsSync(path.join(dir, ".github")));
});

test("init rejects an unknown --ci value; --ci is init-only", async () => {
	const dir = tmpRepo();
	const bad = await run(["init", dir, "--ci", "gitlab"]);
	assert.equal(bad.code, 1);
	assert.match(bad.stderr, /unknown ci/i);
	assert.equal((await run(["check", dir, "--ci", "github"])).code, 1);
});

test("doctor flags a workflow validating the frozen payload body without an edited trigger", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".github", "workflows"), { recursive: true });
	const stale = [
		"on:",
		"  pull_request:",
		"    types: [opened, synchronize]",
		"jobs:",
		"  stdd:",
		"    steps:",
		"      - env:",
		"          PR_BODY: ${{ github.event.pull_request.body }}",
		"        run: printf '%s' \"$PR_BODY\" | npx @stdd/cli check-pr -",
		"",
	].join("\n");
	fs.writeFileSync(path.join(dir, ".github", "workflows", "ci.yml"), stale);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .*frozen event payload|✗ .*body edits will not be re-checked/i);

	fs.writeFileSync(
		path.join(dir, ".github", "workflows", "ci.yml"),
		stale.replace("types: [opened, synchronize]", "types: [opened, edited, synchronize]"),
	);
	const ok = await run(["doctor", dir]);
	assert.ok(!/body edits will not be re-checked/i.test(ok.stdout));
});

test("doctor flags a PR template whose placeholder would pass the evidence gate", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".github"), { recursive: true });
	const tpl = path.join(dir, ".github", "pull_request_template.md");
	fs.writeFileSync(tpl, "## Summary\n\nDocs updated first: <fill in>\n");
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .*pull_request_template.*evidence/i);

	fs.writeFileSync(tpl, "## Summary\n\n> Docs updated first: <fill in>\n");
	const ok = await run(["doctor", dir]);
	assert.ok(!/pull_request_template.*evidence/i.test(ok.stdout));
});

test("check reports artifacts and temporal narrative, exits 1", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.mkdirSync(path.join(dir, "docs", "plans"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, "docs", "domain", "order.md"),
		"The order previously shipped.\nno longer-lived tokens are fine.\n",
	);
	fs.writeFileSync(path.join(dir, "docs", "plans", "p.md"), "step 1\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/plans\/p\.md: committed working artifact/);
	assert.match(res.stderr, /order\.md:1: temporal narrative .* \("previously"\)/);
	assert.ok(!res.stderr.includes(":2:"), "hyphenated compound must not match");
});

test("check passes on a clean repo", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Orders ship after review.\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /stdd check: OK/);
});

test("init records generated files in .stdd/manifest.json", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	const manifest = JSON.parse(fs.readFileSync(path.join(dir, ".stdd", "manifest.json"), "utf8"));
	assert.equal(manifest.generatedBy, "stdd");
	assert.ok(manifest.version.length > 0);
	assert.match(manifest.files[".stdd/method.md"], /^sha256:[0-9a-f]{64}$/);
	assert.ok(manifest.files[".claude/skills/stdd-debugging/SKILL.md"]);
	assert.ok(manifest.files[".stdd/AGENTS-snippet.md"]);
	assert.equal(manifest.files[".stdd/config.json"], undefined, "config is user-owned");
});

test("check passes right after init and flags hand-edited generated files", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	assert.equal((await run(["check", dir])).code, 0);

	const playbook = path.join(dir, ".stdd", "playbooks", "debugging.md");
	fs.appendFileSync(playbook, "\nlocal tweak\n");
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /\.stdd\/playbooks\/debugging\.md: .*edited by hand or stale/);
});

test("check flags generated files missing from disk", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	fs.rmSync(path.join(dir, ".stdd", "method.md"));
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /\.stdd\/method\.md: .*missing/);
});

test("check flags stale generated-file stamps", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	const skillPath = path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md");
	fs.writeFileSync(
		skillPath,
		fs.readFileSync(skillPath, "utf8").replace(/generated by stdd v[^\s]+/, "generated by stdd v0.0.0"),
	);
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /re-run stdd init/);
});

test("check rejects invalid config with a useful error", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "config.json"), '{"canonicalDocs": "oops"}');
	const res = await run(["check", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /"canonicalDocs" must be an array of strings/);
});

test("strict argument parsing fails loudly", async () => {
	const dir = tmpRepo();
	assert.equal((await run(["check", dir, "--unknown"])).code, 1);
	assert.equal((await run(["check", dir, "--tools", "claude"])).code, 1);
	const badTool = await run(["init", dir, "--tools", "nope"]);
	assert.equal(badTool.code, 1);
	assert.match(badTool.stderr, /unknown tool\(s\): nope/);
	assert.equal((await run(["check", dir, "extra"])).code, 1);
});

test("check-pr accepts exactly one evidence line", async () => {
	const dir = tmpRepo();
	const ok = path.join(dir, "ok.md");
	fs.writeFileSync(ok, "Body\nDocs not applicable: lint only\n");
	assert.equal((await run(["check-pr", ok])).code, 0);

	const missing = path.join(dir, "missing.md");
	fs.writeFileSync(missing, "no evidence\n");
	const res = await run(["check-pr", missing]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no docs evidence line/);

	const double = path.join(dir, "double.md");
	fs.writeFileSync(double, "Docs updated first: a\nDocs not applicable: b\n");
	const dres = await run(["check-pr", double]);
	assert.equal(dres.code, 1);
	assert.match(dres.stderr, /more than one/);
});

test("doctor reports missing readiness paths with their hints", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({
			readiness: {
				required: [
					{ path: "node_modules", hint: "pnpm install --frozen-lockfile" },
					{ path: "apps/api/.env" },
				],
			},
		}),
	);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ node_modules missing — pnpm install --frozen-lockfile/);
	assert.match(res.stdout, /✗ apps\/api\/\.env missing/);
});

test("doctor --readiness runs only the readiness section", async () => {
	const dir = tmpRepo(); // no .stdd install, no docs — full doctor would fail loudly
	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.mkdirSync(path.join(dir, "node_modules"), { recursive: true });
	fs.writeFileSync(
		path.join(dir, ".stdd", "config.json"),
		JSON.stringify({ readiness: { required: [{ path: "node_modules", hint: "install" }] } }),
	);
	const res = await run(["doctor", dir, "--readiness"]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /✓ worktree ready \(1\/1 present\)/);
	assert.ok(!res.stdout.includes("canonical docs"), "--readiness must skip adoption checks");

	const empty = tmpRepo();
	const none = await run(["doctor", empty, "--readiness"]);
	assert.equal(none.code, 0);
	assert.match(none.stdout, /no readiness contract declared/);
});

test("--readiness is only valid for doctor", async () => {
	const dir = tmpRepo();
	assert.equal((await run(["check", dir, "--readiness"])).code, 1);
});

test("doctor reports findings on a messy repo and exits 1", async () => {
	const dir = tmpRepo();
	fs.mkdirSync(path.join(dir, "docs", "plans"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "plans", "old-plan.md"), "step 1\n");
	fs.writeFileSync(path.join(dir, "AGENTS.md"), "# Rules\n");
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ .stdd\/ is not installed/);
	assert.match(res.stdout, /✗ no canonical docs found/);
	assert.match(res.stdout, /✗ 1 committed working artifact/);
	assert.match(res.stdout, /✗ AGENTS\.md has no STDD section/);
});

test("doctor passes on a healthy stdd repo and exits 0", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude,codex"]);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Orders ship after review.\n");
	const snippet = fs.readFileSync(path.join(dir, ".stdd", "AGENTS-snippet.md"), "utf8");
	fs.writeFileSync(path.join(dir, "AGENTS.md"), `# Rules\n\n${snippet}`);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 0);
	assert.match(res.stdout, /✓ .stdd\/ installed/);
	assert.match(res.stdout, /✓ canonical docs present/);
	assert.match(res.stdout, /✓ no committed working artifacts/);
	assert.match(res.stdout, /✓ AGENTS\.md carries the STDD section/);
});

test("doctor counts temporal narrative and stale generated files", async () => {
	const dir = tmpRepo();
	await run(["init", dir, "--tools", "claude"]);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "order.md"), "Previously orders shipped.\n");
	const skillPath = path.join(dir, ".claude", "skills", "stdd-debugging", "SKILL.md");
	fs.writeFileSync(
		skillPath,
		fs.readFileSync(skillPath, "utf8").replace(/generated by stdd v[^\s]+/, "generated by stdd v0.0.0"),
	);
	const res = await run(["doctor", dir]);
	assert.equal(res.code, 1);
	assert.match(res.stdout, /✗ 1 canonical doc contains temporal narrative/);
	assert.match(res.stdout, /✗ 1 generated file is stale/);
});

async function tmpGitRepo() {
	const dir = tmpRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("init", "-q", "-b", "main");
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are net.\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("checkout", "-qb", "feature");
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are gross.\n");
	fs.writeFileSync(path.join(dir, "impl.js"), "export {};\n");
	await git("add", ".");
	await git("commit", "-qm", "change");
	return dir;
}

test("check-pr --base passes when claimed docs really changed", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/pricing.md\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
});

test("check-pr --base fails when a claimed doc is not in the diff", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/unrelated.md\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /docs\/domain\/unrelated\.md/);
	assert.match(res.stderr, /not changed/);
});

test("check-pr --base fails when 'updated first' names no path at all", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: see the description\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no doc paths/i);
});

test("check-pr --base verifies 'checked, no change needed' paths exist", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs checked, no change needed: docs/domain/pricing.md — covered\n");
	assert.equal((await run(["check-pr", body, "--base", "main"], { cwd: dir })).code, 0);

	fs.writeFileSync(body, "Docs checked, no change needed: docs/domain/ghost.md — covered\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /ghost\.md/);
	assert.match(res.stderr, /does not exist/);
});

test("check-pr without --base keeps text-only behavior", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: docs/domain/unrelated.md\n");
	assert.equal((await run(["check-pr", body], { cwd: dir })).code, 0);
});

test("check-pr failure points at a near-miss line with a corrected form", async () => {
	const dir = tmpRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Summary\n\n**Docs updated first:** docs/domain/orgs.md\n");
	const res = await run(["check-pr", body]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /near-miss/);
	assert.match(res.stderr, /line 3/);
	assert.match(res.stderr, /found: \*\*Docs updated first:\*\* docs\/domain\/orgs\.md/);
	assert.match(res.stderr, /fix: {3}Docs updated first: docs\/domain\/orgs\.md/);
	assert.match(res.stderr, /column 0/);
});

test("check-pr failure without a near-miss keeps the generic message", async () => {
	const dir = tmpRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "no evidence here\n");
	const res = await run(["check-pr", body]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no docs evidence line/);
	assert.ok(!res.stderr.includes("near-miss"));
});

test("check-pr --base suggests the correct label for sentinel content", async () => {
	const dir = await tmpGitRepo();
	const body = path.join(dir, "pr.md");
	fs.writeFileSync(body, "Docs updated first: not applicable\n");
	const res = await run(["check-pr", body, "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /no doc paths/i);
	assert.match(res.stderr, /Docs not applicable: <why implementation-only>/);
});

/**
 * A repo with a real `origin` (bare sibling): main pushed, a feature branch
 * with a docs change checked out. Returns paths plus a PATH prefix holding a
 * fake `gh` that prints the JSON written to `ghOutput`.
 */
async function tmpGitRepoWithOrigin() {
	const root = tmpRepo();
	const origin = path.join(root, "origin.git");
	const dir = path.join(root, "work");
	fs.mkdirSync(dir);
	await exec("git", ["init", "-q", "--bare", origin]);
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("init", "-q", "-b", "main");
	await git("remote", "add", "origin", origin);
	fs.mkdirSync(path.join(dir, "docs", "domain"), { recursive: true });
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are net.\n");
	await git("add", ".");
	await git("commit", "-qm", "base");
	await git("push", "-q", "origin", "main");
	await git("checkout", "-qb", "feature");
	fs.writeFileSync(path.join(dir, "docs", "domain", "pricing.md"), "Prices are gross.\n");
	await git("add", ".");
	await git("commit", "-qm", "change");

	const bin = path.join(root, "bin");
	fs.mkdirSync(bin);
	const ghOutput = path.join(root, "gh.json");
	fs.writeFileSync(path.join(bin, "gh"), `#!/bin/sh\ncat "${ghOutput}"\n`, { mode: 0o755 });
	const env = {
		...process.env,
		PATH: `${bin}${path.delimiter}${path.dirname(process.execPath)}${path.delimiter}${process.env.PATH}`,
	};
	const headSha = (await git("rev-parse", "HEAD")).stdout.trim();
	return { dir, git, ghOutput, env, headSha };
}

test("check-pr --pr validates the live body against the PR's base and head", async () => {
	const { dir, ghOutput, env, headSha } = await tmpGitRepoWithOrigin();
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: headSha,
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 0);
	assert.match(res.stdout, /OK \(PR #7 body, base origin\/main, head [0-9a-f]{7}\)/);
});

test("check-pr --pr diffs the PR head, not a diverged local checkout", async () => {
	const { dir, git, ghOutput, env, headSha } = await tmpGitRepoWithOrigin();
	await git("update-ref", "refs/heads/tmp-pr", headSha);
	await git("push", "-q", "origin", "refs/heads/tmp-pr:refs/pull/7/head");
	await git("checkout", "-q", "main"); // local HEAD no longer matches the PR head
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: headSha,
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 0, res.stderr);
});

test("check-pr --pr fails when the PR head cannot be resolved", async () => {
	const { dir, git, ghOutput, env } = await tmpGitRepoWithOrigin();
	await git("checkout", "-q", "main");
	fs.writeFileSync(
		ghOutput,
		JSON.stringify({
			body: "Docs updated first: docs/domain/pricing.md\n",
			baseRefName: "main",
			headRefOid: "0123456789abcdef0123456789abcdef01234567",
			number: 7,
		}),
	);
	const res = await run(["check-pr", "--pr", "7"], { cwd: dir, env });
	assert.equal(res.code, 1);
	assert.match(res.stderr, /local HEAD differs from PR head/);
});

test("check-pr --pr is exclusive with the body file and --base, and needs gh", async () => {
	const { dir, env } = await tmpGitRepoWithOrigin();
	const both = await run(["check-pr", "body.md", "--pr", "7"], { cwd: dir, env });
	assert.equal(both.code, 1);
	assert.match(both.stderr, /--pr replaces/);

	const withBase = await run(["check-pr", "--pr", "7", "--base", "main"], { cwd: dir, env });
	assert.equal(withBase.code, 1);
	assert.match(withBase.stderr, /--pr derives the base/);

	const noGh = await run(["check-pr", "--pr", "7"], {
		cwd: dir,
		env: { ...process.env, PATH: path.dirname(process.execPath) },
	});
	assert.equal(noGh.code, 1);
	assert.match(noGh.stderr, /GitHub CLI|gh/);
});

test("evidence prints a finished 'Docs updated first' line when canonical docs changed", async () => {
	const dir = await tmpGitRepo();
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
	assert.equal(res.stdout, "Docs updated first: docs/domain/pricing.md\n");
});

test("evidence lists every changed canonical doc on one line", async () => {
	const dir = await tmpGitRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	fs.writeFileSync(path.join(dir, "docs", "domain", "auth.md"), "Sessions expire.\n");
	await git("add", ".");
	await git("commit", "-qm", "more docs");
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 0);
	assert.equal(res.stdout, "Docs updated first: docs/domain/auth.md, docs/domain/pricing.md\n");
});

test("evidence exits nonzero with templates on stderr when no canonical docs changed", async () => {
	const dir = await tmpGitRepo();
	const git = (...args) =>
		exec("git", ["-C", dir, "-c", "user.email=t@t", "-c", "user.name=t", ...args]);
	await git("checkout", "-qb", "impl-only", "main");
	fs.writeFileSync(path.join(dir, "util.js"), "export {};\n");
	await git("add", ".");
	await git("commit", "-qm", "impl");
	const res = await run(["evidence", "--base", "main"], { cwd: dir });
	assert.equal(res.code, 1);
	assert.equal(res.stdout, "", "stdout must stay empty so $(...) cannot embed a template");
	assert.match(res.stderr, /Docs checked, no change needed: <docs \+ reason>/);
	assert.match(res.stderr, /Docs not applicable: <why implementation-only>/);
});

test("evidence requires a base: --base flag or config baseRef", async () => {
	const dir = await tmpGitRepo();
	const missing = await run(["evidence"], { cwd: dir });
	assert.equal(missing.code, 1);
	assert.match(missing.stderr, /--base|baseRef/);

	fs.mkdirSync(path.join(dir, ".stdd"), { recursive: true });
	fs.writeFileSync(path.join(dir, ".stdd", "config.json"), '{"baseRef": "main"}');
	const fromConfig = await run(["evidence"], { cwd: dir });
	assert.equal(fromConfig.code, 0);
	assert.equal(fromConfig.stdout, "Docs updated first: docs/domain/pricing.md\n");
});

test("check-pr rejects a bare evidence label", async () => {
	const dir = tmpRepo();
	const bare = path.join(dir, "bare.md");
	fs.writeFileSync(bare, "Summary\nDocs updated first:\n");
	const res = await run(["check-pr", bare]);
	assert.equal(res.code, 1);
	assert.match(res.stderr, /name/i);
});

test("check-pr ignores quoted templates and code fences", async () => {
	const dir = tmpRepo();
	const quoted = path.join(dir, "quoted.md");
	fs.writeFileSync(
		quoted,
		"> Docs updated first: template\n```\nDocs not applicable: example\n```\nDocs not applicable: lint only\n",
	);
	assert.equal((await run(["check-pr", quoted])).code, 0);
});
