import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { compileCapabilities, DEFAULT_CONFIG, parseFrontmatter } from "../cli/lib.mjs";
import { buildPlugin } from "../scripts/build-plugin.mjs";
import { renderAgentSkill } from "../sdk/adapters.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const plugin = path.join(ROOT, "plugins", "stdd");

function pluginBuildFixture() {
	const root = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-build-"));
	fs.cpSync(path.join(ROOT, "playbooks"), path.join(root, "playbooks"), { recursive: true });
	fs.cpSync(plugin, path.join(root, "plugins", "stdd"), { recursive: true });
	fs.writeFileSync(path.join(root, "package.json"), '{"version":"9.9.9"}');
	return {
		root,
		pluginRoot: path.join(root, "plugins", "stdd"),
	};
}

function withPatchedFs(patches, action) {
	const capturedNames = new Set([
		...Object.keys(patches),
		"mkdirSync",
		"openSync",
		"realpathSync",
		"renameSync",
		"rmSync",
	]);
	const originals = Object.fromEntries([...capturedNames].map((name) => [name, fs[name]]));
	for (const [name, patch] of Object.entries(patches)) fs[name] = patch(originals[name], originals);
	try {
		return action();
	} finally {
		for (const [name, original] of Object.entries(originals)) fs[name] = original;
	}
}

function installPluginHookProbe(root) {
	const capturePath = path.join(root, "capture.jsonl");
	const installedCli = path.join(root, "node_modules", "@stdd", "cli", "cli", "stdd.mjs");
	fs.mkdirSync(path.dirname(installedCli), { recursive: true });
	fs.writeFileSync(
		installedCli,
		[
			'import fs from "node:fs";',
			`fs.appendFileSync(${JSON.stringify(capturePath)}, JSON.stringify({`,
			"  argv: process.argv.slice(2),",
			"  cwd: process.cwd(),",
			'  input: fs.readFileSync(0, "utf8"),',
			'}) + "\\n");',
			'process.stdout.write(process.argv[2] === "stop-hook" ? "{}\\n" : "probe-session\\n");',
		].join("\n"),
	);
	return capturePath;
}

test("the Codex plugin is version-aligned and contains every playbook skill", () => {
	const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, "package.json"), "utf8"));
	const manifest = JSON.parse(
		fs.readFileSync(path.join(plugin, ".codex-plugin", "plugin.json"), "utf8"),
	);
	assert.equal(manifest.name, "stdd");
	assert.equal(manifest.version, pkg.version);
	assert.ok(Array.isArray(manifest.interface.defaultPrompt));
	assert.ok(manifest.interface.defaultPrompt.length > 0 && manifest.interface.defaultPrompt.length <= 3);
	assert.ok(
		manifest.interface.defaultPrompt.every(
			(prompt) => typeof prompt === "string" && prompt.length > 0 && prompt.length <= 128,
		),
	);
	for (const file of fs
		.readdirSync(path.join(ROOT, "playbooks"))
		.filter((name) => name.endsWith(".md"))) {
		const { meta, body } = parseFrontmatter(fs.readFileSync(path.join(ROOT, "playbooks", file), "utf8"));
		const skill = fs.readFileSync(path.join(plugin, "skills", meta.name, "SKILL.md"), "utf8");
		assert.equal(
			skill,
			renderAgentSkill({
				adapter: "codex",
				name: meta.name,
				description: meta.description,
				when: meta.when,
				body: compileCapabilities(body, DEFAULT_CONFIG.capabilities),
				stamp: `generated by stdd plugin build v${pkg.version} — do not edit`,
			}),
		);
	}
	const planning = fs.readFileSync(path.join(plugin, "skills", "stdd-planning", "SKILL.md"), "utf8");
	assert.match(planning, /stdd review --via subagent/);
	assert.doesNotMatch(planning, /stdd review --via (?:codex|claude)|STDD_CROSS_CLI_REVIEW_VIA/);
	assert.doesNotMatch(planning, /fresh-context pass|re-read the full diff|degrades to/i);

	const planningSource = fs.readFileSync(path.join(ROOT, "playbooks", "planning.md"), "utf8");
	const { meta: planningMeta, body: planningBody } = parseFrontmatter(planningSource);
	const noRoute = renderAgentSkill({
		adapter: "codex",
		name: planningMeta.name,
		description: planningMeta.description,
		when: planningMeta.when,
		body: compileCapabilities(planningBody, {
			subagents: false,
			crossCli: false,
			worktrees: true,
		}),
		stamp: "generated",
	});
	assert.doesNotMatch(
		noRoute,
		/\[review:\]|stdd review|independent review|## The closing review|fresh-context pass|re-read the full diff|degrades to|STDD_CROSS_CLI_REVIEW_VIA/i,
	);
});

test("the supported plugin build workflow documents its Linux publication boundary", () => {
	for (const relative of ["README.md", "method/README.md"]) {
		const documentation = fs.readFileSync(path.join(ROOT, relative), "utf8");
		assert.match(
			documentation,
			/npm run build:plugin[\s\S]{0,500}Linux|Linux[\s\S]{0,500}npm run build:plugin/,
			relative,
		);
	}
});

test("plugin hooks are lifecycle-only and delegate to the project-local CLI", () => {
	const hooks = JSON.parse(fs.readFileSync(path.join(plugin, "hooks", "hooks.json"), "utf8"));
	assert.deepEqual(Object.keys(hooks.hooks), ["SessionStart", "Stop"]);
	const sessionCommand = hooks.hooks.SessionStart[0].hooks[0].command;
	const stopCommand = hooks.hooks.Stop[0].hooks[0].command;
	assert.match(sessionCommand, /stdd-hook\.mjs/);
	assert.match(stopCommand, /stdd-hook\.mjs/);
	const hostEnv = { ...process.env, CLAUDE_PLUGIN_ROOT: plugin };
	delete hostEnv.PLUGIN_ROOT;

	const repo = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-hook-"));
	const nested = path.join(repo, "packages", "app");
	const installedCli = path.join(repo, "node_modules", "@stdd", "cli", "cli", "stdd.mjs");
	fs.mkdirSync(path.join(repo, ".stdd"), { recursive: true });
	fs.mkdirSync(nested, { recursive: true });
	fs.mkdirSync(path.join(nested, ".stdd"), { recursive: true });
	fs.mkdirSync(path.dirname(installedCli), { recursive: true });
	const initialized = spawnSync("git", ["init", "-q", "-b", "main"], { cwd: repo });
	assert.equal(initialized.status, 0);
	fs.writeFileSync(
		installedCli,
		[
			'import fs from "node:fs";',
			'fs.writeFileSync(new URL("../../../../capture.json", import.meta.url), JSON.stringify({',
			"  argv: process.argv.slice(2),",
			"  cwd: process.cwd(),",
			'  input: fs.readFileSync(0, "utf8"),',
			"}));",
			'const stop = process.argv[2] === "stop-hook";',
			'const stopOutput = process.env.STDD_FAKE_STOP_OUTPUT ?? JSON.stringify({ decision: "block", reason: "keep going" });',
			'process.stdout.write(process.env.STDD_FAKE_CHILD_FAIL || process.env.STDD_FAKE_MALFORMED ? "not-json" : stop ? stopOutput : "forwarded-out");',
			'process.stderr.write(process.env.STDD_FAKE_CHILD_FAIL ? "internal failure" : "forwarded-err");',
			"process.exit(process.env.STDD_FAKE_CHILD_FAIL ? 7 : 0);",
		].join("\n"),
	);
	const helper = path.join(plugin, "scripts", "stdd-hook.mjs");
	const session = spawnSync(sessionCommand, {
		cwd: nested,
		encoding: "utf8",
		env: hostEnv,
		shell: true,
	});
	assert.equal(session.status, 0);
	assert.equal(session.stdout, "forwarded-out");
	assert.equal(session.stderr, "forwarded-err");
	assert.deepEqual(JSON.parse(fs.readFileSync(path.join(repo, "capture.json"), "utf8")).argv, [
		"status",
		"--local",
	]);

	const stop = spawnSync(stopCommand, {
		cwd: nested,
		input: '{"stop_hook_active":false}',
		encoding: "utf8",
		env: hostEnv,
		shell: true,
	});
	assert.equal(stop.status, 0);
	assert.deepEqual(JSON.parse(stop.stdout), { decision: "block", reason: "keep going" });
	assert.equal(stop.stderr, "", "Stop forwards protocol JSON only");
	const captured = JSON.parse(fs.readFileSync(path.join(repo, "capture.json"), "utf8"));
	assert.deepEqual(captured.argv, ["stop-hook", "--agent", "codex"]);
	assert.equal(captured.cwd, repo, "the nearest repository root is used");
	assert.equal(captured.input, '{"stop_hook_active":false}');

	for (const { name, child, expected } of [
		{
			name: "valid padded reason",
			child: '{"decision":"block","reason":"  keep going  "}',
			expected: { decision: "block", reason: "  keep going  " },
		},
		{
			name: "whitespace-only reason",
			child: '{"decision":"block","reason":"  \\t\\n  "}',
			expected: {},
		},
		{
			name: "extra key",
			child: '{"decision":"block","reason":"keep going","extra":true}',
			expected: {},
		},
	]) {
		const result = spawnSync(process.execPath, [helper, "stop"], {
			cwd: nested,
			input: "{}",
			encoding: "utf8",
			env: { ...process.env, STDD_FAKE_STOP_OUTPUT: child },
		});
		assert.equal(result.status, 0, `${name}: helper exit`);
		assert.equal(result.stderr, "", `${name}: helper stderr`);
		assert.deepEqual(JSON.parse(result.stdout), expected, `${name}: helper payload`);
		assert.equal(result.stdout, `${JSON.stringify(expected)}\n`, `${name}: canonical JSON`);
	}

	const failedChild = spawnSync(process.execPath, [helper, "stop"], {
		cwd: nested,
		input: "{}",
		encoding: "utf8",
		env: { ...process.env, STDD_FAKE_CHILD_FAIL: "1" },
	});
	assert.equal(failedChild.status, 0, "the child failure is fail-open");
	assert.deepEqual(JSON.parse(failedChild.stdout), {}, "child failure becomes an allow response");
	assert.equal(failedChild.stderr, "", "internal child diagnostics never break the host lifecycle");

	const malformedSuccess = spawnSync(process.execPath, [helper, "stop"], {
		cwd: nested,
		input: "{}",
		encoding: "utf8",
		env: { ...process.env, STDD_FAKE_MALFORMED: "1" },
	});
	assert.equal(malformedSuccess.status, 0);
	assert.deepEqual(
		JSON.parse(malformedSuccess.stdout),
		{},
		"malformed output becomes an allow response",
	);

	const noRepository = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-no-repo-"));
	const missingCli = spawnSync(process.execPath, [helper, "stop"], {
		cwd: noRepository,
		input: "{}",
		encoding: "utf8",
	});
	assert.equal(missingCli.status, 0);
	assert.deepEqual(JSON.parse(missingCli.stdout), {}, "missing local state still returns allow JSON");

	const directoryFd = fs.openSync(repo, "r");
	try {
		const unreadableInput = spawnSync(process.execPath, [helper, "stop"], {
			cwd: nested,
			stdio: [directoryFd, "pipe", "pipe"],
		});
		assert.equal(unreadableInput.status, 0, "an internal stdin read error is fail-open");
		assert.deepEqual(JSON.parse(unreadableInput.stdout), {});
	} finally {
		fs.closeSync(directoryFd);
	}
});

test("plugin hooks never escape a resolved nested Git checkout", () => {
	const parent = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-parent-"));
	fs.mkdirSync(path.join(parent, ".stdd"), { recursive: true });
	const capturePath = installPluginHookProbe(parent);
	assert.equal(spawnSync("git", ["init", "-q", "-b", "main"], { cwd: parent }).status, 0);

	const nestedRepo = path.join(parent, "vendor", "unrelated");
	const cwd = path.join(nestedRepo, "packages", "app");
	fs.mkdirSync(cwd, { recursive: true });
	assert.equal(spawnSync("git", ["init", "-q", "-b", "main"], { cwd: nestedRepo }).status, 0);
	const helper = path.join(plugin, "scripts", "stdd-hook.mjs");

	const session = spawnSync(process.execPath, [helper, "session"], {
		cwd,
		encoding: "utf8",
	});
	assert.equal(session.status, 0);
	assert.equal(session.stdout, "");
	assert.equal(session.stderr, "");

	const stop = spawnSync(process.execPath, [helper, "stop"], {
		cwd,
		input: '{"stop_hook_active":false}',
		encoding: "utf8",
	});
	assert.equal(stop.status, 0);
	assert.equal(stop.stdout, "{}\n");
	assert.equal(stop.stderr, "");

	const withoutGit = spawnSync(process.execPath, [helper, "session"], {
		cwd,
		encoding: "utf8",
		env: { ...process.env, PATH: path.join(parent, "missing-bin") },
	});
	assert.equal(withoutGit.status, 0);
	assert.equal(withoutGit.stdout, "");
	assert.equal(withoutGit.stderr, "");

	const symlinkedRoot = path.join(parent, "vendor", "symlinked-boundary");
	const symlinkedCwd = path.join(symlinkedRoot, "packages", "app");
	fs.mkdirSync(symlinkedCwd, { recursive: true });
	fs.symlinkSync(path.join(parent, "missing-git-dir"), path.join(symlinkedRoot, ".git"));
	const acrossSymlink = spawnSync(process.execPath, [helper, "session"], {
		cwd: symlinkedCwd,
		encoding: "utf8",
	});
	assert.equal(acrossSymlink.status, 0);
	assert.equal(acrossSymlink.stdout, "");
	assert.equal(acrossSymlink.stderr, "");
	assert.equal(
		fs.existsSync(capturePath),
		false,
		"the nested checkout must not invoke an unrelated parent CLI, even when Git cannot run",
	);
});

test("plugin hooks discover an adopting ancestor only when cwd is outside Git", () => {
	const adoptingRoot = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-non-git-"));
	fs.mkdirSync(path.join(adoptingRoot, ".stdd"), { recursive: true });
	const capturePath = installPluginHookProbe(adoptingRoot);
	const cwd = path.join(adoptingRoot, "packages", "app");
	fs.mkdirSync(cwd, { recursive: true });
	const helper = path.join(plugin, "scripts", "stdd-hook.mjs");

	const session = spawnSync(process.execPath, [helper, "session"], {
		cwd,
		encoding: "utf8",
	});
	assert.equal(session.status, 0);
	assert.equal(session.stdout, "probe-session\n");

	const stop = spawnSync(process.execPath, [helper, "stop"], {
		cwd,
		input: '{"stop_hook_active":false}',
		encoding: "utf8",
	});
	assert.equal(stop.status, 0);
	assert.equal(stop.stdout, "{}\n");
	const captures = fs
		.readFileSync(capturePath, "utf8")
		.trim()
		.split("\n")
		.map((line) => JSON.parse(line));
	assert.deepEqual(
		captures.map(({ argv, cwd: invokedFrom }) => ({ argv, cwd: invokedFrom })),
		[
			{ argv: ["status", "--local"], cwd: adoptingRoot },
			{ argv: ["stop-hook", "--agent", "codex"], cwd: adoptingRoot },
		],
	);
	assert.equal(captures[1].input, '{"stop_hook_active":false}');
});

test("plugin build rejects an active skill directory symlink before writing any output", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const manifestPath = path.join(pluginRoot, ".codex-plugin", "plugin.json");
	const safeSkillPath = path.join(pluginRoot, "skills", "stdd-brainstorming", "SKILL.md");
	const manifestBefore = fs.readFileSync(manifestPath);
	const safeSkillBefore = fs.readFileSync(safeSkillPath);
	const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-outside-skill-"));
	const outsideSkill = path.join(outside, "SKILL.md");
	const outsideBefore = Buffer.from("OUTSIDE_SKILL_MUST_NOT_CHANGE\n");
	fs.writeFileSync(outsideSkill, outsideBefore);
	const activeSkillDir = path.join(pluginRoot, "skills", "stdd-start-change");
	fs.rmSync(activeSkillDir, { recursive: true });
	fs.symlinkSync(outside, activeSkillDir, "dir");

	assert.throws(() => buildPlugin(root), /skill.*stdd-start-change.*symlink|symlink.*skill/i);
	assert.deepEqual(fs.readFileSync(outsideSkill), outsideBefore);
	assert.deepEqual(fs.readFileSync(manifestPath), manifestBefore);
	assert.deepEqual(fs.readFileSync(safeSkillPath), safeSkillBefore);
});

test("plugin build rejects manifest path symlinks before writing any output", () => {
	for (const mode of ["manifest-file", "manifest-parent"]) {
		const { root, pluginRoot } = pluginBuildFixture();
		const manifestDir = path.join(pluginRoot, ".codex-plugin");
		const manifestPath = path.join(manifestDir, "plugin.json");
		const safeSkillPath = path.join(pluginRoot, "skills", "stdd-brainstorming", "SKILL.md");
		const safeSkillBefore = fs.readFileSync(safeSkillPath);
		const outside = fs.mkdtempSync(path.join(os.tmpdir(), `stdd-plugin-outside-${mode}-`));
		const outsideManifest = path.join(outside, "plugin.json");
		const outsideBefore = fs.readFileSync(manifestPath);
		fs.writeFileSync(outsideManifest, outsideBefore);
		if (mode === "manifest-file") {
			fs.rmSync(manifestPath);
			fs.symlinkSync(outsideManifest, manifestPath);
		} else {
			fs.rmSync(manifestDir, { recursive: true });
			fs.symlinkSync(outside, manifestDir, "dir");
		}

		assert.throws(() => buildPlugin(root), /codex-plugin|plugin\.json.*symlink|symlink.*manifest/i);
		assert.deepEqual(fs.readFileSync(outsideManifest), outsideBefore, mode);
		assert.deepEqual(fs.readFileSync(safeSkillPath), safeSkillBefore, mode);
	}
});

test("plugin build rejects root, skill-file, hook, and script symlink boundaries", () => {
	for (const mode of ["plugin-root", "skill-file", "hooks", "scripts"]) {
		const { root, pluginRoot } = pluginBuildFixture();
		const manifestPath = path.join(pluginRoot, ".codex-plugin", "plugin.json");
		const safeSkillPath = path.join(pluginRoot, "skills", "stdd-brainstorming", "SKILL.md");
		const manifestBefore = fs.readFileSync(manifestPath);
		const safeSkillBefore = fs.readFileSync(safeSkillPath);
		const outside = fs.mkdtempSync(path.join(os.tmpdir(), `stdd-plugin-outside-${mode}-`));
		const outsideFile = path.join(outside, mode === "skill-file" ? "SKILL.md" : `${mode}.txt`);
		const outsideBefore = Buffer.from(`OUTSIDE_${mode}_MUST_NOT_CHANGE\n`);
		fs.writeFileSync(outsideFile, outsideBefore);

		if (mode === "plugin-root") {
			fs.rmSync(pluginRoot, { recursive: true });
			fs.symlinkSync(outside, pluginRoot, "dir");
		} else if (mode === "skill-file") {
			const skillFile = path.join(pluginRoot, "skills", "stdd-start-change", "SKILL.md");
			fs.rmSync(skillFile);
			fs.symlinkSync(outsideFile, skillFile);
		} else {
			const boundary = path.join(pluginRoot, mode);
			fs.rmSync(boundary, { recursive: true });
			fs.symlinkSync(outside, boundary, "dir");
		}

		assert.throws(() => buildPlugin(root), /symlink.*unsafe|symlink.*plugin publication/i, mode);
		assert.deepEqual(fs.readFileSync(outsideFile), outsideBefore, mode);
		if (mode !== "plugin-root") {
			assert.deepEqual(fs.readFileSync(manifestPath), manifestBefore, mode);
			assert.deepEqual(fs.readFileSync(safeSkillPath), safeSkillBefore, mode);
		}
	}
});

test("plugin build rejects a playbook replaced after validation before publishing output", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const playbooksRoot = path.join(root, "playbooks");
	const playbookPath = path.join(playbooksRoot, "planning.md");
	const parkedPlaybook = path.join(playbooksRoot, "planning.md.parked");
	const manifestPath = path.join(pluginRoot, ".codex-plugin", "plugin.json");
	const skillPath = path.join(pluginRoot, "skills", "stdd-planning", "SKILL.md");
	const manifestBefore = fs.readFileSync(manifestPath);
	const skillBefore = fs.readFileSync(skillPath);
	const originalPlaybook = fs.readFileSync(playbookPath);
	const replacement =
		"---\nname: stdd-planning\ndescription: Attacker replacement\n---\n\nATTACKER_PLAYBOOK\n";
	let swapped = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					readFileSync: (originalRead, originals) =>
						function (candidate, ...args) {
							const observed =
								typeof candidate === "number"
									? fs.readlinkSync(`/proc/self/fd/${candidate}`)
									: String(candidate);
							if (
								!swapped &&
								path.basename(observed) === "planning.md" &&
								originals.realpathSync(path.dirname(observed)) === playbooksRoot
							) {
								swapped = true;
								originals.renameSync(playbookPath, parkedPlaybook);
								fs.writeFileSync(playbookPath, replacement);
							}
							return originalRead.call(this, candidate, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/playbook planning\.md.*changed|changed.*playbook planning\.md/i,
	);
	assert.equal(swapped, true);
	assert.equal(fs.readFileSync(playbookPath, "utf8"), replacement);
	assert.deepEqual(fs.readFileSync(parkedPlaybook), originalPlaybook);
	assert.deepEqual(fs.readFileSync(manifestPath), manifestBefore);
	assert.deepEqual(fs.readFileSync(skillPath), skillBefore);
});

test("plugin build rejects multiply linked playbooks before publishing output", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const playbookPath = path.join(root, "playbooks", "planning.md");
	const secondLink = path.join(root, "playbooks", "planning-linked-copy");
	const manifestPath = path.join(pluginRoot, ".codex-plugin", "plugin.json");
	const skillPath = path.join(pluginRoot, "skills", "stdd-planning", "SKILL.md");
	const manifestBefore = fs.readFileSync(manifestPath);
	const skillBefore = fs.readFileSync(skillPath);
	fs.linkSync(playbookPath, secondLink);

	assert.throws(() => buildPlugin(root), /playbook planning\.md.*single-link/i);
	assert.equal(fs.statSync(playbookPath).nlink, 2);
	assert.deepEqual(fs.readFileSync(secondLink), fs.readFileSync(playbookPath));
	assert.deepEqual(fs.readFileSync(manifestPath), manifestBefore);
	assert.deepEqual(fs.readFileSync(skillPath), skillBefore);
});

test("plugin build confines a skill write when its parent swaps at temp open", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillDir = path.join(pluginRoot, "skills", "stdd-brainstorming");
	const parked = path.join(pluginRoot, "skills", "parked-brainstorming");
	const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-open-swap-"));
	const outsideSkill = path.join(outside, "SKILL.md");
	const outsideBefore = Buffer.from("OUTSIDE_OPEN_SWAP\n");
	fs.writeFileSync(outsideSkill, outsideBefore);
	let swapped = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					openSync: (originalOpen, originals) =>
						function (candidate, ...args) {
							const shown = String(candidate);
							if (
								!swapped &&
								path.basename(shown).startsWith(".SKILL.md-") &&
								originals.realpathSync(path.dirname(shown)) === skillDir
							) {
								swapped = true;
								originals.renameSync(skillDir, parked);
								fs.symlinkSync(outside, skillDir, "dir");
							}
							return originalOpen.call(this, candidate, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/changed|identity|unsafe|symlink/i,
	);
	assert.equal(swapped, true);
	assert.deepEqual(fs.readFileSync(outsideSkill), outsideBefore);
});

test("plugin build never unlinks a replacement swapped onto a failed publication temp", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillDir = path.join(pluginRoot, "skills", "stdd-brainstorming");
	const attackerPark = path.join(
		fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-temp-replacement-")),
		"verified-temp",
	);
	let tempDescriptor = null;
	let replacementPath = null;
	let unsafeUnlink = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					openSync: (originalOpen) =>
						function (candidate, ...args) {
							const descriptor = originalOpen.call(this, candidate, ...args);
							const shown = String(candidate);
							if (
								path.basename(shown).startsWith(".SKILL.md-") &&
								fs.realpathSync(path.dirname(shown)) === skillDir
							) {
								tempDescriptor = descriptor;
							}
							return descriptor;
						},
					fsyncSync: (originalFsync, originals) =>
						function (descriptor, ...args) {
							if (descriptor === tempDescriptor) {
								const heldParent = `/proc/self/fd/${descriptor}`;
								const descriptorTarget = fs.readlinkSync(heldParent);
								const tempPath = descriptorTarget.startsWith("/")
									? descriptorTarget
									: path.resolve(path.dirname(heldParent), descriptorTarget);
								const tempName = path.basename(tempPath);
								originals.renameSync(tempPath, attackerPark);
								replacementPath = path.join(skillDir, tempName);
								fs.writeFileSync(replacementPath, "REPLACEMENT_TEMP_SURVIVES\n");
								throw new Error("injected temp fsync failure");
							}
							return originalFsync.call(this, descriptor, ...args);
						},
					unlinkSync: (originalUnlink) =>
						function (candidate, ...args) {
							if (replacementPath && String(candidate).endsWith(path.basename(replacementPath))) {
								unsafeUnlink = true;
							}
							return originalUnlink.call(this, candidate, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/injected temp fsync failure/i,
	);
	assert.equal(unsafeUnlink, false);
	assert.equal(fs.readFileSync(replacementPath, "utf8"), "REPLACEMENT_TEMP_SURVIVES\n");
});

test("plugin build confines a skill publication when its parent swaps at rename", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillDir = path.join(pluginRoot, "skills", "stdd-brainstorming");
	const parked = path.join(pluginRoot, "skills", "parked-brainstorming");
	const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-rename-swap-"));
	const outsideSkill = path.join(outside, "SKILL.md");
	const outsideBefore = Buffer.from("OUTSIDE_RENAME_SWAP\n");
	fs.writeFileSync(outsideSkill, outsideBefore);
	let swapped = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					renameSync: (originalRename, originals) =>
						function (source, target, ...args) {
							const sourcePath = String(source);
							if (
								!swapped &&
								path.basename(sourcePath).startsWith(".SKILL.md-") &&
								path.basename(String(target)) === "SKILL.md" &&
								originals.realpathSync(path.dirname(sourcePath)) === skillDir
							) {
								swapped = true;
								const outsideTemp = path.join(outside, path.basename(sourcePath));
								fs.writeFileSync(outsideTemp, "ATTACKER_TEMP\n");
								originalRename.call(this, skillDir, parked);
								fs.symlinkSync(outside, skillDir, "dir");
							}
							return originalRename.call(this, source, target, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/changed|identity|unsafe|symlink/i,
	);
	assert.equal(swapped, true);
	assert.deepEqual(fs.readFileSync(outsideSkill), outsideBefore);
});

test("plugin build atomically replaces a final skill symlink swap without writing through it", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillDir = path.join(pluginRoot, "skills", "stdd-brainstorming");
	const skillPath = path.join(skillDir, "SKILL.md");
	const outside = path.join(
		fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-final-swap-")),
		"outside.md",
	);
	const outsideBefore = Buffer.from("OUTSIDE_FINAL_SWAP\n");
	fs.writeFileSync(outside, outsideBefore);
	let swapped = false;

	withPatchedFs(
		{
			renameSync: (originalRename, originals) =>
				function (source, target, ...args) {
					const sourcePath = String(source);
					if (
						!swapped &&
						path.basename(sourcePath).startsWith(".SKILL.md-") &&
						path.basename(String(target)) === "SKILL.md" &&
						originals.realpathSync(path.dirname(sourcePath)) === skillDir
					) {
						swapped = true;
						fs.rmSync(skillPath);
						fs.symlinkSync(outside, skillPath);
					}
					return originalRename.call(this, source, target, ...args);
				},
		},
		() => buildPlugin(root),
	);
	assert.equal(swapped, true);
	assert.deepEqual(fs.readFileSync(outside), outsideBefore);
	assert.equal(fs.lstatSync(skillPath).isSymbolicLink(), false);
	assert.match(fs.readFileSync(skillPath, "utf8"), /generated by stdd plugin build v9\.9\.9/);
});

test("plugin build confines active skill mkdir when the skills parent swaps", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillsRoot = path.join(pluginRoot, "skills");
	const activeName = "stdd-start-change";
	const activeDir = path.join(skillsRoot, activeName);
	const parked = path.join(pluginRoot, "parked-skills");
	const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-mkdir-swap-"));
	fs.rmSync(activeDir, { recursive: true });
	let swapped = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					mkdirSync: (originalMkdir, originals) =>
						function (candidate, ...args) {
							const shown = String(candidate);
							if (
								!swapped &&
								path.basename(shown) === activeName &&
								originals.realpathSync(path.dirname(shown)) === skillsRoot
							) {
								swapped = true;
								originals.renameSync(skillsRoot, parked);
								fs.symlinkSync(outside, skillsRoot, "dir");
							}
							return originalMkdir.call(this, candidate, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/changed|identity|unsafe|symlink/i,
	);
	assert.equal(swapped, true);
	assert.equal(fs.existsSync(path.join(outside, activeName)), false);
});

test("plugin build confines stale skill settlement when the skills parent swaps", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillsRoot = path.join(pluginRoot, "skills");
	const staleName = "stdd-stale";
	const staleDir = path.join(skillsRoot, staleName);
	const parked = path.join(pluginRoot, "parked-skills");
	const outside = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-stale-swap-"));
	const outsideStale = path.join(outside, staleName);
	fs.mkdirSync(staleDir);
	fs.writeFileSync(path.join(staleDir, "SKILL.md"), "STALE_INSIDE\n");
	fs.mkdirSync(outsideStale);
	fs.writeFileSync(path.join(outsideStale, "SKILL.md"), "OUTSIDE_STALE\n");
	let swapped = false;
	const swap = (originals) => {
		swapped = true;
		originals.renameSync(skillsRoot, parked);
		fs.symlinkSync(outside, skillsRoot, "dir");
	};

	assert.throws(
		() =>
			withPatchedFs(
				{
					rmSync: (originalRm, originals) =>
						function (candidate, ...args) {
							if (!swapped && path.basename(String(candidate)) === staleName) swap(originals);
							return originalRm.call(this, candidate, ...args);
						},
					renameSync: (originalRename, originals) =>
						function (source, target, ...args) {
							if (!swapped && path.basename(String(source)) === staleName) swap(originals);
							return originalRename.call(this, source, target, ...args);
						},
				},
				() => buildPlugin(root),
			),
		/changed|identity|unsafe|symlink/i,
	);
	assert.equal(swapped, true);
	assert.equal(fs.readFileSync(path.join(outsideStale, "SKILL.md"), "utf8"), "OUTSIDE_STALE\n");
});

test("plugin build never recursively removes quarantined stale trees", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const skillsRoot = path.join(pluginRoot, "skills");
	const staleName = "stdd-stale";
	fs.mkdirSync(path.join(skillsRoot, staleName));
	fs.writeFileSync(path.join(skillsRoot, staleName, "SKILL.md"), "STALE_INSIDE\n");
	const quarantine = path.join(pluginRoot, ".stdd-plugin-quarantine");
	fs.mkdirSync(quarantine, { mode: 0o700 });
	const replacement = path.join(quarantine, "preexisting-replacement");
	fs.mkdirSync(replacement);
	fs.writeFileSync(path.join(replacement, "marker"), "REPLACEMENT_SURVIVES\n");
	let destructiveRm = false;

	withPatchedFs(
		{
			rmSync: (originalRm) =>
				function (candidate, ...args) {
					if (String(candidate).includes(".stdd-plugin-quarantine")) destructiveRm = true;
					return originalRm.call(this, candidate, ...args);
				},
		},
		() => buildPlugin(root),
	);
	assert.equal(destructiveRm, false);
	assert.equal(fs.readFileSync(path.join(replacement, "marker"), "utf8"), "REPLACEMENT_SURVIVES\n");
	const retired = fs
		.readdirSync(quarantine)
		.find((name) => name.startsWith(`${staleName}-`) && name.endsWith(".retired"));
	assert.equal(fs.readFileSync(path.join(quarantine, retired, "SKILL.md"), "utf8"), "STALE_INSIDE\n");
});

test("plugin build never deletes a replacement swapped onto a quarantine final name", () => {
	const { root, pluginRoot } = pluginBuildFixture();
	const staleName = "stdd-stale";
	const staleDir = path.join(pluginRoot, "skills", staleName);
	const quarantine = path.join(pluginRoot, ".stdd-plugin-quarantine");
	fs.mkdirSync(staleDir);
	fs.writeFileSync(path.join(staleDir, "SKILL.md"), "STALE_INSIDE\n");
	const attackerPark = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-plugin-quarantine-final-swap-"));
	let replacementMarker = null;
	let swapped = false;

	assert.throws(
		() =>
			withPatchedFs(
				{
					renameSync: (originalRename) =>
						function (source, target, ...args) {
							const targetName = path.basename(String(target));
							const result = originalRename.call(this, source, target, ...args);
							if (
								!swapped &&
								path.basename(String(source)) === staleName &&
								targetName.endsWith(".retired")
							) {
								swapped = true;
								originalRename.call(this, target, path.join(attackerPark, targetName));
								fs.mkdirSync(target);
								fs.writeFileSync(path.join(String(target), "marker"), "REPLACEMENT_SURVIVES\n");
								replacementMarker = path.join(quarantine, targetName, "marker");
							}
							return result;
						},
				},
				() => buildPlugin(root),
			),
		/changed|identity|quarantine/i,
	);
	assert.equal(swapped, true);
	assert.equal(fs.readFileSync(replacementMarker, "utf8"), "REPLACEMENT_SURVIVES\n");
});

test("plugin rebuild removes skills whose playbooks were deleted or renamed", () => {
	const { root } = pluginBuildFixture();
	fs.mkdirSync(path.join(root, "plugins", "stdd", "skills", "stdd-stale"), { recursive: true });
	fs.writeFileSync(path.join(root, "plugins", "stdd", "skills", "stdd-stale", "SKILL.md"), "stale");

	buildPlugin(root);

	assert.ok(!fs.existsSync(path.join(root, "plugins", "stdd", "skills", "stdd-stale")));
	assert.ok(fs.existsSync(path.join(root, "plugins", "stdd", "skills", "stdd-start-change")));
	const quarantine = path.join(root, "plugins", "stdd", ".stdd-plugin-quarantine");
	const retired = fs
		.readdirSync(quarantine)
		.find((name) => name.startsWith("stdd-stale-") && name.endsWith(".retired"));
	assert.equal(fs.readFileSync(path.join(quarantine, retired, "SKILL.md"), "utf8"), "stale");
	assert.match(fs.readFileSync(path.join(quarantine, "README.txt"), "utf8"), /inspect and remove/i);
	const manifestPath = path.join(root, "plugins", "stdd", ".codex-plugin", "plugin.json");
	const malformed = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
	malformed.interface.defaultPrompt = "not-an-array";
	fs.writeFileSync(manifestPath, JSON.stringify(malformed));
	assert.throws(() => buildPlugin(root), /defaultPrompt/);
});
