#!/usr/bin/env node
import { execFileSync, spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	DEFAULT_CONFIG,
	extractDocPaths,
	findEvidenceLines,
	globToRegExp,
	mergeConfig,
	nearMissEvidenceLines,
	parseFrontmatter,
	parseLedger,
	redGenuine,
	scanTemporal,
	sentinelSuggestion,
	sha256,
	temporalMatchers,
	workflowValidatesStaleBody,
} from "./lib.mjs";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSION = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "package.json"), "utf8")).version;
const KNOWN_TOOLS = ["claude", "codex"];
const KNOWN_CI = ["github"];
const STAMP = `generated by stdd v${VERSION} — do not edit, re-run \`stdd init\``;

function fail(message) {
	console.error(`stdd: ${message}`);
	process.exit(1);
}

function listTrackedFiles(dir) {
	try {
		const out = execFileSync("git", ["-C", dir, "ls-files", "-z"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		});
		const files = out.split("\0").filter(Boolean);
		if (files.length > 0) return files;
	} catch {
		// not a git repo — fall through to a filesystem walk
	}
	const files = [];
	const walk = (rel) => {
		for (const entry of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
			if (entry.name === ".git" || entry.name === "node_modules") continue;
			const relPath = rel ? `${rel}/${entry.name}` : entry.name;
			if (entry.isDirectory()) walk(relPath);
			else files.push(relPath);
		}
	};
	walk("");
	return files;
}

function loadPlaybooks() {
	const dir = path.join(PKG_ROOT, "playbooks");
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md"))
		.map((f) => {
			const source = fs.readFileSync(path.join(dir, f), "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`playbook ${f} is missing required frontmatter (name, description)`);
			}
			return { file: f, source, meta, body };
		});
}

function loadConfig(targetDir) {
	const configPath = path.join(targetDir, ".stdd", "config.json");
	if (!fs.existsSync(configPath)) return DEFAULT_CONFIG;
	let parsed;
	try {
		parsed = JSON.parse(fs.readFileSync(configPath, "utf8"));
	} catch (err) {
		fail(`.stdd/config.json is not valid JSON: ${err.message}`);
	}
	try {
		return mergeConfig(parsed);
	} catch (err) {
		fail(`.stdd/config.json: ${err.message}`);
	}
}

function init(targetDir, tools, ci, hooks) {
	const stddDir = path.join(targetDir, ".stdd");
	fs.mkdirSync(path.join(stddDir, "playbooks"), { recursive: true });
	// Every generated file is recorded here (repo-relative path → content
	// hash) and written to .stdd/manifest.json, so check/doctor can detect
	// hand edits, deletions, and stale copies. User-owned files (config.json)
	// are deliberately not recorded.
	const generated = {};
	const writeGenerated = (relPath, content) => {
		fs.writeFileSync(path.join(targetDir, ...relPath.split("/")), content);
		generated[relPath] = sha256(content);
	};

	writeGenerated(".stdd/method.md", fs.readFileSync(path.join(PKG_ROOT, "method", "README.md"), "utf8"));
	const playbooks = loadPlaybooks();
	for (const pb of playbooks) {
		writeGenerated(`.stdd/playbooks/${pb.file}`, pb.source);
	}
	const configPath = path.join(stddDir, "config.json");
	if (!fs.existsSync(configPath)) {
		fs.writeFileSync(configPath, `${JSON.stringify(DEFAULT_CONFIG, null, "\t")}\n`);
	}
	console.log(`Installed .stdd/ (method, ${playbooks.length} playbooks, config)`);

	if (tools.includes("claude")) {
		for (const pb of playbooks) {
			const skillDir = path.join(targetDir, ".claude", "skills", pb.meta.name);
			fs.mkdirSync(skillDir, { recursive: true });
			const skill =
				`---\nname: ${pb.meta.name}\ndescription: ${pb.meta.description}\n---\n\n` +
				`<!-- ${STAMP} -->\n\n${pb.body}`;
			writeGenerated(`.claude/skills/${pb.meta.name}/SKILL.md`, skill);
		}
		console.log(`Installed ${playbooks.length} Claude Code skills under .claude/skills/`);
	}

	if (tools.includes("codex")) {
		const lines = [
			`<!-- ${STAMP} -->`,
			"",
			"## STDD",
			"",
			"This repository follows the STDD method: read `.stdd/method.md` before",
			"any behavior change and follow its loop (docs edit is the spec → failing",
			"test → implement → verify → PR evidence).",
			"",
			"Do not search the project log (dated entries marked",
			"`authority: non-canonical`, e.g. `docs/project/`) unless the user",
			"explicitly asks for historical rationale or deferred work — it records",
			"past decisions and future intentions, never the present.",
			"",
			"Playbooks in `.stdd/playbooks/`:",
			"",
			...playbooks.map((pb) => `- \`${pb.file}\` — ${pb.meta.when ?? pb.meta.description}`),
		];
		const snippet = `${lines.join("\n")}\n`;
		writeGenerated(".stdd/AGENTS-snippet.md", snippet);
		console.log("\nAdd this to your AGENTS.md (also saved to .stdd/AGENTS-snippet.md):\n");
		console.log(snippet);
	}

	if (ci.includes("github")) {
		fs.mkdirSync(path.join(targetDir, ".github", "workflows"), { recursive: true });
		const workflow = fs
			.readFileSync(path.join(PKG_ROOT, "templates", "github-stdd.yml"), "utf8")
			.replace("__STAMP__", STAMP);
		writeGenerated(".github/workflows/stdd.yml", workflow);
		console.log("Installed .github/workflows/stdd.yml (validates the live PR body)");
	}

	if (hooks) {
		// One fast offline command only — network calls in hooks produce
		// false positives that train --no-verify. User-owned after
		// generation (like config.json): never manifested, never overwritten.
		const hookPath = path.join(stddDir, "hooks", "pre-push");
		if (fs.existsSync(hookPath)) {
			console.log(".stdd/hooks/pre-push already exists — left untouched (user-owned)");
		} else {
			fs.mkdirSync(path.join(stddDir, "hooks"), { recursive: true });
			fs.writeFileSync(
				hookPath,
				"#!/bin/sh\n# user-owned after generation — append your own steps freely\n# --no: never install from the network — a hook must be fast and offline\nnpx --no stdd check . || exit 1\n",
				{ mode: 0o755 },
			);
			console.log(
				"Installed .stdd/hooks/pre-push (runs stdd check — fast, offline). Wire it up with ONE of:\n" +
					"  git config core.hooksPath .stdd/hooks   # note: this disables hooks in .git/hooks\n" +
					"  …or call `stdd check` from your existing husky/lefthook pre-push",
			);
		}
	}

	// The ledger is a per-checkout working artifact — never committed. The
	// ignore rule is user-owned once written, so it is not manifested.
	const gitignorePath = path.join(targetDir, ".gitignore");
	const gitignore = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, "utf8") : "";
	if (!gitignore.split("\n").includes(".stdd/ledger.jsonl")) {
		const sep = gitignore === "" || gitignore.endsWith("\n") ? "" : "\n";
		fs.writeFileSync(gitignorePath, `${gitignore}${sep}.stdd/ledger.jsonl\n`);
		console.log("Added .stdd/ledger.jsonl to .gitignore (the ledger is never committed)");
	}

	const manifest = { generatedBy: "stdd", version: VERSION, files: generated };
	fs.writeFileSync(path.join(stddDir, "manifest.json"), `${JSON.stringify(manifest, null, "\t")}\n`);
}

/**
 * Shared repository scan for `check` and `doctor`: committed working
 * artifacts, canonical docs and their temporal-narrative hits, and stale
 * generated files (a stale stamp means the CLI was upgraded without
 * re-running `stdd init`).
 */
function scanRepo(targetDir, config) {
	const files = listTrackedFiles(targetDir);

	const forbidden = config.forbiddenArtifacts.map(globToRegExp);
	const artifacts = files.filter((file) => forbidden.some((re) => re.test(file)));

	const canonical = config.canonicalDocs.map(globToRegExp);
	const canonicalFiles = files.filter((file) => canonical.some((re) => re.test(file)));
	const matchers = temporalMatchers(config.temporalPhrases);
	const temporal = [];
	for (const file of canonicalFiles) {
		const lines = fs.readFileSync(path.join(targetDir, file), "utf8").split("\n");
		for (const hit of scanTemporal(lines, matchers)) temporal.push({ file, ...hit });
	}

	return { artifacts, canonicalFiles, temporal, stale: scanGeneratedDrift(targetDir) };
}

/**
 * Generated-file drift, as `{ file, message }` findings. With a manifest
 * (written by `stdd init`), every generated file is verified by content
 * hash. Without one (repo initialized by an older stdd), fall back to the
 * version stamp inside Claude skills.
 */
function scanGeneratedDrift(targetDir) {
	const stale = [];
	const manifestPath = path.join(targetDir, ".stdd", "manifest.json");
	if (fs.existsSync(manifestPath)) {
		let manifest;
		try {
			manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
		} catch {
			return [{ file: ".stdd/manifest.json", message: "is not valid JSON — re-run stdd init" }];
		}
		if (manifest.version !== VERSION) {
			stale.push({
				file: ".stdd/manifest.json",
				message: `written by stdd v${manifest.version}, CLI is v${VERSION} — re-run stdd init`,
			});
		}
		for (const [file, hash] of Object.entries(manifest.files ?? {})) {
			const filePath = path.join(targetDir, ...file.split("/"));
			if (!fs.existsSync(filePath)) {
				stale.push({ file, message: "listed in .stdd/manifest.json but missing — re-run stdd init" });
			} else if (sha256(fs.readFileSync(filePath, "utf8")) !== hash) {
				stale.push({ file, message: "edited by hand or stale — re-run stdd init" });
			}
		}
		return stale;
	}

	const stampRe = /generated by stdd v([0-9][^\s]*) —/;
	const skillsDir = path.join(targetDir, ".claude", "skills");
	if (fs.existsSync(skillsDir)) {
		for (const name of fs.readdirSync(skillsDir)) {
			const skillPath = path.join(skillsDir, name, "SKILL.md");
			if (!fs.existsSync(skillPath)) continue;
			const m = stampRe.exec(fs.readFileSync(skillPath, "utf8"));
			if (m && m[1] !== VERSION) {
				stale.push({
					file: `.claude/skills/${name}/SKILL.md`,
					message: `generated by stdd v${m[1]}, CLI is v${VERSION} — re-run stdd init`,
				});
			}
		}
	}
	return stale;
}

function check(targetDir) {
	const config = loadConfig(targetDir);
	const { artifacts, temporal, stale } = scanRepo(targetDir, config);
	const violations = [
		...artifacts.map((file) => `${file}: committed working artifact (forbiddenArtifacts)`),
		...temporal.map(
			(hit) => `${hit.file}:${hit.line}: temporal narrative in canonical doc ("${hit.phrase}")`,
		),
		...stale.map((s) => `${s.file}: ${s.message}`),
	];

	if (violations.length > 0) {
		console.error(`stdd check: ${violations.length} violation(s)\n`);
		for (const v of violations) console.error(`  ${v}`);
		process.exit(1);
	}
	console.log("stdd check: OK");
}

/**
 * Config-declared worktree readiness: report each missing required path
 * with its repo-authored fix hint. Purely declarative — existence only,
 * nothing is executed or installed. Returns true when everything passes.
 */
function reportReadiness(targetDir, config, report) {
	const required = config.readiness.required;
	if (required.length === 0) return null;
	const missing = required.filter(
		(entry) => !fs.existsSync(path.join(targetDir, ...entry.path.split("/"))),
	);
	for (const entry of missing) {
		report(false, `${entry.path} missing${entry.hint ? ` — ${entry.hint}` : ""}`);
	}
	if (missing.length === 0) {
		report(true, `worktree ready (${required.length}/${required.length} present)`);
	}
	return missing.length === 0;
}

function doctor(targetDir, readinessOnly = false) {
	const count = (n, singular, plural) => `${n} ${n === 1 ? singular : plural}`;
	let failed = false;
	const report = (ok, message) => {
		console.log(`${ok ? "✓" : "✗"} ${message}`);
		if (!ok) failed = true;
	};

	if (readinessOnly) {
		if (reportReadiness(targetDir, loadConfig(targetDir), report) === null) {
			console.log("no readiness contract declared (readiness.required in .stdd/config.json)");
		}
		if (failed) process.exit(1);
		return;
	}

	const installed = fs.existsSync(path.join(targetDir, ".stdd", "method.md"));
	report(installed, installed ? ".stdd/ installed" : ".stdd/ is not installed — run stdd init");

	const config = loadConfig(targetDir);
	reportReadiness(targetDir, config, report);
	const { artifacts, canonicalFiles, temporal, stale } = scanRepo(targetDir, config);

	report(
		canonicalFiles.length > 0,
		canonicalFiles.length > 0
			? `canonical docs present (${count(canonicalFiles.length, "file", "files")})`
			: "no canonical docs found — create docs/domain/ or docs/product/, or adjust canonicalDocs",
	);

	report(
		artifacts.length === 0,
		artifacts.length === 0
			? "no committed working artifacts"
			: `${count(artifacts.length, "committed working artifact", "committed working artifacts")} may mislead coding agents`,
	);

	const temporalFiles = new Set(temporal.map((hit) => hit.file)).size;
	report(
		temporalFiles === 0,
		temporalFiles === 0
			? "canonical docs describe the present (no temporal narrative)"
			: `${count(temporalFiles, "canonical doc contains", "canonical docs contain")} temporal narrative`,
	);

	report(
		stale.length === 0,
		stale.length === 0
			? `generated files match stdd v${VERSION}`
			: `${count(stale.length, "generated file is", "generated files are")} stale — re-run stdd init`,
	);

	// informational only — a missing hook is a choice, never a failure
	const hookInstalled = fs.existsSync(path.join(targetDir, ".stdd", "hooks", "pre-push"));
	console.log(
		hookInstalled
			? "· pre-push hook installed (.stdd/hooks/pre-push) — wire via git config core.hooksPath .stdd/hooks"
			: "· no pre-push hook installed — optional: stdd init --hooks",
	);

	const agentsPath = path.join(targetDir, "AGENTS.md");
	if (fs.existsSync(agentsPath)) {
		const hasSection = /^## STDD$/m.test(fs.readFileSync(agentsPath, "utf8"));
		report(
			hasSection,
			hasSection
				? "AGENTS.md carries the STDD section"
				: "AGENTS.md has no STDD section — paste .stdd/AGENTS-snippet.md",
		);
	}

	const workflowsDir = path.join(targetDir, ".github", "workflows");
	if (fs.existsSync(workflowsDir)) {
		for (const file of fs.readdirSync(workflowsDir).filter((f) => /\.ya?ml$/.test(f))) {
			if (workflowValidatesStaleBody(fs.readFileSync(path.join(workflowsDir, file), "utf8"))) {
				report(
					false,
					`.github/workflows/${file} validates the frozen event payload body — ` +
						"body edits will not be re-checked; see stdd init --ci github",
				);
			}
		}
	}

	for (const rel of [
		"pull_request_template.md",
		".github/pull_request_template.md",
		"docs/pull_request_template.md",
	]) {
		const tplPath = path.join(targetDir, ...rel.split("/"));
		if (!fs.existsSync(tplPath)) continue;
		if (findEvidenceLines(fs.readFileSync(tplPath, "utf8")).length > 0) {
			report(
				false,
				`${rel} carries an unquoted evidence label — placeholder residue would pass ` +
					'the gate on every PR; quote template instructions ("> Docs …")',
			);
		}
	}

	if (failed) process.exit(1);
}

/** Run git in the working directory, returning trimmed stdout; throws on failure. */
function git(...args) {
	return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}

/**
 * With --pr: fetch the live PR (body, base, head) from the forge, so the
 * validation matches what CI will see — never a diverged local checkout.
 * Returns `{ body, baseRef, headRef, number }`.
 */
function resolveLivePr(pr) {
	const args = [
		"pr",
		"view",
		...(pr === "." ? [] : [pr]),
		"--json",
		"body,baseRefName,headRefOid,number",
	];
	let info;
	try {
		info = JSON.parse(execFileSync("gh", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }));
	} catch (err) {
		if (err.code === "ENOENT") fail("--pr needs the GitHub CLI (gh) on PATH");
		fail(`gh pr view failed: ${err.stderr?.toString().trim().split("\n")[0] || err.message}`);
	}
	const baseRef = `origin/${info.baseRefName}`;
	try {
		git("fetch", "-q", "origin", info.baseRefName);
	} catch (err) {
		fail(
			`could not fetch origin/${info.baseRefName}: ${err.stderr?.toString().trim().split("\n")[0] || err.message}`,
		);
	}
	let headRef = "HEAD";
	if (git("rev-parse", "HEAD") !== info.headRefOid) {
		try {
			git("cat-file", "-e", `${info.headRefOid}^{commit}`);
		} catch {
			try {
				git("fetch", "-q", "origin", `pull/${info.number}/head`);
				git("cat-file", "-e", `${info.headRefOid}^{commit}`);
			} catch {
				fail(
					`local HEAD differs from PR head ${info.headRefOid.slice(0, 7)} and it could not ` +
						"be fetched — push or check out the PR branch",
				);
			}
		}
		headRef = info.headRefOid;
	}
	return { body: info.body, baseRef, headRef, number: info.number };
}

// --- the session ledger (see method: "The session ledger and stdd status") ---

const LEDGER_REL = ".stdd/ledger.jsonl";

/**
 * The ledger and config anchor to the repository, never the shell's cwd —
 * a recorder run from a subdirectory must not create a nested `.stdd/`.
 * Resolution: the git toplevel when it holds `.stdd/` (or when none exists
 * yet), otherwise the nearest ancestor holding `.stdd/`. Outside a git
 * repo the cwd is returned unchanged — recorders require git anyway.
 */
function resolveRepoDir(cwd) {
	let top;
	try {
		top = execFileSync("git", ["-C", cwd, "rev-parse", "--show-toplevel"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch {
		return cwd;
	}
	if (fs.existsSync(path.join(top, ".stdd"))) return top;
	let dir = path.resolve(cwd);
	while (dir !== top && path.dirname(dir) !== dir) {
		if (fs.existsSync(path.join(dir, ".stdd"))) return dir;
		dir = path.dirname(dir);
	}
	return top;
}
const DOCS_DECISIONS = ["updated-first", "checked", "not-applicable"];
const LABEL_TO_DECISION = {
	"Docs updated first": "updated-first",
	"Docs checked, no change needed": "checked",
	"Docs not applicable": "not-applicable",
};
const EXCERPT_LIMIT = 2000;

/** Current branch name, or null outside a git repo (soft — callers decide). */
function currentBranch(cwd) {
	try {
		return execFileSync("git", ["-C", cwd, "rev-parse", "--abbrev-ref", "HEAD"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch {
		return null;
	}
}

function requireBranch(cwd) {
	const branch = currentBranch(cwd);
	if (!branch) fail("the ledger needs a git repository with at least one commit");
	return branch;
}

function appendLedger(cwd, event) {
	const branch = requireBranch(cwd);
	fs.mkdirSync(path.join(cwd, ".stdd"), { recursive: true });
	fs.appendFileSync(
		path.join(cwd, LEDGER_REL),
		`${JSON.stringify({ ts: new Date().toISOString(), branch, ...event })}\n`,
	);
}

/** Current branch's ledger events, in append order. [] without a ledger. */
function loadLedger(cwd, branch) {
	const ledgerPath = path.join(cwd, LEDGER_REL);
	if (!fs.existsSync(ledgerPath)) return [];
	return parseLedger(fs.readFileSync(ledgerPath, "utf8")).filter((e) => e.branch === branch);
}

/** `stdd docs <decision> [paths…] [--reason <why>]` — record the docs decision. */
function recordDocs(cwd, decision, paths, reason) {
	if (!DOCS_DECISIONS.includes(decision)) {
		fail(`unknown docs decision "${decision ?? ""}" — use ${DOCS_DECISIONS.join(", ")}`);
	}
	if (decision === "not-applicable") {
		if (paths.length > 0) fail("not-applicable takes no paths — it names a reason instead");
		if (!reason) fail("not-applicable needs --reason <why implementation-only>");
	} else if (paths.length === 0) {
		fail(`${decision} needs at least one docs path`);
	}
	if (decision === "checked" && !reason) {
		fail("checked needs --reason <why no change is needed>");
	}
	appendLedger(cwd, { event: "docs", decision, paths, ...(reason ? { reason } : {}) });
	console.log(`stdd docs: recorded ${decision}${paths.length ? ` (${paths.join(", ")})` : ""}`);
}

/**
 * `stdd red|verify -- <cmd>` — run the command, record {cmd, exit, excerpt}
 * verbatim, pass the exit code through. Output flows to the caller unchanged.
 */
function recordRun(cwd, kind, argv) {
	const config = loadConfig(cwd);
	const result = spawnSync(argv[0], argv.slice(1), { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
	let exit = result.status ?? 1;
	let output = `${result.stdout ?? ""}${result.stderr ?? ""}`;
	if (result.error) {
		exit = 127;
		output += `${result.error.message}\n`;
	}
	if (result.stdout) process.stdout.write(result.stdout);
	if (result.stderr) process.stderr.write(result.stderr);
	if (result.error) console.error(`stdd ${kind}: ${result.error.message}`);

	const event = { event: kind, cmd: argv.join(" "), exit, excerpt: output.slice(-EXCERPT_LIMIT) };
	if (kind === "red") {
		event.genuine = redGenuine(exit, output, config.redPattern ?? null);
		if (exit === 0) {
			console.error('stdd red: the command exited 0 — that is green, not red (recorded genuine: "no")');
		} else if (event.genuine === "unknown") {
			console.error(
				'stdd red: no redPattern in .stdd/config.json — cannot assert genuine-red (recorded genuine: "unknown")',
			);
		} else if (event.genuine === "no") {
			console.error(
				'stdd red: output does not match redPattern — this looks like an environment error, not a genuine red (recorded genuine: "no")',
			);
		}
	}
	appendLedger(cwd, event);
	process.exit(exit);
}

/**
 * Content hashes of every dirty (staged, unstaged, untracked) path.
 * Deleted paths and untracked directories hash to null — equality of
 * nulls still distinguishes inherited state from a slice's own edits.
 */
function dirtySnapshot(cwd) {
	const out = execFileSync("git", ["-C", cwd, "status", "--porcelain"], {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	});
	const dirty = {};
	for (const line of out.split("\n").filter(Boolean)) {
		let p = line.slice(3);
		if (p.includes(" -> ")) p = p.split(" -> ")[1];
		if (p.startsWith('"') && p.endsWith('"')) p = JSON.parse(p);
		const abs = path.join(cwd, ...p.split("/"));
		dirty[p] =
			!p.endsWith("/") && fs.existsSync(abs) && fs.statSync(abs).isFile()
				? sha256(fs.readFileSync(abs, "utf8"))
				: null;
	}
	return dirty;
}

/**
 * `stdd slice new` — declare a delegated slice's scope and snapshot the
 * checkout baseline (head + dirty-file hashes) into a ledger scope event.
 */
function sliceNew(cwd, frozenPaths, allowedPaths) {
	if (frozenPaths.length === 0 && allowedPaths.length === 0) {
		fail("slice new needs a scope — pass --frozen <globs> and/or --allowed <globs>");
	}
	requireBranch(cwd);
	const head = execFileSync("git", ["-C", cwd, "rev-parse", "HEAD"], {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	}).trim();
	appendLedger(cwd, {
		event: "scope",
		frozenPaths,
		allowedPaths,
		baseline: { head, dirty: dirtySnapshot(cwd) },
	});
	console.log(
		`stdd slice: scope declared (frozen: ${frozenPaths.join(", ") || "—"}; ` +
			`allowed: ${allowedPaths.join(", ") || "—"}) — baseline at ${head.slice(0, 7)}`,
	);
}

/**
 * `stdd scope` — postflight against the slice baseline, not a ref. Only
 * session-introduced changes count; inherited dirt (already modified at
 * baseline, byte-identical now) is reported separately, never blamed.
 */
function scopeCheck(cwd) {
	const branch = requireBranch(cwd);
	const scope = loadLedger(cwd, branch)
		.filter((e) => e.event === "scope")
		.at(-1);
	if (!scope) {
		fail("no slice declared for this branch — run `stdd slice new --frozen/--allowed` first");
	}
	let committed;
	try {
		committed = execFileSync("git", ["-C", cwd, "diff", "--name-only", scope.baseline.head, "HEAD"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		})
			.split("\n")
			.filter(Boolean);
	} catch {
		fail(`baseline commit ${scope.baseline.head.slice(0, 7)} is gone — cannot diff the slice`);
	}
	const introduced = new Set(committed);
	const inherited = [];
	for (const [p, hash] of Object.entries(dirtySnapshot(cwd))) {
		if (p in scope.baseline.dirty && scope.baseline.dirty[p] === hash) inherited.push(p);
		else introduced.add(p);
	}
	// stdd's own bookkeeping (the ledger grows during the slice by design;
	// porcelain may report the whole untracked .stdd/ dir) is never in scope
	for (const p of introduced) {
		if (p === ".stdd/" || p.startsWith(".stdd/")) introduced.delete(p);
	}
	const frozen = scope.frozenPaths.map(globToRegExp);
	const allowed = scope.allowedPaths.map(globToRegExp);
	const violations = [];
	for (const p of introduced) {
		if (frozen.some((re) => re.test(p))) {
			violations.push(`${p}: frozen path modified by this slice`);
		} else if (allowed.length > 0 && !allowed.some((re) => re.test(p))) {
			violations.push(`${p}: outside the allowed paths`);
		}
	}
	for (const p of inherited) {
		console.log(`inherited dirt (present at baseline, not introduced by this slice): ${p}`);
	}
	if (violations.length > 0) {
		console.error(`stdd scope: ${violations.length} violation(s)\n`);
		for (const v of violations) console.error(`  ${v}`);
		process.exit(1);
	}
	console.log(`stdd scope: OK (${introduced.size} introduced change(s), all in scope)`);
}

/**
 * The branch's PR as `stdd status` reports it. Degrades, never errors:
 * no gh on PATH or an unexpected gh failure → state "unknown".
 */
function statusPr(cwd) {
	let raw;
	try {
		raw = execFileSync("gh", ["pr", "view", "--json", "number,url,statusCheckRollup"], {
			cwd,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (err) {
		if (err.code === "ENOENT") return { state: "unknown", reason: "gh unavailable" };
		const stderr = err.stderr?.toString() ?? "";
		if (/no pull requests found/i.test(stderr)) return { state: "none" };
		return { state: "unknown", reason: stderr.trim().split("\n")[0] || "gh failed" };
	}
	let info;
	try {
		info = JSON.parse(raw);
	} catch {
		return { state: "unknown", reason: "gh returned unparseable output" };
	}
	const checks = { success: 0, failure: 0, pending: 0 };
	for (const check of info.statusCheckRollup ?? []) {
		const conclusion = (check.conclusion ?? "").toUpperCase();
		if (conclusion === "SUCCESS" || conclusion === "NEUTRAL" || conclusion === "SKIPPED") {
			checks.success++;
		} else if (conclusion === "") {
			checks.pending++;
		} else {
			checks.failure++;
		}
	}
	return { state: "open", number: info.number, url: info.url, checks };
}

/**
 * `stdd status` — the next-step oracle. Inputs in order of trust: git (diff
 * against the configured baseRef, dirty state), the ledger, then the forge.
 */
function status(cwd, asJson) {
	const config = loadConfig(cwd);
	const branch = requireBranch(cwd);
	const events = loadLedger(cwd, branch);

	// git: changed files = committed diff vs baseRef + dirty working tree
	let changed = null;
	if (config.baseRef) {
		try {
			const diff = execFileSync("git", ["-C", cwd, "diff", "--name-only", `${config.baseRef}...HEAD`], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			});
			const dirty = execFileSync("git", ["-C", cwd, "status", "--porcelain"], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			});
			changed = [
				...new Set([
					...diff.split("\n").filter(Boolean),
					...dirty
						.split("\n")
						.filter(Boolean)
						.map((line) => line.slice(3).trim()),
				]),
			];
		} catch {
			changed = null; // unresolvable baseRef — report unknown, never error
		}
	}
	const canonical = config.canonicalDocs.map(globToRegExp);
	const docsChanged = (changed ?? []).filter((f) => canonical.some((re) => re.test(f)));
	const nonDocChanged = (changed ?? []).filter((f) => !canonical.some((re) => re.test(f)));

	const docsEvent = events.filter((e) => e.event === "docs").at(-1) ?? null;
	const lastRedIdx = events.findLastIndex((e) => e.event === "red");
	const redEvent = lastRedIdx === -1 ? null : events[lastRedIdx];
	const verifyEvent =
		events
			.slice(lastRedIdx + 1)
			.filter((e) => e.event === "verify" && e.exit === 0)
			.at(-1) ?? null;

	const loop = {
		docs: docsEvent
			? { done: true, source: "ledger", decision: docsEvent.decision, paths: docsEvent.paths }
			: docsChanged.length > 0
				? { done: true, source: "diff", paths: docsChanged }
				: { done: false },
		red: redEvent
			? { done: true, genuine: redEvent.genuine, cmd: redEvent.cmd, exit: redEvent.exit }
			: { done: false },
		impl: { done: nonDocChanged.length > 0 },
		verify: verifyEvent ? { done: true, cmd: verifyEvent.cmd, exit: verifyEvent.exit } : { done: false },
	};
	const pr = statusPr(cwd);

	let next;
	if (pr.state === "open" && pr.checks.failure > 0) {
		// a red required check on an open PR outranks everything — pr-green
		next = `drive PR #${pr.number}'s required checks terminal-green (pr-green playbook)`;
	} else if (!loop.docs.done) {
		next = "make the docs decision: edit the canonical docs, or record `stdd docs <decision>`";
	} else if (!loop.red.done) {
		next = "write the failing test and record it via `stdd red -- <cmd>`";
	} else if (!loop.impl.done) {
		next = "implement until the red test passes";
	} else if (!loop.verify.done) {
		next = "run the narrowest verify lane via `stdd verify -- <cmd>`";
	} else if (pr.state === "none") {
		next = "draft the evidence line via `stdd evidence`, then open the PR";
	} else if (pr.state === "open" && (pr.checks.failure > 0 || pr.checks.pending > 0)) {
		next = `drive PR #${pr.number}'s required checks terminal-green (pr-green playbook)`;
	} else if (pr.state === "open") {
		next = `PR #${pr.number} checks are green — done pending review and merge`;
	} else {
		next = `PR state unknown (${pr.reason}) — draft the evidence line via \`stdd evidence\` if no PR exists yet`;
	}

	if (asJson) {
		console.log(JSON.stringify({ branch, loop, pr, next }, null, "\t"));
		return;
	}
	const mark = (step) => (step.done ? "✓" : "✗");
	const docsDetail = docsEvent
		? ` (${docsEvent.decision}${docsEvent.paths?.length ? `: ${docsEvent.paths.join(", ")}` : ""})`
		: docsChanged.length > 0
			? ` (diff: ${docsChanged.join(", ")})`
			: changed === null
				? " — unknown (no resolvable baseRef)"
				: " — no docs decision recorded, no canonical docs in the diff";
	const redDetail = redEvent
		? ` (genuine: ${redEvent.genuine}, exit ${redEvent.exit}: ${redEvent.cmd})`
		: " — no red recorded";
	const implDetail = loop.impl.done
		? " (working tree has non-doc changes)"
		: " — no non-doc changes yet";
	const verifyDetail = verifyEvent
		? ` (exit 0: ${verifyEvent.cmd})`
		: " — no passing verify recorded since the last red";
	const prLine =
		pr.state === "open"
			? `#${pr.number} — ${pr.checks.failure} failing, ${pr.checks.pending} pending, ${pr.checks.success} green`
			: pr.state === "none"
				? `none for ${branch}`
				: `unknown (${pr.reason})`;
	console.log(
		[
			`loop:   docs ${mark(loop.docs)}${docsDetail}`,
			`        red  ${mark(loop.red)}${redDetail}`,
			`        impl ${mark(loop.impl)}${implDetail}`,
			`        verify ${mark(loop.verify)}${verifyDetail}`,
			`pr:     ${prLine}`,
			`next:   ${next}`,
		].join("\n"),
	);
}

/**
 * Draft the docs evidence line from the actual diff instead of recall.
 * Canonical docs changed → the finished line on stdout (substitution-safe);
 * none changed → the authored-sentinel templates on stderr, nonzero exit.
 */
function evidence(targetDir, baseRefFlag) {
	const config = loadConfig(targetDir);
	const base = baseRefFlag ?? config.baseRef;
	if (!base) {
		fail('evidence needs a base ref — pass --base <ref> or set "baseRef" in .stdd/config.json');
	}
	let changed;
	try {
		changed = execFileSync("git", ["-C", targetDir, "diff", "--name-only", `${base}...HEAD`], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		})
			.split("\n")
			.filter(Boolean);
	} catch (err) {
		fail(`--base ${base}: git diff failed: ${err.stderr?.toString().trim() || err.message}`);
	}
	const canonical = config.canonicalDocs.map(globToRegExp);
	const docs = changed.filter((file) => canonical.some((re) => re.test(file)));
	// The ledger's recorded decision is read first; the diff is the
	// cross-check, and on contradiction the diff wins and the conflict is
	// reported. loadLedger needs a branch — outside a git repo there is no
	// ledger to consult, so degrade to diff-only.
	const evidenceBranch = currentBranch(targetDir);
	const recorded = evidenceBranch
		? (loadLedger(targetDir, evidenceBranch)
				.filter((e) => e.event === "docs")
				.at(-1) ?? null)
		: null;
	if (docs.length > 0) {
		if (recorded && recorded.decision !== "updated-first") {
			console.error(
				`stdd evidence: the ledger records "${recorded.decision}" but the diff changes ` +
					`canonical docs — the diff wins; the ledger claim is contradicted`,
			);
		}
		console.log(`Docs updated first: ${docs.join(", ")}`);
		return;
	}
	if (recorded?.decision === "checked") {
		console.log(`Docs checked, no change needed: ${recorded.paths.join(", ")} — ${recorded.reason}`);
		return;
	}
	if (recorded?.decision === "not-applicable") {
		console.log(`Docs not applicable: ${recorded.reason}`);
		return;
	}
	fail(
		`no canonical docs changed against ${base}${
			recorded ? ` — the ledger claims "updated-first" but the diff is contradicted` : ""
		} — author the evidence line yourself:\n` +
			"  Docs checked, no change needed: <docs + reason>\n" +
			"  Docs not applicable: <why implementation-only>",
	);
}

function checkPr(prBodyFile, baseRef, pr) {
	let body;
	let headRef = "HEAD";
	let okSuffix = "";
	if (pr) {
		if (prBodyFile) fail(`--pr replaces the <file|-> argument — drop "${prBodyFile}"`);
		if (baseRef) fail("--pr derives the base from the PR — drop --base");
		const live = resolveLivePr(pr);
		body = live.body;
		baseRef = live.baseRef;
		headRef = live.headRef;
		const shortHead = (headRef === "HEAD" ? git("rev-parse", "HEAD") : headRef).slice(0, 7);
		okSuffix = ` (PR #${live.number} body, base ${baseRef}, head ${shortHead})`;
	} else {
		body =
			prBodyFile === "-" || !prBodyFile
				? fs.readFileSync(0, "utf8")
				: fs.readFileSync(prBodyFile, "utf8");
	}
	const matches = findEvidenceLines(body);
	if (matches.length === 0) {
		let message =
			"PR body has no docs evidence line. Add exactly one of:\n" +
			"  Docs updated first: <docs>\n" +
			"  Docs checked, no change needed: <docs + reason>\n" +
			"  Docs not applicable: <why implementation-only>";
		for (const near of nearMissEvidenceLines(body)) {
			message +=
				`\n\nline ${near.line} is a near-miss:\n` +
				`  found: ${near.raw.trim()}\n` +
				`  fix:   ${near.suggestion}\n` +
				"  (the line must start at column 0 with the exact label, no markdown formatting)";
		}
		fail(message);
	}
	if (matches.length > 1) {
		fail("PR body has more than one docs evidence line — keep exactly one.");
	}
	if (matches[0].content === "") {
		fail(`"${matches[0].label}:" names no evidence — list the docs or the reason after the colon.`);
	}
	const repoDir = resolveRepoDir(process.cwd());
	if (baseRef) verifyEvidenceAgainstDiff(matches[0], baseRef, headRef, repoDir);
	// Advisory only — a ledger disagreement never changes the pass condition.
	const advisoryBranch = currentBranch(repoDir);
	const recorded = advisoryBranch
		? (loadLedger(repoDir, advisoryBranch)
				.filter((e) => e.event === "docs")
				.at(-1) ?? null)
		: null;
	if (recorded && LABEL_TO_DECISION[matches[0].label] !== recorded.decision) {
		console.error(
			`stdd check-pr: advisory — the ledger records the docs decision as ` +
				`"${recorded.decision}" but the PR body says "${matches[0].label}"`,
		);
	}
	console.log(`stdd check-pr: OK${okSuffix}`);
}

/** With --base: the evidence claim must be backed by the actual git diff. */
function verifyEvidenceAgainstDiff(
	{ label, content },
	baseRef,
	headRef = "HEAD",
	repoDir = process.cwd(),
) {
	const paths = extractDocPaths(content);
	if (label === "Docs updated first") {
		if (paths.length === 0) {
			const suggestion = sentinelSuggestion(content);
			fail(
				`"Docs updated first:" names no doc paths — list the changed docs.` +
					(suggestion ? `\nDid you mean:\n  ${suggestion}` : ""),
			);
		}
		let changed;
		try {
			changed = execFileSync("git", ["diff", "--name-only", `${baseRef}...${headRef}`], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			})
				.split("\n")
				.filter(Boolean);
		} catch (err) {
			fail(`--base ${baseRef}: git diff failed: ${err.stderr?.toString().trim() || err.message}`);
		}
		const missing = paths.filter((p) => !changed.includes(p));
		if (missing.length > 0) {
			fail(`claimed as updated but not changed against ${baseRef}: ${missing.join(", ")}`);
		}
	} else if (label === "Docs checked, no change needed") {
		const absent = paths.filter((p) => !fs.existsSync(path.join(repoDir, ...p.split("/"))));
		if (absent.length > 0) {
			fail(`claimed as checked but does not exist in the tree: ${absent.join(", ")}`);
		}
	}
}

// --- argument parsing (strict: unknown flags are errors) ---
const [, , command, ...rest] = process.argv;

// Ledger commands parse their own arguments (`--` passthrough, repeated
// positionals) and exit here; the strict generic loop below never sees them.
if (command === "red" || command === "verify") {
	const sep = rest.indexOf("--");
	if (sep === -1 || sep === rest.length - 1) {
		fail(`${command} needs a command: stdd ${command} -- <cmd> [args…]`);
	}
	if (sep !== 0) fail(`unexpected argument before --: ${rest[0]}`);
	recordRun(resolveRepoDir(process.cwd()), command, rest.slice(sep + 1));
}
if (command === "docs") {
	let reason = null;
	const words = [];
	for (let i = 0; i < rest.length; i++) {
		const arg = rest[i];
		if (arg === "--reason" || arg.startsWith("--reason=")) {
			reason = arg.includes("=") ? arg.slice("--reason=".length) : (rest[++i] ?? "");
			if (!reason) fail("--reason requires a value");
		} else if (arg.startsWith("--")) {
			fail(`unknown flag: ${arg}`);
		} else {
			words.push(arg);
		}
	}
	recordDocs(resolveRepoDir(process.cwd()), words[0], words.slice(1), reason);
	process.exit(0);
}
if (command === "note") {
	const text = rest.join(" ").trim();
	if (!text) fail("note needs text: stdd note <text>");
	appendLedger(resolveRepoDir(process.cwd()), { event: "note", text });
	console.log("stdd note: recorded");
	process.exit(0);
}
if (command === "slice") {
	if (rest[0] !== "new") {
		fail(`unknown slice subcommand "${rest[0] ?? ""}" — use "stdd slice new"`);
	}
	let frozen = [];
	let allowed = [];
	for (let i = 1; i < rest.length; i++) {
		const arg = rest[i];
		if (arg === "--frozen" || arg.startsWith("--frozen=")) {
			const value = arg.includes("=") ? arg.slice("--frozen=".length) : (rest[++i] ?? "");
			frozen = value.split(",").filter(Boolean);
			if (frozen.length === 0) fail("--frozen requires globs, e.g. --frozen docs/**,migrations/**");
		} else if (arg === "--allowed" || arg.startsWith("--allowed=")) {
			const value = arg.includes("=") ? arg.slice("--allowed=".length) : (rest[++i] ?? "");
			allowed = value.split(",").filter(Boolean);
			if (allowed.length === 0) fail("--allowed requires globs, e.g. --allowed src/billing/**");
		} else {
			fail(`unexpected argument: ${arg}`);
		}
	}
	sliceNew(resolveRepoDir(process.cwd()), frozen, allowed);
	process.exit(0);
}
if (command === "scope") {
	if (rest.length > 0) fail(`unexpected argument: ${rest[0]}`);
	scopeCheck(resolveRepoDir(process.cwd()));
	process.exit(0);
}
if (command === "status") {
	const unknown = rest.filter((a) => a !== "--json");
	if (unknown.length > 0) fail(`unexpected argument: ${unknown[0]}`);
	status(resolveRepoDir(process.cwd()), rest.includes("--json"));
	process.exit(0);
}
let tools = null;
let ci = null;
let baseRefArg = null;
let prArg = null;
let readinessOnly = false;
let hooksFlag = false;
const positional = [];
for (let i = 0; i < rest.length; i++) {
	const arg = rest[i];
	if (arg === "--base" || arg.startsWith("--base=")) {
		if (command !== "check-pr" && command !== "evidence") {
			fail(`--base is only valid for "stdd check-pr" and "stdd evidence"`);
		}
		baseRefArg = arg.includes("=") ? arg.slice("--base=".length) : (rest[++i] ?? "");
		if (!baseRefArg) fail("--base requires a git ref, e.g. --base origin/main");
	} else if (arg === "--hooks") {
		if (command !== "init") fail(`--hooks is only valid for "stdd init"`);
		hooksFlag = true;
	} else if (arg === "--readiness") {
		if (command !== "doctor") fail(`--readiness is only valid for "stdd doctor"`);
		readinessOnly = true;
	} else if (arg === "--pr" || arg.startsWith("--pr=")) {
		if (command !== "check-pr") fail(`--pr is only valid for "stdd check-pr"`);
		prArg = arg.includes("=") ? arg.slice("--pr=".length) : (rest[++i] ?? "");
		if (!prArg) fail("--pr requires a PR number, or . for the current branch's PR");
	} else if (arg === "--ci" || arg.startsWith("--ci=")) {
		if (command !== "init") fail(`--ci is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--ci=".length) : (rest[++i] ?? "");
		ci = value.split(",").filter(Boolean);
		if (ci.length === 0) fail("--ci requires a value, e.g. --ci github");
		const unknown = ci.filter((c) => !KNOWN_CI.includes(c));
		if (unknown.length > 0) {
			fail(`unknown ci provider(s): ${unknown.join(", ")} (known: ${KNOWN_CI.join(", ")})`);
		}
	} else if (arg === "--tools" || arg.startsWith("--tools=")) {
		if (command !== "init") fail(`--tools is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--tools=".length) : (rest[++i] ?? "");
		tools = value.split(",").filter(Boolean);
		if (tools.length === 0) fail("--tools requires a value, e.g. --tools claude,codex");
		const unknown = tools.filter((t) => !KNOWN_TOOLS.includes(t));
		if (unknown.length > 0) {
			fail(`unknown tool(s): ${unknown.join(", ")} (known: ${KNOWN_TOOLS.join(", ")})`);
		}
	} else if (arg.startsWith("--")) {
		fail(`unknown flag: ${arg}`);
	} else {
		positional.push(arg);
	}
}
if (positional.length > 1) fail(`unexpected argument: ${positional[1]}`);
const targetDir = path.resolve(positional[0] ?? ".");

switch (command) {
	case "init":
		init(targetDir, tools ?? KNOWN_TOOLS, ci ?? [], hooksFlag);
		break;
	case "check":
		check(targetDir);
		break;
	case "doctor":
		doctor(targetDir, readinessOnly);
		break;
	case "check-pr":
		checkPr(positional[0], baseRefArg, prArg);
		break;
	case "evidence":
		// Without an explicit dir, evidence anchors to the repo like the
		// recorders — its config and ledger live at the root .stdd/.
		evidence(positional[0] ? targetDir : resolveRepoDir(process.cwd()), baseRefArg);
		break;
	case "--version":
	case "version":
		console.log(VERSION);
		break;
	default:
		console.log(
			"Usage: stdd <init|check|check-pr|evidence|doctor|status|docs|red|verify|note|slice|scope> " +
				"[dir|pr-body-file] [--tools claude,codex] [--ci github] [--hooks] [--base <ref>] " +
				"[--pr <n|.>] [--readiness] [--json] [--reason <why>] [-- <cmd>]",
		);
		process.exit(command ? 1 : 0);
}
