#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	DEFAULT_CONFIG,
	extractDocPaths,
	findEvidenceLines,
	globToRegExp,
	mergeConfig,
	parseFrontmatter,
	scanTemporal,
	sha256,
	temporalMatchers,
} from "./lib.mjs";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSION = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "package.json"), "utf8")).version;
const KNOWN_TOOLS = ["claude", "codex"];
const STAMP = `generated by stdd v${VERSION} — do not edit, re-run \`stdd init\``;

function fail(message) {
	console.error(`stdd: ${message}`);
	process.exit(1);
}

function listTrackedFiles(dir) {
	try {
		const out = execFileSync("git", ["-C", dir, "ls-files", "-z"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		});
		const files = out.split("\0").filter(Boolean);
		if (files.length > 0) return files;
	} catch {
		// not a git repo — fall through to a filesystem walk
	}
	const files = [];
	const walk = (rel) => {
		for (const entry of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
			if (entry.name === ".git" || entry.name === "node_modules") continue;
			const relPath = rel ? `${rel}/${entry.name}` : entry.name;
			if (entry.isDirectory()) walk(relPath);
			else files.push(relPath);
		}
	};
	walk("");
	return files;
}

function loadPlaybooks() {
	const dir = path.join(PKG_ROOT, "playbooks");
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md"))
		.map((f) => {
			const source = fs.readFileSync(path.join(dir, f), "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`playbook ${f} is missing required frontmatter (name, description)`);
			}
			return { file: f, source, meta, body };
		});
}

function loadConfig(targetDir) {
	const configPath = path.join(targetDir, ".stdd", "config.json");
	if (!fs.existsSync(configPath)) return DEFAULT_CONFIG;
	let parsed;
	try {
		parsed = JSON.parse(fs.readFileSync(configPath, "utf8"));
	} catch (err) {
		fail(`.stdd/config.json is not valid JSON: ${err.message}`);
	}
	try {
		return mergeConfig(parsed);
	} catch (err) {
		fail(`.stdd/config.json: ${err.message}`);
	}
}

function init(targetDir, tools) {
	const stddDir = path.join(targetDir, ".stdd");
	fs.mkdirSync(path.join(stddDir, "playbooks"), { recursive: true });
	// Every generated file is recorded here (repo-relative path → content
	// hash) and written to .stdd/manifest.json, so check/doctor can detect
	// hand edits, deletions, and stale copies. User-owned files (config.json)
	// are deliberately not recorded.
	const generated = {};
	const writeGenerated = (relPath, content) => {
		fs.writeFileSync(path.join(targetDir, ...relPath.split("/")), content);
		generated[relPath] = sha256(content);
	};

	writeGenerated(".stdd/method.md", fs.readFileSync(path.join(PKG_ROOT, "method", "README.md"), "utf8"));
	const playbooks = loadPlaybooks();
	for (const pb of playbooks) {
		writeGenerated(`.stdd/playbooks/${pb.file}`, pb.source);
	}
	const configPath = path.join(stddDir, "config.json");
	if (!fs.existsSync(configPath)) {
		fs.writeFileSync(configPath, `${JSON.stringify(DEFAULT_CONFIG, null, "\t")}\n`);
	}
	console.log(`Installed .stdd/ (method, ${playbooks.length} playbooks, config)`);

	if (tools.includes("claude")) {
		for (const pb of playbooks) {
			const skillDir = path.join(targetDir, ".claude", "skills", pb.meta.name);
			fs.mkdirSync(skillDir, { recursive: true });
			const skill =
				`---\nname: ${pb.meta.name}\ndescription: ${pb.meta.description}\n---\n\n` +
				`<!-- ${STAMP} -->\n\n${pb.body}`;
			writeGenerated(`.claude/skills/${pb.meta.name}/SKILL.md`, skill);
		}
		console.log(`Installed ${playbooks.length} Claude Code skills under .claude/skills/`);
	}

	if (tools.includes("codex")) {
		const lines = [
			`<!-- ${STAMP} -->`,
			"",
			"## STDD",
			"",
			"This repository follows the STDD method: read `.stdd/method.md` before",
			"any behavior change and follow its loop (docs edit is the spec → failing",
			"test → implement → verify → PR evidence).",
			"",
			"Do not search the project log (dated entries marked",
			"`authority: non-canonical`, e.g. `docs/project/`) unless the user",
			"explicitly asks for historical rationale or deferred work — it records",
			"past decisions and future intentions, never the present.",
			"",
			"Playbooks in `.stdd/playbooks/`:",
			"",
			...playbooks.map((pb) => `- \`${pb.file}\` — ${pb.meta.when ?? pb.meta.description}`),
		];
		const snippet = `${lines.join("\n")}\n`;
		writeGenerated(".stdd/AGENTS-snippet.md", snippet);
		console.log("\nAdd this to your AGENTS.md (also saved to .stdd/AGENTS-snippet.md):\n");
		console.log(snippet);
	}

	const manifest = { generatedBy: "stdd", version: VERSION, files: generated };
	fs.writeFileSync(path.join(stddDir, "manifest.json"), `${JSON.stringify(manifest, null, "\t")}\n`);
}

/**
 * Shared repository scan for `check` and `doctor`: committed working
 * artifacts, canonical docs and their temporal-narrative hits, and stale
 * generated files (a stale stamp means the CLI was upgraded without
 * re-running `stdd init`).
 */
function scanRepo(targetDir, config) {
	const files = listTrackedFiles(targetDir);

	const forbidden = config.forbiddenArtifacts.map(globToRegExp);
	const artifacts = files.filter((file) => forbidden.some((re) => re.test(file)));

	const canonical = config.canonicalDocs.map(globToRegExp);
	const canonicalFiles = files.filter((file) => canonical.some((re) => re.test(file)));
	const matchers = temporalMatchers(config.temporalPhrases);
	const temporal = [];
	for (const file of canonicalFiles) {
		const lines = fs.readFileSync(path.join(targetDir, file), "utf8").split("\n");
		for (const hit of scanTemporal(lines, matchers)) temporal.push({ file, ...hit });
	}

	return { artifacts, canonicalFiles, temporal, stale: scanGeneratedDrift(targetDir) };
}

/**
 * Generated-file drift, as `{ file, message }` findings. With a manifest
 * (written by `stdd init`), every generated file is verified by content
 * hash. Without one (repo initialized by an older stdd), fall back to the
 * version stamp inside Claude skills.
 */
function scanGeneratedDrift(targetDir) {
	const stale = [];
	const manifestPath = path.join(targetDir, ".stdd", "manifest.json");
	if (fs.existsSync(manifestPath)) {
		let manifest;
		try {
			manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
		} catch {
			return [{ file: ".stdd/manifest.json", message: "is not valid JSON — re-run stdd init" }];
		}
		if (manifest.version !== VERSION) {
			stale.push({
				file: ".stdd/manifest.json",
				message: `written by stdd v${manifest.version}, CLI is v${VERSION} — re-run stdd init`,
			});
		}
		for (const [file, hash] of Object.entries(manifest.files ?? {})) {
			const filePath = path.join(targetDir, ...file.split("/"));
			if (!fs.existsSync(filePath)) {
				stale.push({ file, message: "listed in .stdd/manifest.json but missing — re-run stdd init" });
			} else if (sha256(fs.readFileSync(filePath, "utf8")) !== hash) {
				stale.push({ file, message: "edited by hand or stale — re-run stdd init" });
			}
		}
		return stale;
	}

	const stampRe = /generated by stdd v([0-9][^\s]*) —/;
	const skillsDir = path.join(targetDir, ".claude", "skills");
	if (fs.existsSync(skillsDir)) {
		for (const name of fs.readdirSync(skillsDir)) {
			const skillPath = path.join(skillsDir, name, "SKILL.md");
			if (!fs.existsSync(skillPath)) continue;
			const m = stampRe.exec(fs.readFileSync(skillPath, "utf8"));
			if (m && m[1] !== VERSION) {
				stale.push({
					file: `.claude/skills/${name}/SKILL.md`,
					message: `generated by stdd v${m[1]}, CLI is v${VERSION} — re-run stdd init`,
				});
			}
		}
	}
	return stale;
}

function check(targetDir) {
	const config = loadConfig(targetDir);
	const { artifacts, temporal, stale } = scanRepo(targetDir, config);
	const violations = [
		...artifacts.map((file) => `${file}: committed working artifact (forbiddenArtifacts)`),
		...temporal.map(
			(hit) => `${hit.file}:${hit.line}: temporal narrative in canonical doc ("${hit.phrase}")`,
		),
		...stale.map((s) => `${s.file}: ${s.message}`),
	];

	if (violations.length > 0) {
		console.error(`stdd check: ${violations.length} violation(s)\n`);
		for (const v of violations) console.error(`  ${v}`);
		process.exit(1);
	}
	console.log("stdd check: OK");
}

function doctor(targetDir) {
	const count = (n, singular, plural) => `${n} ${n === 1 ? singular : plural}`;
	let failed = false;
	const report = (ok, message) => {
		console.log(`${ok ? "✓" : "✗"} ${message}`);
		if (!ok) failed = true;
	};

	const installed = fs.existsSync(path.join(targetDir, ".stdd", "method.md"));
	report(installed, installed ? ".stdd/ installed" : ".stdd/ is not installed — run stdd init");

	const config = loadConfig(targetDir);
	const { artifacts, canonicalFiles, temporal, stale } = scanRepo(targetDir, config);

	report(
		canonicalFiles.length > 0,
		canonicalFiles.length > 0
			? `canonical docs present (${count(canonicalFiles.length, "file", "files")})`
			: "no canonical docs found — create docs/domain/ or docs/product/, or adjust canonicalDocs",
	);

	report(
		artifacts.length === 0,
		artifacts.length === 0
			? "no committed working artifacts"
			: `${count(artifacts.length, "committed working artifact", "committed working artifacts")} may mislead coding agents`,
	);

	const temporalFiles = new Set(temporal.map((hit) => hit.file)).size;
	report(
		temporalFiles === 0,
		temporalFiles === 0
			? "canonical docs describe the present (no temporal narrative)"
			: `${count(temporalFiles, "canonical doc contains", "canonical docs contain")} temporal narrative`,
	);

	report(
		stale.length === 0,
		stale.length === 0
			? `generated files match stdd v${VERSION}`
			: `${count(stale.length, "generated file is", "generated files are")} stale — re-run stdd init`,
	);

	const agentsPath = path.join(targetDir, "AGENTS.md");
	if (fs.existsSync(agentsPath)) {
		const hasSection = /^## STDD$/m.test(fs.readFileSync(agentsPath, "utf8"));
		report(
			hasSection,
			hasSection
				? "AGENTS.md carries the STDD section"
				: "AGENTS.md has no STDD section — paste .stdd/AGENTS-snippet.md",
		);
	}

	if (failed) process.exit(1);
}

function checkPr(prBodyFile, baseRef) {
	const body =
		prBodyFile === "-" || !prBodyFile ? fs.readFileSync(0, "utf8") : fs.readFileSync(prBodyFile, "utf8");
	const matches = findEvidenceLines(body);
	if (matches.length === 0) {
		fail(
			"PR body has no docs evidence line. Add exactly one of:\n" +
				"  Docs updated first: <docs>\n" +
				"  Docs checked, no change needed: <docs + reason>\n" +
				"  Docs not applicable: <why implementation-only>",
		);
	}
	if (matches.length > 1) {
		fail("PR body has more than one docs evidence line — keep exactly one.");
	}
	if (matches[0].content === "") {
		fail(`"${matches[0].label}:" names no evidence — list the docs or the reason after the colon.`);
	}
	if (baseRef) verifyEvidenceAgainstDiff(matches[0], baseRef);
	console.log("stdd check-pr: OK");
}

/** With --base: the evidence claim must be backed by the actual git diff. */
function verifyEvidenceAgainstDiff({ label, content }, baseRef) {
	const paths = extractDocPaths(content);
	if (label === "Docs updated first") {
		if (paths.length === 0) {
			fail(`"Docs updated first:" names no doc paths — list the changed docs.`);
		}
		let changed;
		try {
			changed = execFileSync("git", ["diff", "--name-only", `${baseRef}...HEAD`], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			})
				.split("\n")
				.filter(Boolean);
		} catch (err) {
			fail(`--base ${baseRef}: git diff failed: ${err.stderr?.toString().trim() || err.message}`);
		}
		const missing = paths.filter((p) => !changed.includes(p));
		if (missing.length > 0) {
			fail(`claimed as updated but not changed against ${baseRef}: ${missing.join(", ")}`);
		}
	} else if (label === "Docs checked, no change needed") {
		const absent = paths.filter((p) => !fs.existsSync(path.join(process.cwd(), ...p.split("/"))));
		if (absent.length > 0) {
			fail(`claimed as checked but does not exist in the tree: ${absent.join(", ")}`);
		}
	}
}

// --- argument parsing (strict: unknown flags are errors) ---
const [, , command, ...rest] = process.argv;
let tools = null;
let baseRefArg = null;
const positional = [];
for (let i = 0; i < rest.length; i++) {
	const arg = rest[i];
	if (arg === "--base" || arg.startsWith("--base=")) {
		if (command !== "check-pr") fail(`--base is only valid for "stdd check-pr"`);
		baseRefArg = arg.includes("=") ? arg.slice("--base=".length) : (rest[++i] ?? "");
		if (!baseRefArg) fail("--base requires a git ref, e.g. --base origin/main");
	} else if (arg === "--tools" || arg.startsWith("--tools=")) {
		if (command !== "init") fail(`--tools is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--tools=".length) : (rest[++i] ?? "");
		tools = value.split(",").filter(Boolean);
		if (tools.length === 0) fail("--tools requires a value, e.g. --tools claude,codex");
		const unknown = tools.filter((t) => !KNOWN_TOOLS.includes(t));
		if (unknown.length > 0) {
			fail(`unknown tool(s): ${unknown.join(", ")} (known: ${KNOWN_TOOLS.join(", ")})`);
		}
	} else if (arg.startsWith("--")) {
		fail(`unknown flag: ${arg}`);
	} else {
		positional.push(arg);
	}
}
if (positional.length > 1) fail(`unexpected argument: ${positional[1]}`);
const targetDir = path.resolve(positional[0] ?? ".");

switch (command) {
	case "init":
		init(targetDir, tools ?? KNOWN_TOOLS);
		break;
	case "check":
		check(targetDir);
		break;
	case "doctor":
		doctor(targetDir);
		break;
	case "check-pr":
		checkPr(positional[0], baseRefArg);
		break;
	case "--version":
	case "version":
		console.log(VERSION);
		break;
	default:
		console.log(
			"Usage: stdd <init|check|check-pr|doctor> [dir|pr-body-file] [--tools claude,codex] [--base <ref>]",
		);
		process.exit(command ? 1 : 0);
}
