#!/usr/bin/env node
import { execFileSync, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import {
	appendDeferred,
	compileCapabilities,
	DEFAULT_CONFIG,
	dedupeChecks,
	deriveReviewVerdict,
	didYouMean,
	extractDocPaths,
	findEvidenceLines,
	globToRegExp,
	mergeConfig,
	nearMissEvidenceLines,
	parseFrontmatter,
	parseLedger,
	parsePlan,
	parseReviewResult,
	planProgress,
	redGenuine,
	scanTemporal,
	sentinelSuggestion,
	sha256,
	temporalMatchers,
	workflowValidatesStaleBody,
} from "./lib.mjs";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSION = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "package.json"), "utf8")).version;
const KNOWN_TOOLS = ["claude", "codex"];
const KNOWN_CI = ["github"];
const KNOWN_CAPABILITIES = Object.keys(DEFAULT_CONFIG.capabilities);
const STAMP = `generated by stdd v${VERSION} — do not edit, re-run \`stdd init\``;

function fail(message) {
	console.error(`stdd: ${message}`);
	process.exit(1);
}

function listTrackedFiles(dir) {
	try {
		const out = execFileSync("git", ["-C", dir, "ls-files", "-z"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "ignore"],
		});
		const files = out.split("\0").filter(Boolean);
		if (files.length > 0) return files;
	} catch {
		// not a git repo — fall through to a filesystem walk
	}
	const files = [];
	const walk = (rel) => {
		for (const entry of fs.readdirSync(path.join(dir, rel), { withFileTypes: true })) {
			if (entry.name === ".git" || entry.name === "node_modules") continue;
			const relPath = rel ? `${rel}/${entry.name}` : entry.name;
			if (entry.isDirectory()) walk(relPath);
			else files.push(relPath);
		}
	};
	walk("");
	return files;
}

function loadPlaybooks() {
	const dir = path.join(PKG_ROOT, "playbooks");
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md"))
		.map((f) => {
			const source = fs.readFileSync(path.join(dir, f), "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`playbook ${f} is missing required frontmatter (name, description)`);
			}
			return { file: f, source, meta, body };
		});
}

/**
 * Project recipes: repo-owned playbooks in `.stdd/playbooks/local/`, same
 * frontmatter contract as the kit's. Never generated, never overwritten.
 */
function loadLocalPlaybooks(targetDir) {
	const dir = path.join(targetDir, ".stdd", "playbooks", "local");
	if (!fs.existsSync(dir)) return [];
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md"))
		.map((f) => {
			const source = fs.readFileSync(path.join(dir, f), "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`local playbook local/${f} is missing required frontmatter (name, description)`);
			}
			return { file: f, source, meta, body };
		});
}

/** Files recorded by the previous init, or {} without a readable manifest. */
function readManifestFiles(stddDir) {
	try {
		return JSON.parse(fs.readFileSync(path.join(stddDir, "manifest.json"), "utf8")).files ?? {};
	} catch {
		return {};
	}
}

/**
 * `--capabilities <list>`: write the full profile into the user-owned
 * config — named capabilities on, every other known one off. Other config
 * keys survive untouched.
 */
function writeCapabilities(targetDir, list) {
	const configPath = path.join(targetDir, ".stdd", "config.json");
	let parsed = { ...DEFAULT_CONFIG };
	if (fs.existsSync(configPath)) {
		try {
			parsed = JSON.parse(fs.readFileSync(configPath, "utf8"));
		} catch (err) {
			fail(`.stdd/config.json is not valid JSON: ${err.message}`);
		}
	}
	parsed.capabilities = Object.fromEntries(KNOWN_CAPABILITIES.map((c) => [c, list.includes(c)]));
	fs.writeFileSync(configPath, `${JSON.stringify(parsed, null, "\t")}\n`);
}

/**
 * `--session-hook`: merge a SessionStart hook running `stdd status` into
 * `.claude/settings.json` — every fresh context window (startup, clear,
 * compact) opens with the loop state in it. Merged, never duplicated; a
 * settings file that does not parse is left untouched.
 */
function installSessionHook(targetDir) {
	const settingsPath = path.join(targetDir, ".claude", "settings.json");
	const entry = {
		matcher: "startup|clear|compact",
		hooks: [{ type: "command", command: "npx --no stdd status || true" }],
	};
	let settings = {};
	if (fs.existsSync(settingsPath)) {
		try {
			settings = JSON.parse(fs.readFileSync(settingsPath, "utf8"));
		} catch {
			console.error(
				".claude/settings.json does not parse — left untouched; merge the hook manually:\n  " +
					JSON.stringify({ hooks: { SessionStart: [entry] } }),
			);
			return;
		}
	}
	settings.hooks ??= {};
	settings.hooks.SessionStart ??= [];
	if (JSON.stringify(settings.hooks.SessionStart).includes("stdd status")) {
		console.log(".claude/settings.json already carries the session-start hook — left untouched");
		return;
	}
	settings.hooks.SessionStart.push(entry);
	fs.mkdirSync(path.dirname(settingsPath), { recursive: true });
	fs.writeFileSync(settingsPath, `${JSON.stringify(settings, null, "\t")}\n`);
	console.log(
		"Wired the Claude Code SessionStart hook (startup|clear|compact → stdd status) in .claude/settings.json",
	);
}

/**
 * `--interview`: one question at a time, the recommended answer first —
 * an empty answer takes it. Piped answers work; a stream that ends early
 * resolves every remaining question to its default.
 */
async function interview() {
	const rl = createInterface({ input: process.stdin, output: process.stdout });
	// Own line queue instead of rl.question: piped answers arrive in one
	// burst, and lines emitted while no question is pending would be lost.
	const lines = [];
	const waiters = [];
	let closed = false;
	rl.on("line", (line) => {
		const waiter = waiters.shift();
		if (waiter) waiter(line);
		else lines.push(line);
	});
	rl.on("close", () => {
		closed = true;
		while (waiters.length > 0) waiters.shift()("");
	});
	const readLine = () => {
		if (lines.length > 0) return Promise.resolve(lines.shift());
		if (closed) return Promise.resolve("");
		return new Promise((resolve) => waiters.push(resolve));
	};
	const ask = async (question, def) => {
		process.stdout.write(question);
		const answer = (await readLine()).trim();
		return answer === "" ? def : answer;
	};
	const yes = async (question, def) =>
		/^y/i.test(await ask(`${question} ${def ? "[Y/n]" : "[y/N]"} `, def ? "y" : "n"));

	console.log("stdd init — one question at a time; an empty answer takes the recommended default\n");
	const toolsAnswer = await ask(
		`Agents to compile for (${KNOWN_TOOLS.join(", ")}) [${KNOWN_TOOLS.join(",")}]: `,
		KNOWN_TOOLS.join(","),
	);
	const tools = toolsAnswer
		.split(",")
		.map((t) => t.trim())
		.filter(Boolean);
	const unknownTools = tools.filter((t) => !KNOWN_TOOLS.includes(t));
	if (unknownTools.length > 0) {
		rl.close();
		fail(`unknown tool(s): ${unknownTools.join(", ")} (known: ${KNOWN_TOOLS.join(", ")})`);
	}
	const capabilitiesList = [];
	if (await yes("Can agents dispatch subagents?", true)) capabilitiesList.push("subagents");
	if (await yes("May Claude Code and Codex invoke each other?", false))
		capabilitiesList.push("crossCli");
	if (await yes("Are isolated git worktrees available?", true)) capabilitiesList.push("worktrees");
	const ci = (await yes("Install the GitHub Actions gate (stdd check + PR evidence)?", true))
		? ["github"]
		: [];
	const hooks = await yes("Install the pre-push hook (stdd check — fast, offline)?", true);
	const sessionHook = tools.includes("claude")
		? await yes("Wire the Claude Code session-start hook (stdd status)?", true)
		: false;
	rl.close();
	return { tools, ci, hooks, sessionHook, capabilitiesList };
}

function loadConfig(targetDir) {
	const configPath = path.join(targetDir, ".stdd", "config.json");
	if (!fs.existsSync(configPath)) return DEFAULT_CONFIG;
	let parsed;
	try {
		parsed = JSON.parse(fs.readFileSync(configPath, "utf8"));
	} catch (err) {
		fail(`.stdd/config.json is not valid JSON: ${err.message}`);
	}
	try {
		return mergeConfig(parsed);
	} catch (err) {
		fail(`.stdd/config.json: ${err.message}`);
	}
}

function init(targetDir, opts) {
	const { tools, ci, hooks, sessionHook, capabilitiesList } = opts;
	const stddDir = path.join(targetDir, ".stdd");
	fs.mkdirSync(path.join(stddDir, "playbooks"), { recursive: true });
	if (capabilitiesList) writeCapabilities(targetDir, capabilitiesList);
	const capabilities = loadConfig(targetDir).capabilities;
	// The previous run's manifest: files it generated that this profile no
	// longer produces are removed at the end — only when still byte-identical.
	const oldFiles = readManifestFiles(stddDir);
	// Every generated file is recorded here (repo-relative path → content
	// hash) and written to .stdd/manifest.json, so check/doctor can detect
	// hand edits, deletions, and stale copies. User-owned files (config.json,
	// local recipes) are deliberately not recorded.
	const generated = {};
	const writeGenerated = (relPath, content) => {
		fs.writeFileSync(path.join(targetDir, ...relPath.split("/")), content);
		generated[relPath] = sha256(content);
	};

	writeGenerated(".stdd/method.md", fs.readFileSync(path.join(PKG_ROOT, "method", "README.md"), "utf8"));
	// Kit playbooks minus those a local recipe overrides by name, then both
	// sets filtered by `requires:` and compiled against the profile.
	const local = loadLocalPlaybooks(targetDir);
	const localNames = new Set(local.map((pb) => pb.meta.name));
	const kit = loadPlaybooks().filter((pb) => {
		if (!localNames.has(pb.meta.name)) return true;
		console.log(`local recipe overrides the kit playbook "${pb.meta.name}" (${pb.file})`);
		return false;
	});
	const applies = (pb) => {
		if (!pb.meta.requires) return true;
		if (!KNOWN_CAPABILITIES.includes(pb.meta.requires)) {
			fail(`playbook ${pb.file}: requires unknown capability "${pb.meta.requires}"`);
		}
		return capabilities[pb.meta.requires];
	};
	const compile = (pb, text) => {
		try {
			return compileCapabilities(text, capabilities);
		} catch (err) {
			fail(`playbook ${pb.file}: ${err.message}`);
		}
	};
	const kitActive = kit.filter(applies);
	const localActive = local.filter(applies);
	for (const pb of kitActive) {
		writeGenerated(`.stdd/playbooks/${pb.file}`, compile(pb, pb.source));
	}
	const configPath = path.join(stddDir, "config.json");
	if (!fs.existsSync(configPath)) {
		fs.writeFileSync(configPath, `${JSON.stringify(DEFAULT_CONFIG, null, "\t")}\n`);
	}
	console.log(`Installed .stdd/ (method, ${kitActive.length} playbooks, config)`);

	if (tools.includes("claude")) {
		for (const pb of [...kitActive, ...localActive]) {
			const skillDir = path.join(targetDir, ".claude", "skills", pb.meta.name);
			fs.mkdirSync(skillDir, { recursive: true });
			// the description is the only always-visible routing surface — the
			// `when:` trigger must ride on it, not sit unread in the body
			const description = pb.meta.when
				? `${pb.meta.description}. Use when: ${pb.meta.when}`
				: pb.meta.description;
			const skill =
				`---\nname: ${pb.meta.name}\ndescription: ${JSON.stringify(description)}\n---\n\n` +
				`<!-- ${STAMP} -->\n\n${compile(pb, pb.body)}`;
			writeGenerated(`.claude/skills/${pb.meta.name}/SKILL.md`, skill);
		}
		console.log(
			`Installed ${kitActive.length + localActive.length} Claude Code skills under .claude/skills/`,
		);
	}

	if (tools.includes("codex")) {
		const lines = [
			`<!-- ${STAMP} -->`,
			"",
			"## STDD",
			"",
			"This repository follows the STDD method: read `.stdd/method.md` before",
			"any behavior change and follow its loop (docs edit is the spec → failing",
			"test → implement → verify → PR evidence).",
			"",
			"Do not search the project log (dated entries marked",
			"`authority: non-canonical`, e.g. `docs/project/`) unless the user",
			"explicitly asks for historical rationale or deferred work — it records",
			"past decisions and future intentions, never the present.",
			"",
			"If `stdd` is not on PATH, run it via the package runner instead",
			"(`pnpm exec stdd`, `npx --no stdd`) — never skip recording a loop",
			"fact because the bare command failed.",
			...(capabilities.crossCli
				? [
						"",
						"Claude Code and Codex may invoke each other: dispatch the other CLI",
						"headless with a brief file (`codex exec`, `claude -p`) per the",
						"delegate-slice playbook.",
					]
				: []),
			"",
			"Playbooks in `.stdd/playbooks/`:",
			"",
			...kitActive.map((pb) => `- \`${pb.file}\` — ${pb.meta.when ?? pb.meta.description}`),
			...(localActive.length > 0
				? [
						"",
						"Project playbooks in `.stdd/playbooks/local/`:",
						"",
						...localActive.map(
							(pb) => `- \`local/${pb.file}\` — ${pb.meta.when ?? pb.meta.description}`,
						),
					]
				: []),
		];
		const snippet = `${lines.join("\n")}\n`;
		writeGenerated(".stdd/AGENTS-snippet.md", snippet);
		// AGENTS.md is user-owned (never manifest-tracked): only the marked
		// section is managed — created when absent, replaced in place when
		// present, everything outside the markers untouched
		const agentsPath = path.join(targetDir, "AGENTS.md");
		const block = `<!-- stdd:begin — managed section, re-run \`stdd init\` to update -->\n${snippet}<!-- stdd:end -->\n`;
		const markers = /<!-- stdd:begin[^>]*-->\r?\n[\s\S]*?<!-- stdd:end -->\r?\n?/;
		if (!fs.existsSync(agentsPath)) {
			fs.writeFileSync(agentsPath, block);
			console.log("Wrote AGENTS.md with the managed STDD section");
		} else {
			const current = fs.readFileSync(agentsPath, "utf8");
			const updated = markers.test(current)
				? current.replace(markers, block)
				: `${current}${current.endsWith("\n") ? "" : "\n"}\n${block}`;
			if (updated !== current) fs.writeFileSync(agentsPath, updated);
			console.log("Updated the managed STDD section in AGENTS.md");
		}
	}

	if (ci.includes("github")) {
		fs.mkdirSync(path.join(targetDir, ".github", "workflows"), { recursive: true });
		const workflow = fs
			.readFileSync(path.join(PKG_ROOT, "templates", "github-stdd.yml"), "utf8")
			.replace("__STAMP__", STAMP);
		writeGenerated(".github/workflows/stdd.yml", workflow);
		console.log("Installed .github/workflows/stdd.yml (validates the live PR body)");
	}

	if (hooks) {
		// One fast offline command only — network calls in hooks produce
		// false positives that train --no-verify. User-owned after
		// generation (like config.json): never manifested, never overwritten.
		const hookPath = path.join(stddDir, "hooks", "pre-push");
		if (fs.existsSync(hookPath)) {
			console.log(".stdd/hooks/pre-push already exists — left untouched (user-owned)");
		} else {
			fs.mkdirSync(path.join(stddDir, "hooks"), { recursive: true });
			fs.writeFileSync(
				hookPath,
				"#!/bin/sh\n# user-owned after generation — append your own steps freely\n# --no: never install from the network — a hook must be fast and offline\nnpx --no stdd check . || exit 1\n",
				{ mode: 0o755 },
			);
			console.log(
				"Installed .stdd/hooks/pre-push (runs stdd check — fast, offline). Wire it up with ONE of:\n" +
					"  git config core.hooksPath .stdd/hooks   # note: this disables hooks in .git/hooks\n" +
					"  …or call `stdd check` from your existing husky/lefthook pre-push",
			);
		}
	}

	if (sessionHook) installSessionHook(targetDir);

	// The ledger and the plan are per-checkout working artifacts — never
	// committed. The ignore rules are user-owned once written, not manifested.
	const gitignorePath = path.join(targetDir, ".gitignore");
	const gitignore = fs.existsSync(gitignorePath) ? fs.readFileSync(gitignorePath, "utf8") : "";
	const lines = gitignore.split("\n");
	const missing = [".stdd/ledger.jsonl", ".stdd/plan.md"].filter((l) => !lines.includes(l));
	if (missing.length > 0) {
		const sep = gitignore === "" || gitignore.endsWith("\n") ? "" : "\n";
		fs.writeFileSync(gitignorePath, `${gitignore}${sep}${missing.join("\n")}\n`);
		console.log(`Added ${missing.join(", ")} to .gitignore (per-checkout, never committed)`);
	}

	const manifest = { generatedBy: "stdd", version: VERSION, files: generated };
	fs.writeFileSync(path.join(stddDir, "manifest.json"), `${JSON.stringify(manifest, null, "\t")}\n`);

	// A profile or tool change may stop generating a file a previous init
	// wrote. Remove it only when still byte-identical to what init wrote —
	// a hand-edited file is never deleted.
	for (const [file, hash] of Object.entries(oldFiles)) {
		if (file in generated) continue;
		const filePath = path.join(targetDir, ...file.split("/"));
		if (fs.existsSync(filePath) && sha256(fs.readFileSync(filePath, "utf8")) === hash) {
			fs.rmSync(filePath);
			console.log(`Removed ${file} (no longer generated by this profile)`);
		}
	}
}

/**
 * Shared repository scan for `check` and `doctor`: committed working
 * artifacts, canonical docs and their temporal-narrative hits, and stale
 * generated files (a stale stamp means the CLI was upgraded without
 * re-running `stdd init`).
 */
function scanRepo(targetDir, config) {
	const files = listTrackedFiles(targetDir);

	const forbidden = config.forbiddenArtifacts.map(globToRegExp);
	const artifacts = files.filter((file) => forbidden.some((re) => re.test(file)));

	const canonical = config.canonicalDocs.map(globToRegExp);
	const canonicalFiles = files.filter((file) => canonical.some((re) => re.test(file)));
	const matchers = temporalMatchers(config.temporalPhrases);
	const temporal = [];
	for (const file of canonicalFiles) {
		const lines = fs.readFileSync(path.join(targetDir, file), "utf8").split("\n");
		for (const hit of scanTemporal(lines, matchers)) temporal.push({ file, ...hit });
	}

	const contentHits = [];
	let added = null;
	if (config.contentRules.some((r) => r.newFilesOnly)) {
		added = addedFiles(targetDir, config.baseRef);
	}
	for (const rule of config.contentRules) {
		const fileRe = globToRegExp(rule.files);
		let targets = files.filter((f) => fileRe.test(f));
		if (rule.newFilesOnly && added !== null) {
			targets = targets.filter((f) => added.includes(f));
		}
		for (const file of targets) {
			const content = fs.readFileSync(path.join(targetDir, file), "utf8");
			if (rule.forbid) {
				const re = new RegExp(rule.forbid);
				content.split("\n").forEach((line, i) => {
					if (re.test(line)) contentHits.push({ file, line: i + 1, rule });
				});
			}
			if (rule.require && !new RegExp(rule.require, "m").test(content)) {
				contentHits.push({ file, line: null, rule });
			}
		}
	}

	return {
		artifacts,
		bookkeeping: trackedBookkeeping(targetDir),
		canonicalFiles,
		temporal,
		contentHits,
		stale: scanGeneratedDrift(targetDir),
	};
}

/**
 * stdd's own per-checkout bookkeeping (the ledger, the plan) that git
 * tracks anyway. Hardcoded, not config-driven — these files are never
 * legitimate in history. Outside a git repo tracking is unknowable: [].
 */
function trackedBookkeeping(targetDir) {
	try {
		return execFileSync(
			"git",
			["-C", targetDir, "ls-files", "--", ".stdd/ledger.jsonl", ".stdd/plan.md"],
			{ encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
		)
			.split("\n")
			.filter(Boolean);
	} catch {
		return [];
	}
}

/** Files added against baseRef, or null when the base is unresolvable. */
function addedFiles(targetDir, baseRef) {
	if (!baseRef) return null;
	try {
		return execFileSync(
			"git",
			["-C", targetDir, "diff", "--diff-filter=A", "--name-only", `${baseRef}...HEAD`],
			{ encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
		)
			.split("\n")
			.filter(Boolean);
	} catch {
		return null;
	}
}

/**
 * Generated-file drift, as `{ file, message }` findings. With a manifest
 * (written by `stdd init`), every generated file is verified by content
 * hash. Without one (repo initialized by an older stdd), fall back to the
 * version stamp inside Claude skills.
 */
function scanGeneratedDrift(targetDir) {
	const stale = [];
	const manifestPath = path.join(targetDir, ".stdd", "manifest.json");
	if (fs.existsSync(manifestPath)) {
		let manifest;
		try {
			manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
		} catch {
			return [{ file: ".stdd/manifest.json", message: "is not valid JSON — re-run stdd init" }];
		}
		if (manifest.version !== VERSION) {
			stale.push({
				file: ".stdd/manifest.json",
				message: `written by stdd v${manifest.version}, CLI is v${VERSION} — re-run stdd init`,
			});
		}
		for (const [file, hash] of Object.entries(manifest.files ?? {})) {
			const filePath = path.join(targetDir, ...file.split("/"));
			if (!fs.existsSync(filePath)) {
				stale.push({ file, message: "listed in .stdd/manifest.json but missing — re-run stdd init" });
			} else if (sha256(fs.readFileSync(filePath, "utf8")) !== hash) {
				stale.push({ file, message: "edited by hand or stale — re-run stdd init" });
			}
		}
		return stale;
	}

	const stampRe = /generated by stdd v([0-9][^\s]*) —/;
	const skillsDir = path.join(targetDir, ".claude", "skills");
	if (fs.existsSync(skillsDir)) {
		for (const name of fs.readdirSync(skillsDir)) {
			const skillPath = path.join(skillsDir, name, "SKILL.md");
			if (!fs.existsSync(skillPath)) continue;
			const m = stampRe.exec(fs.readFileSync(skillPath, "utf8"));
			if (m && m[1] !== VERSION) {
				stale.push({
					file: `.claude/skills/${name}/SKILL.md`,
					message: `generated by stdd v${m[1]}, CLI is v${VERSION} — re-run stdd init`,
				});
			}
		}
	}
	return stale;
}

function check(targetDir) {
	const config = loadConfig(targetDir);
	const { artifacts, bookkeeping, temporal, contentHits, stale } = scanRepo(targetDir, config);
	const violations = [
		...artifacts.map((file) => `${file}: committed working artifact (forbiddenArtifacts)`),
		...bookkeeping.map(
			(file) => `${file}: committed stdd working artifact — per-checkout only; add it to .gitignore`,
		),
		...temporal.map(
			(hit) => `${hit.file}:${hit.line}: temporal narrative in canonical doc ("${hit.phrase}")`,
		),
		...contentHits.map(
			(h) =>
				`${h.file}${h.line ? `:${h.line}` : ""}: ${h.rule.name}` +
				(h.rule.message ? ` — ${h.rule.message}` : h.line ? "" : " — required pattern not found"),
		),
		...stale.map((s) => `${s.file}: ${s.message}`),
	];
	// Enforced locally (the pre-push hook runs stdd check); a detached
	// checkout — CI — has no branch name to validate and skips the rule.
	if (config.branchPattern) {
		const branch = currentBranch(targetDir);
		if (branch && branch !== "HEAD" && !new RegExp(config.branchPattern).test(branch)) {
			violations.push(`branch "${branch}" does not match branchPattern ${config.branchPattern}`);
		}
	}

	if (violations.length > 0) {
		console.error(`stdd check: ${violations.length} violation(s)\n`);
		for (const v of violations) console.error(`  ${v}`);
		process.exit(1);
	}
	console.log("stdd check: OK");
}

/**
 * Config-declared worktree readiness: report each missing required path
 * with its repo-authored fix hint. Purely declarative — existence only,
 * nothing is executed or installed. Returns true when everything passes.
 */
function reportReadiness(targetDir, config, report) {
	const required = config.readiness.required;
	if (required.length === 0) return null;
	const missing = required.filter(
		(entry) => !fs.existsSync(path.join(targetDir, ...entry.path.split("/"))),
	);
	for (const entry of missing) {
		report(false, `${entry.path} missing${entry.hint ? ` — ${entry.hint}` : ""}`);
	}
	if (missing.length === 0) {
		report(true, `worktree ready (${required.length}/${required.length} present)`);
	}
	return missing.length === 0;
}

function doctor(targetDir, readinessOnly = false) {
	const count = (n, singular, plural) => `${n} ${n === 1 ? singular : plural}`;
	let failed = false;
	const report = (ok, message) => {
		console.log(`${ok ? "✓" : "✗"} ${message}`);
		if (!ok) failed = true;
	};

	if (readinessOnly) {
		if (reportReadiness(targetDir, loadConfig(targetDir), report) === null) {
			console.log("no readiness contract declared (readiness.required in .stdd/config.json)");
		}
		if (failed) process.exit(1);
		return;
	}

	const installed = fs.existsSync(path.join(targetDir, ".stdd", "method.md"));
	report(installed, installed ? ".stdd/ installed" : ".stdd/ is not installed — run stdd init");

	const config = loadConfig(targetDir);
	reportReadiness(targetDir, config, report);
	const { artifacts, bookkeeping, canonicalFiles, temporal, contentHits, stale } = scanRepo(
		targetDir,
		config,
	);

	if (config.contentRules.length > 0) {
		report(
			contentHits.length === 0,
			contentHits.length === 0
				? `content rules clean (${count(config.contentRules.length, "rule", "rules")})`
				: `${count(contentHits.length, "content-rule violation", "content-rule violations")} — see stdd check`,
		);
	}

	report(
		canonicalFiles.length > 0,
		canonicalFiles.length > 0
			? `canonical docs present (${count(canonicalFiles.length, "file", "files")})`
			: "no canonical docs found — create docs/domain/ or docs/product/, or adjust canonicalDocs",
	);

	const committed = artifacts.length + bookkeeping.length;
	report(
		committed === 0,
		committed === 0
			? "no committed working artifacts"
			: `${count(committed, "committed working artifact", "committed working artifacts")} may mislead coding agents`,
	);

	const temporalFiles = new Set(temporal.map((hit) => hit.file)).size;
	report(
		temporalFiles === 0,
		temporalFiles === 0
			? "canonical docs describe the present (no temporal narrative)"
			: `${count(temporalFiles, "canonical doc contains", "canonical docs contain")} temporal narrative`,
	);

	report(
		stale.length === 0,
		stale.length === 0
			? `generated files match stdd v${VERSION}`
			: `${count(stale.length, "generated file is", "generated files are")} stale — re-run stdd init`,
	);

	// informational only — a missing hook is a choice, never a failure
	const hookInstalled = fs.existsSync(path.join(targetDir, ".stdd", "hooks", "pre-push"));
	console.log(
		hookInstalled
			? "· pre-push hook installed (.stdd/hooks/pre-push) — wire via git config core.hooksPath .stdd/hooks"
			: "· no pre-push hook installed — optional: stdd init --hooks",
	);

	const agentsPath = path.join(targetDir, "AGENTS.md");
	if (fs.existsSync(agentsPath)) {
		const hasSection = /^## STDD$/m.test(fs.readFileSync(agentsPath, "utf8"));
		report(
			hasSection,
			hasSection
				? "AGENTS.md carries the STDD section"
				: "AGENTS.md has no STDD section — run `stdd init --tools codex` to write it",
		);
	}

	const workflowsDir = path.join(targetDir, ".github", "workflows");
	if (fs.existsSync(workflowsDir)) {
		for (const file of fs.readdirSync(workflowsDir).filter((f) => /\.ya?ml$/.test(f))) {
			if (workflowValidatesStaleBody(fs.readFileSync(path.join(workflowsDir, file), "utf8"))) {
				report(
					false,
					`.github/workflows/${file} validates the frozen event payload body — ` +
						"body edits will not be re-checked; see stdd init --ci github",
				);
			}
		}
	}

	for (const rel of [
		"pull_request_template.md",
		".github/pull_request_template.md",
		"docs/pull_request_template.md",
	]) {
		const tplPath = path.join(targetDir, ...rel.split("/"));
		if (!fs.existsSync(tplPath)) continue;
		if (findEvidenceLines(fs.readFileSync(tplPath, "utf8")).length > 0) {
			report(
				false,
				`${rel} carries an unquoted evidence label — placeholder residue would pass ` +
					'the gate on every PR; quote template instructions ("> Docs …")',
			);
		}
	}

	if (failed) process.exit(1);
}

/** Run git in the working directory, returning trimmed stdout; throws on failure. */
function git(...args) {
	return execFileSync("git", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
}

/**
 * With --pr: fetch the live PR (body, base, head) from the forge, so the
 * validation matches what CI will see — never a diverged local checkout.
 * Returns `{ body, baseRef, headRef, number }`.
 */
function resolveLivePr(pr) {
	const args = [
		"pr",
		"view",
		...(pr === "." ? [] : [pr]),
		"--json",
		"body,baseRefName,headRefOid,number",
	];
	let info;
	try {
		info = JSON.parse(execFileSync("gh", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }));
	} catch (err) {
		if (err.code === "ENOENT") fail("--pr needs the GitHub CLI (gh) on PATH");
		fail(`gh pr view failed: ${err.stderr?.toString().trim().split("\n")[0] || err.message}`);
	}
	const baseRef = `origin/${info.baseRefName}`;
	try {
		git("fetch", "-q", "origin", info.baseRefName);
	} catch (err) {
		fail(
			`could not fetch origin/${info.baseRefName}: ${err.stderr?.toString().trim().split("\n")[0] || err.message}`,
		);
	}
	let headRef = "HEAD";
	if (git("rev-parse", "HEAD") !== info.headRefOid) {
		try {
			git("cat-file", "-e", `${info.headRefOid}^{commit}`);
		} catch {
			try {
				git("fetch", "-q", "origin", `pull/${info.number}/head`);
				git("cat-file", "-e", `${info.headRefOid}^{commit}`);
			} catch {
				fail(
					`local HEAD differs from PR head ${info.headRefOid.slice(0, 7)} and it could not ` +
						"be fetched — push or check out the PR branch",
				);
			}
		}
		headRef = info.headRefOid;
	}
	return { body: info.body, baseRef, headRef, number: info.number };
}

// --- the session ledger (see method: "The session ledger and stdd status") ---

const LEDGER_REL = ".stdd/ledger.jsonl";
const PLAN_REL = ".stdd/plan.md";

/**
 * The ledger and config anchor to the repository, never the shell's cwd —
 * a recorder run from a subdirectory must not create a nested `.stdd/`.
 * Resolution: the git toplevel when it holds `.stdd/` (or when none exists
 * yet), otherwise the nearest ancestor holding `.stdd/`. Outside a git
 * repo the cwd is returned unchanged — recorders require git anyway.
 */
function resolveRepoDir(cwd) {
	let top;
	try {
		top = execFileSync("git", ["-C", cwd, "rev-parse", "--show-toplevel"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch {
		return cwd;
	}
	if (fs.existsSync(path.join(top, ".stdd"))) return top;
	let dir = path.resolve(cwd);
	while (dir !== top && path.dirname(dir) !== dir) {
		if (fs.existsSync(path.join(dir, ".stdd"))) return dir;
		dir = path.dirname(dir);
	}
	return top;
}
const DOCS_DECISIONS = ["updated-first", "checked", "not-applicable"];
const LABEL_TO_DECISION = {
	"Docs updated first": "updated-first",
	"Docs checked, no change needed": "checked",
	"Docs not applicable": "not-applicable",
};
const EXCERPT_LIMIT = 2000;

/** Current branch name, or null outside a git repo (soft — callers decide). */
function currentBranch(cwd) {
	try {
		return execFileSync("git", ["-C", cwd, "rev-parse", "--abbrev-ref", "HEAD"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		}).trim();
	} catch {
		return null;
	}
}

function requireBranch(cwd) {
	const branch = currentBranch(cwd);
	if (!branch) fail("the ledger needs a git repository with at least one commit");
	return branch;
}

function appendLedger(cwd, event) {
	const branch = requireBranch(cwd);
	fs.mkdirSync(path.join(cwd, ".stdd"), { recursive: true });
	fs.appendFileSync(
		path.join(cwd, LEDGER_REL),
		`${JSON.stringify({ ts: new Date().toISOString(), branch, ...event })}\n`,
	);
}

/** Current branch's ledger events, in append order. [] without a ledger. */
function loadLedger(cwd, branch) {
	const ledgerPath = path.join(cwd, LEDGER_REL);
	if (!fs.existsSync(ledgerPath)) return [];
	return parseLedger(fs.readFileSync(ledgerPath, "utf8")).filter((e) => e.branch === branch);
}

/** `stdd docs <decision> [paths…] [--reason <why>]` — record the docs decision. */
function recordDocs(cwd, decision, paths, reason) {
	if (!DOCS_DECISIONS.includes(decision)) {
		// Free text is the recurring mistake — answer with the exact forms
		// and, when a decision word is buried in the prose, the corrected call.
		const joined = [decision ?? "", ...paths].join(" ");
		const stem = /not[- ]applicable/i.test(joined)
			? "not-applicable"
			: /updated[- ]first/i.test(joined)
				? "updated-first"
				: /\bchecked\b/i.test(joined)
					? "checked"
					: null;
		fail(
			`unknown docs decision "${decision ?? ""}" — the decision is one word, then its arguments:\n` +
				"  stdd docs updated-first <paths…>\n" +
				"  stdd docs checked <paths…> --reason <why>\n" +
				"  stdd docs not-applicable --reason <why>" +
				(stem ? `\ndid you mean: stdd docs ${stem} …` : ""),
		);
	}
	if (decision === "not-applicable") {
		if (paths.length > 0) {
			fail(
				"not-applicable takes no paths — put the why into --reason:\n" +
					'  stdd docs not-applicable --reason "<why implementation-only>"',
			);
		}
		if (!reason) fail("not-applicable needs --reason <why implementation-only>");
	} else if (paths.length === 0) {
		fail(`${decision} needs at least one docs path`);
	}
	if (decision === "checked" && !reason) {
		fail("checked needs --reason <why no change is needed>");
	}
	appendLedger(cwd, { event: "docs", decision, paths, ...(reason ? { reason } : {}) });
	console.log(`stdd docs: recorded ${decision}${paths.length ? ` (${paths.join(", ")})` : ""}`);
}

/**
 * `stdd red|verify -- <cmd>` — run the command, record {cmd, exit, excerpt}
 * verbatim, pass the exit code through. Output flows to the caller unchanged.
 */
function recordRun(cwd, kind, argv) {
	// A single whitespace-carrying word after -- is a description, not a
	// command — it can never spawn. Reject with the corrected form and
	// record nothing: prose in the ledger verifies nothing.
	if (argv.length === 1 && /\s/.test(argv[0])) {
		fail(
			`${kind} takes the command and its arguments, never prose — nothing was recorded\n` +
				`  e.g.:             stdd ${kind} -- pnpm --filter api test\n` +
				`  shell constructs: stdd ${kind} -- sh -c "<cmd>"`,
		);
	}
	const config = loadConfig(cwd);
	const result = spawnSync(argv[0], argv.slice(1), { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 });
	let exit = result.status ?? 1;
	let output = `${result.stdout ?? ""}${result.stderr ?? ""}`;
	if (result.error) {
		exit = 127;
		output += `${result.error.message}\n`;
	}
	if (result.stdout) process.stdout.write(result.stdout);
	if (result.stderr) process.stderr.write(result.stderr);
	if (result.error) {
		console.error(
			`stdd ${kind}: ${result.error.message}` +
				(result.error.code === "ENOENT"
					? " — command not found; is the worktree ready (stdd doctor --readiness)? " +
						"Shell constructs need sh -c"
					: ""),
		);
	}

	const event = { event: kind, cmd: argv.join(" "), exit, excerpt: output.slice(-EXCERPT_LIMIT) };
	if (kind === "red") {
		event.genuine = redGenuine(exit, output, config.redPattern ?? null);
		if (exit === 0) {
			console.error('stdd red: the command exited 0 — that is green, not red (recorded genuine: "no")');
		} else if (event.genuine === "unknown") {
			console.error(
				'stdd red: no redPattern in .stdd/config.json — cannot assert genuine-red (recorded genuine: "unknown")',
			);
		} else if (event.genuine === "no") {
			console.error(
				'stdd red: output does not match redPattern — this looks like an environment error, not a genuine red (recorded genuine: "no")',
			);
		}
	}
	appendLedger(cwd, event);
	process.exit(exit);
}

/**
 * `stdd defer <text>` — record a scope cut under the plan's `## Deferred`
 * section (see method: "The durable plan and stdd defer"). Creates the
 * plan file and the section as needed; never touches git or the ledger.
 */
function defer(cwd, text) {
	const planPath = path.join(cwd, PLAN_REL);
	fs.mkdirSync(path.join(cwd, ".stdd"), { recursive: true });
	const content = fs.existsSync(planPath) ? fs.readFileSync(planPath, "utf8") : "";
	fs.writeFileSync(planPath, appendDeferred(content, text));
	console.log(
		`stdd defer: recorded under ${PLAN_REL} — carry it into the PR description's out-of-scope`,
	);
}

/**
 * Content hashes of every dirty (staged, unstaged, untracked) path.
 * Deleted paths and untracked directories hash to null — equality of
 * nulls still distinguishes inherited state from a slice's own edits.
 */
function dirtySnapshot(cwd) {
	// -z: NUL-delimited, no C-style octal quoting — a non-ASCII filename
	// must never crash the callers (review, status, gate, scope)
	// --untracked-files=all: a wholly untracked directory must list every
	// file inside it, or edits there would never change the snapshot
	const out = execFileSync("git", ["-C", cwd, "status", "--porcelain", "-z", "--untracked-files=all"], {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	});
	const dirty = {};
	const tokens = out.split("\0");
	for (let i = 0; i < tokens.length; i++) {
		const entry = tokens[i];
		if (!entry) continue;
		const xy = entry.slice(0, 2);
		const p = entry.slice(3);
		// a rename/copy entry is followed by the origin path token — the
		// current path is what the snapshot tracks
		if (/[RC]/.test(xy)) i++;
		const abs = path.join(cwd, ...p.split("/"));
		// lstat: a symlink is fingerprinted by its target PATH — the repo
		// change is the link itself, and following it would pull files from
		// outside the repository into the snapshot
		let st = null;
		try {
			st = p.endsWith("/") ? null : fs.lstatSync(abs);
		} catch {
			st = null;
		}
		dirty[p] = st?.isSymbolicLink()
			? sha256(`link:${fs.readlinkSync(abs)}`)
			: st?.isFile()
				? sha256(fs.readFileSync(abs)) // raw bytes — lossy text decoding collapses distinct binaries
				: null;
	}
	return dirty;
}

/**
 * `stdd slice new` — declare a delegated slice's scope and snapshot the
 * checkout baseline (head + dirty-file hashes) into a ledger scope event.
 */
function sliceNew(cwd, frozenPaths, allowedPaths) {
	if (frozenPaths.length === 0 && allowedPaths.length === 0) {
		fail("slice new needs a scope — pass --frozen <globs> and/or --allowed <globs>");
	}
	requireBranch(cwd);
	const head = execFileSync("git", ["-C", cwd, "rev-parse", "HEAD"], {
		encoding: "utf8",
		stdio: ["ignore", "pipe", "pipe"],
	}).trim();
	appendLedger(cwd, {
		event: "scope",
		frozenPaths,
		allowedPaths,
		baseline: { head, dirty: dirtySnapshot(cwd) },
	});
	console.log(
		`stdd slice: scope declared (frozen: ${frozenPaths.join(", ") || "—"}; ` +
			`allowed: ${allowedPaths.join(", ") || "—"}) — baseline at ${head.slice(0, 7)}`,
	);
}

/**
 * `stdd scope` — postflight against the slice baseline, not a ref. Only
 * session-introduced changes count; inherited dirt (already modified at
 * baseline, byte-identical now) is reported separately, never blamed.
 */
function scopeCheck(cwd) {
	const branch = requireBranch(cwd);
	const scope = loadLedger(cwd, branch)
		.filter((e) => e.event === "scope")
		.at(-1);
	if (!scope) {
		fail("no slice declared for this branch — run `stdd slice new --frozen/--allowed` first");
	}
	let committed;
	try {
		committed = execFileSync("git", ["-C", cwd, "diff", "--name-only", scope.baseline.head, "HEAD"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		})
			.split("\n")
			.filter(Boolean);
	} catch {
		fail(`baseline commit ${scope.baseline.head.slice(0, 7)} is gone — cannot diff the slice`);
	}
	const introduced = new Set(committed);
	const inherited = [];
	for (const [p, hash] of Object.entries(dirtySnapshot(cwd))) {
		if (p in scope.baseline.dirty && scope.baseline.dirty[p] === hash) inherited.push(p);
		else introduced.add(p);
	}
	// stdd's own bookkeeping (the ledger grows during the slice by design;
	// porcelain may report the whole untracked .stdd/ dir) is never in scope
	for (const p of introduced) {
		if (p === ".stdd/" || p.startsWith(".stdd/")) introduced.delete(p);
	}
	const frozen = scope.frozenPaths.map(globToRegExp);
	const allowed = scope.allowedPaths.map(globToRegExp);
	const violations = [];
	for (const p of introduced) {
		if (frozen.some((re) => re.test(p))) {
			violations.push(`${p}: frozen path modified by this slice`);
		} else if (allowed.length > 0 && !allowed.some((re) => re.test(p))) {
			violations.push(`${p}: outside the allowed paths`);
		}
	}
	for (const p of inherited) {
		console.log(`inherited dirt (present at baseline, not introduced by this slice): ${p}`);
	}
	if (violations.length > 0) {
		console.error(`stdd scope: ${violations.length} violation(s)\n`);
		for (const v of violations) console.error(`  ${v}`);
		process.exit(1);
	}
	console.log(`stdd scope: OK (${introduced.size} introduced change(s), all in scope)`);
}

// --- the closing review: stdd review ---

const REVIEW_VIAS = ["subagent", "codex"];

/**
 * Hash of the work under review: the diff against baseRef plus the
 * dirty-file state, `.stdd/` excluded — the ledger and the plan are
 * working artifacts, never the subject of the review, and recording the
 * review itself must not invalidate it.
 */
/**
 * The diff under review. `strict` aborts on an unresolvable base — a
 * review of an unavailable diff proves nothing and must not be recordable;
 * status/gate callers stay tolerant and get a placeholder instead.
 */
// Only the WORKING artifacts are exempt from review evidence — recording
// events must never invalidate a review. Tracked .stdd/ deliverables
// (config, generated kit) stay under review like any other file.
const REVIEW_EXEMPT = [".stdd/ledger.jsonl", ".stdd/plan.md"];

function reviewDiff(cwd, baseRef, strict) {
	try {
		return execFileSync(
			"git",
			["-C", cwd, "diff", baseRef, "--", ".", ...REVIEW_EXEMPT.map((p) => `:(exclude)${p}`)],
			{
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
				maxBuffer: 64 * 1024 * 1024,
			},
		);
	} catch {
		if (strict) {
			fail(
				`cannot diff against "${baseRef}" — fetch the base ref or fix "baseRef" in .stdd/config.json`,
			);
		}
		return "(unresolvable base)";
	}
}

/**
 * The plan as snapshot material: checkbox marks are normalized away —
 * they are claims graded by the ledger, and the auto-checked [review:]
 * box must not invalidate the approval that checked it. Editing the
 * plan's words DOES stale a review: the verdict is a comparison against
 * exactly that specification.
 */
function normalizedPlan(cwd) {
	const planPath = path.join(cwd, PLAN_REL);
	if (!fs.existsSync(planPath)) return "(no plan file)";
	return fs.readFileSync(planPath, "utf8").replace(/^(\s*[-*+]\s+)\[[ xX]\]/gm, "$1[ ]");
}

function reviewSnapshot(cwd, baseRef, strict = false) {
	const diff = reviewDiff(cwd, baseRef, strict);
	const dirty = dirtySnapshot(cwd);
	for (const p of REVIEW_EXEMPT) delete dirty[p];
	return sha256(`${diff}\n${JSON.stringify(dirty)}\n${normalizedPlan(cwd)}`);
}

function buildReviewBrief(cwd, config) {
	const planPath = path.join(cwd, PLAN_REL);
	const plan = fs.existsSync(planPath) ? fs.readFileSync(planPath, "utf8") : "(no plan file)";
	let diff = reviewDiff(cwd, config.baseRef, true);
	// the manifest never truncates: even when the diff body is cut, every
	// changed file is at least named to the reviewer
	let manifest;
	try {
		manifest = execFileSync(
			"git",
			[
				"-C",
				cwd,
				"diff",
				"--name-status",
				config.baseRef,
				"--",
				".",
				...REVIEW_EXEMPT.map((p) => `:(exclude)${p}`),
			],
			{ encoding: "utf8", stdio: ["ignore", "pipe", "pipe"], maxBuffer: 64 * 1024 * 1024 },
		);
	} catch {
		manifest = "(unavailable)";
	}
	// a new file is part of the change even before `git add` — the diff
	// alone would let untracked work sail through unreviewed
	let untrackedSection = "";
	try {
		// -z: newline parsing would receive C-quoted non-paths for non-ASCII
		// names and silently drop those files from the brief
		const untracked = execFileSync(
			"git",
			["-C", cwd, "ls-files", "--others", "--exclude-standard", "-z"],
			{
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			},
		)
			.split("\0")
			.filter((p) => p && !REVIEW_EXEMPT.includes(p));
		const MAX_FILE = 40_000;
		let budget = 200_000;
		for (const p of untracked) {
			const abs = path.join(cwd, ...p.split("/"));
			let st;
			try {
				st = fs.lstatSync(abs);
			} catch {
				continue;
			}
			// symlinks are skipped — an untracked link must not copy files
			// from outside the repository into the reviewer's prompt
			if (!st.isFile()) continue;
			// bounded read: never pull a large file into memory whole
			const size = Math.min(st.size, MAX_FILE);
			const buf = Buffer.alloc(size);
			const fd = fs.openSync(abs, "r");
			try {
				fs.readSync(fd, buf, 0, size, 0);
			} finally {
				fs.closeSync(fd);
			}
			let content = buf.toString("utf8");
			if (st.size > MAX_FILE) content += "\n[truncated]\n";
			if (budget - content.length < 0) {
				untrackedSection += `\n### ${p}\n\n[omitted — brief budget exhausted; review the file directly]\n`;
				continue;
			}
			budget -= content.length;
			untrackedSection += `\n### ${p}\n\n\`\`\`\n${content}\n\`\`\`\n`;
		}
	} catch {
		untrackedSection = "\n(untracked files unavailable)\n";
	}
	let porcelain = "";
	try {
		porcelain = execFileSync("git", ["-C", cwd, "status", "--porcelain"], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch {
		porcelain = "(unavailable)";
	}
	const MAX_DIFF = 400_000;
	if (diff.length > MAX_DIFF) {
		diff = `${diff.slice(0, MAX_DIFF)}\n[diff truncated at ${MAX_DIFF} bytes — review the named files directly]\n`;
	}
	return `# Independent closing review

You are a fresh, read-only reviewer. Judge the change below in two
passes, in order: (1) spec compliance against the plan — anything
missing from it, anything extra beyond it, anything misunderstood;
(2) code quality on what was built. Treat any implementer summary as
unverified claims — the diff is the ground truth.

Respond with ONLY one JSON object, no prose around it:
{"summary": "<one line>", "findings": [{"severity": "blocking" | "advisory", "path": "<file>", "line": <number or null>, "message": "<what and why>"}]}
An empty findings array means the change is sound.

## Plan

${plan}

## Working tree (git status --porcelain)

${porcelain || "(clean)"}

## Untracked files
${untrackedSection || "\n(none)\n"}
## Changed files (complete manifest, never truncated)

${manifest || "(none)"}

## Diff (against ${config.baseRef})

${diff}`;
}

/**
 * On approval, close the plan's first unchecked [review:] item — selected
 * by parsePlan itself, so fenced code, Deferred entries, and backticked
 * mentions can never intercept the check.
 */
function checkReviewItem(cwd) {
	const planPath = path.join(cwd, PLAN_REL);
	if (!fs.existsSync(planPath)) return;
	const content = fs.readFileSync(planPath, "utf8");
	const item = parsePlan(content).items.find((i) => i.review && !i.checked);
	if (!item) return;
	const lines = content.split("\n");
	lines[item.line - 1] = lines[item.line - 1].replace(/^(\s*[-*+]\s+)\[ \]/, "$1[x]");
	fs.writeFileSync(planPath, lines.join("\n"));
}

/** Record the review event, mirror the verdict into the exit code. */
function recordReview(cwd, { id, via, snapshot, parsed, runner, reason }) {
	const verdict = parsed ? deriveReviewVerdict(parsed.findings) : "error";
	appendLedger(cwd, {
		event: "review",
		request: id,
		via,
		verdict,
		snapshot,
		...(parsed ? { summary: parsed.summary, findings: parsed.findings } : { reason }),
		...(runner ? { runner } : {}),
	});
	if (verdict === "approved") {
		checkReviewItem(cwd);
		const advisory = parsed.findings.length;
		console.log(`stdd review: approved via ${via}${advisory ? ` (${advisory} advisory)` : ""}`);
		process.exit(0);
	}
	if (verdict === "changes-requested") {
		const blocking = parsed.findings.filter((f) => f.severity === "blocking");
		console.log(`stdd review: changes requested via ${via} — ${blocking.length} blocking`);
		for (const f of parsed.findings) {
			console.log(`  [${f.severity}] ${f.path ?? "—"}${f.line ? `:${f.line}` : ""} — ${f.message}`);
		}
		console.log("fix the findings, then run `stdd review` again — the newest verdict controls");
		process.exit(1);
	}
	console.error(`stdd review: error — ${reason}`);
	process.exit(2);
}

/** `stdd review --result <file|->` — grade a result against the open request. */
function reviewSubmit(cwd, config, resultArg) {
	const events = loadLedger(cwd, requireBranch(cwd));
	const lastRequest = events.filter((e) => e.event === "review-request").at(-1) ?? null;
	const answered = new Set(events.filter((e) => e.event === "review").map((e) => e.request));
	if (!lastRequest || answered.has(lastRequest.id)) {
		fail("no open review request — run `stdd review` first");
	}
	// a codex request is answered by its own runner and nothing else — a
	// hand-fed file must not forge codex provenance
	if (lastRequest.via !== "subagent") {
		fail(
			`the open request was dispatched via ${lastRequest.via} — its runner records the verdict; rerun \`stdd review\` for a fresh dispatch`,
		);
	}
	let text;
	try {
		text = resultArg === "-" ? fs.readFileSync(0, "utf8") : fs.readFileSync(resultArg, "utf8");
	} catch (err) {
		fail(`cannot read the result: ${err.message}`);
	}
	const snapshot = reviewSnapshot(cwd, config.baseRef, true);
	if (snapshot !== lastRequest.snapshot) {
		recordReview(cwd, {
			id: lastRequest.id,
			via: lastRequest.via,
			snapshot,
			parsed: null,
			runner: null,
			reason: "stale: the checkout changed since the request — run `stdd review` again",
		});
	}
	const parsed = parseReviewResult(text);
	recordReview(cwd, {
		id: lastRequest.id,
		via: lastRequest.via,
		snapshot,
		parsed,
		runner: null,
		reason: parsed ? null : "malformed reviewer output — expected the documented JSON object",
	});
}

/** `stdd review [--via subagent|codex] [--timeout <s>]` — run the closing review. */
function reviewRun(cwd, viaArg, timeoutSec) {
	const config = loadConfig(cwd);
	const via = viaArg ?? config.review.via;
	if (!REVIEW_VIAS.includes(via)) {
		fail(`unknown review route "${via}" (known: ${REVIEW_VIAS.join(", ")})`);
	}
	// an unavailable route is an error, never a silent fall-back to
	// self-review
	if (via === "codex" && !config.capabilities.crossCli) {
		fail(
			"review via codex needs the crossCli capability — enable it in .stdd/config.json (capabilities.crossCli) or use --via subagent",
		);
	}
	if (via === "subagent" && !config.capabilities.subagents) {
		fail(
			"review via subagent needs the subagents capability — enable it in .stdd/config.json (capabilities.subagents) or use --via codex",
		);
	}
	const dispatchBranch = requireBranch(cwd);
	const snapshot = reviewSnapshot(cwd, config.baseRef, true);
	const brief = buildReviewBrief(cwd, config);
	// random, not derived: two requests in the same millisecond over the
	// same snapshot must never share an id
	const id = `rev-${randomBytes(4).toString("hex")}`;
	// the brief can carry source contents: private temp dir (0700), file
	// 0600 — never world-readable under a default umask
	const briefDir = fs.mkdtempSync(path.join(os.tmpdir(), "stdd-review-"));
	const briefPath = path.join(briefDir, `${id}.md`);
	fs.writeFileSync(briefPath, brief, { mode: 0o600 });
	appendLedger(cwd, {
		event: "review-request",
		id,
		via,
		snapshot,
		brief: sha256(brief),
	});
	if (via === "subagent") {
		console.log(`stdd review: brief written to ${briefPath}`);
		console.log("dispatch a fresh READ-ONLY reviewer with that file — never this session's history —");
		console.log("then record its JSON result: stdd review --result <file|->");
		process.exit(0);
	}
	const bin = process.env.STDD_CODEX_BIN || "codex";
	const outPath = path.join(briefDir, "last-message.txt");
	console.log(`stdd review: dispatching ${bin} exec --sandbox read-only (timeout ${timeoutSec}s)…`);
	// the brief travels over stdin (prompt arg "-"): one argv element caps
	// out around 128 KB on Linux, and stdin closes at EOF — codex never
	// hangs on "Reading additional input from stdin..."
	const spawn = spawnSync(
		bin,
		["exec", "--sandbox", "read-only", "--output-last-message", outPath, "-"],
		{
			cwd,
			encoding: "utf8",
			input: brief,
			timeout: timeoutSec * 1000,
			maxBuffer: 64 * 1024 * 1024,
		},
	);
	const runnerFailed = Boolean(spawn.error) || spawn.status !== 0;
	const last = fs.existsSync(outPath) ? fs.readFileSync(outPath, "utf8") : (spawn.stdout ?? "");
	fs.rmSync(briefDir, { recursive: true, force: true });
	// the ledger is branch-scoped: a checkout that switched branches while
	// the reviewer ran would record the verdict on the wrong branch —
	// record nothing; the request stays open on the original branch
	if (requireBranch(cwd) !== dispatchBranch) {
		fail(
			`the checkout switched branches while the reviewer ran — nothing recorded; rerun \`stdd review\` on ${dispatchBranch}`,
		);
	}
	// the runner may take minutes — an approval only counts for the diff
	// the reviewer actually saw, so the snapshot is recomputed on return
	const after = reviewSnapshot(cwd, config.baseRef, true);
	const wentStale = !runnerFailed && after !== snapshot;
	const parsed = runnerFailed || wentStale ? null : parseReviewResult(last);
	recordReview(cwd, {
		id,
		via,
		snapshot: after,
		parsed,
		runner: {
			command: `${bin} exec`,
			exit: spawn.status,
			...(spawn.error
				? { error: spawn.error.code === "ETIMEDOUT" ? "timeout" : String(spawn.error.message) }
				: {}),
		},
		reason: runnerFailed
			? spawn.error?.code === "ETIMEDOUT"
				? `the reviewer timed out after ${timeoutSec}s`
				: `the reviewer process failed (exit ${spawn.status ?? "—"})`
			: wentStale
				? "stale: the checkout changed while the reviewer ran — run `stdd review` again"
				: parsed
					? null
					: "malformed reviewer output — expected the documented JSON object",
	});
}

/**
 * The branch's PR as `stdd status` reports it. Degrades, never errors:
 * no gh on PATH or an unexpected gh failure → state "unknown".
 */
function statusPr(cwd) {
	let raw;
	try {
		raw = execFileSync("gh", ["pr", "view", "--json", "number,url,statusCheckRollup"], {
			cwd,
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		});
	} catch (err) {
		if (err.code === "ENOENT") return { state: "unknown", reason: "gh unavailable" };
		const stderr = err.stderr?.toString() ?? "";
		if (/no pull requests found/i.test(stderr)) return { state: "none" };
		return { state: "unknown", reason: stderr.trim().split("\n")[0] || "gh failed" };
	}
	let info;
	try {
		info = JSON.parse(raw);
	} catch {
		return { state: "unknown", reason: "gh returned unparseable output" };
	}
	const checks = { success: 0, failure: 0, pending: 0 };
	for (const check of info.statusCheckRollup ?? []) {
		const conclusion = (check.conclusion ?? "").toUpperCase();
		if (conclusion === "SUCCESS" || conclusion === "NEUTRAL" || conclusion === "SKIPPED") {
			checks.success++;
		} else if (conclusion === "") {
			checks.pending++;
		} else {
			checks.failure++;
		}
	}
	return { state: "open", number: info.number, url: info.url, checks };
}

/** One rollup entry → { name, terminal, ok }, for check runs and statuses. */
function normalizeCheck(entry) {
	const startedAt = entry.startedAt ?? entry.createdAt ?? "";
	if (entry.state !== undefined && entry.status === undefined) {
		const state = (entry.state ?? "").toUpperCase();
		return {
			name: entry.context ?? "unknown",
			terminal: state !== "" && state !== "EXPECTED" && state !== "PENDING",
			ok: state === "SUCCESS",
			startedAt,
		};
	}
	const conclusion = (entry.conclusion ?? "").toUpperCase();
	return {
		name: entry.name ?? "unknown",
		terminal: (entry.status ?? "").toUpperCase() === "COMPLETED",
		ok: conclusion === "SUCCESS" || conclusion === "NEUTRAL" || conclusion === "SKIPPED",
		startedAt,
	};
}

/** The PR's checks for its current head, straight from the forge. */
function ghPrChecks(pr) {
	const args = ["pr", "view", ...(pr ? [pr] : []), "--json", "number,url,headRefOid,statusCheckRollup"];
	let raw;
	try {
		raw = execFileSync("gh", args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] });
	} catch (err) {
		if (err.code === "ENOENT") fail("stdd ci needs the GitHub CLI (gh) on PATH");
		const stderr = err.stderr?.toString() ?? "";
		if (/no pull requests found/i.test(stderr)) {
			fail("no PR for the current branch — open it first, then watch it settle");
		}
		fail(`gh pr view failed: ${stderr.trim().split("\n")[0] || err.message}`);
	}
	let info;
	try {
		info = JSON.parse(raw);
	} catch {
		fail("gh returned unparseable output");
	}
	return {
		number: info.number,
		url: info.url,
		head: info.headRefOid,
		checks: dedupeChecks((info.statusCheckRollup ?? []).map(normalizeCheck)),
	};
}

/**
 * `stdd ci [pr] [--watch]` — the PR's checks on its **current head**. The
 * watch settles only when the check set is stable (two consecutive polls
 * with the same names) and fully terminal: a watcher attached right after
 * a push sees a partial set — the classic early-settle trap. A terminal
 * failure exits immediately; a head move (amend, force-push) restarts the
 * watch on the new head.
 */
async function ciCommand(pr, watch, intervalSec, timeoutSec) {
	const render = (c) => `  ${c.terminal ? (c.ok ? "✓" : "✗") : "…"} ${c.name}`;
	let localHead = null;
	try {
		localHead = git("rev-parse", "HEAD");
	} catch {
		// outside a git repo gh still resolves an explicit PR number
	}
	let lastHead = null;
	let lastNames = null;
	let lastProgress = null;
	let stable = 0;
	const deadline = Date.now() + timeoutSec * 1000;
	for (;;) {
		const view = ghPrChecks(pr);
		if (view.head !== lastHead) {
			if (lastHead === null) {
				console.log(`PR #${view.number} — checks on head ${view.head.slice(0, 7)} (${view.url})`);
				if (localHead && localHead !== view.head) {
					console.error(
						`stdd ci: local HEAD ${localHead.slice(0, 7)} differs from the PR head — ` +
							"watching the PR head; push if you meant your local commit",
					);
				}
			} else {
				console.log(`head moved to ${view.head.slice(0, 7)} — restarting the watch`);
			}
			lastHead = view.head;
			lastNames = null;
			stable = 0;
		}
		const failed = view.checks.filter((c) => c.terminal && !c.ok);
		const allTerminal = view.checks.every((c) => c.terminal);
		const names = view.checks
			.map((c) => c.name)
			.sort()
			.join("\n");

		if (!watch) {
			for (const c of view.checks) console.log(render(c));
			if (view.checks.length === 0) console.log("  (no checks reported)");
			if (failed.length > 0) {
				console.error(`stdd ci: ${failed.length} failing on ${view.head.slice(0, 7)}`);
				process.exit(1);
			}
			if (allTerminal && view.checks.length > 0) {
				console.log(`stdd ci: green (${view.checks.length} checks) on ${view.head.slice(0, 7)}`);
				return;
			}
			console.error(
				"stdd ci: not settled — checks pending or not yet registered; `stdd ci --watch` waits it out",
			);
			process.exit(1);
		}

		if (failed.length > 0) {
			for (const c of view.checks) console.log(render(c));
			console.error(`stdd ci: ${failed.length} failing check(s) on ${view.head.slice(0, 7)}`);
			process.exit(1);
		}
		stable = allTerminal && view.checks.length > 0 && names === lastNames ? stable + 1 : 0;
		lastNames = names;
		if (stable >= 1 && allTerminal) {
			// second consecutive all-terminal poll with an unchanged set
			for (const c of view.checks) console.log(render(c));
			console.log(
				`stdd ci: green (${view.checks.length} checks) on ${view.head.slice(0, 7)} — terminal`,
			);
			return;
		}
		const progress = `  ${view.checks.filter((c) => c.terminal).length}/${view.checks.length} terminal`;
		if (progress !== lastProgress) {
			console.log(progress);
			lastProgress = progress;
		}
		if (Date.now() > deadline) {
			const open = view.checks.filter((c) => !c.terminal).map((c) => c.name);
			fail(
				`timed out after ${timeoutSec}s — still not terminal: ` +
					(open.join(", ") || "check set still settling"),
			);
		}
		await new Promise((resolve) => setTimeout(resolve, intervalSec * 1000));
	}
}

/**
 * `stdd status` — the next-step oracle. Inputs in order of trust: git (diff
 * against the configured baseRef, dirty state), the ledger, then the forge.
 */
function status(cwd, asJson) {
	const config = loadConfig(cwd);
	const branch = requireBranch(cwd);
	const events = loadLedger(cwd, branch);

	// git: changed files = committed diff vs baseRef + dirty working tree
	let changed = null;
	if (config.baseRef) {
		try {
			const diff = execFileSync("git", ["-C", cwd, "diff", "--name-only", `${config.baseRef}...HEAD`], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			});
			const dirty = execFileSync("git", ["-C", cwd, "status", "--porcelain"], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			});
			changed = [
				...new Set([
					...diff.split("\n").filter(Boolean),
					...dirty
						.split("\n")
						.filter(Boolean)
						.map((line) => line.slice(3).trim()),
				]),
			];
		} catch {
			changed = null; // unresolvable baseRef — report unknown, never error
		}
	}
	const canonical = config.canonicalDocs.map(globToRegExp);
	const docsChanged = (changed ?? []).filter((f) => canonical.some((re) => re.test(f)));
	const nonDocChanged = (changed ?? []).filter((f) => !canonical.some((re) => re.test(f)));

	const docsEvent = events.filter((e) => e.event === "docs").at(-1) ?? null;
	const lastRedIdx = events.findLastIndex((e) => e.event === "red");
	const redEvent = lastRedIdx === -1 ? null : events[lastRedIdx];
	const verifyEvent =
		events
			.slice(lastRedIdx + 1)
			.filter((e) => e.event === "verify" && e.exit === 0)
			.at(-1) ?? null;

	const loop = {
		docs: docsEvent
			? { done: true, source: "ledger", decision: docsEvent.decision, paths: docsEvent.paths }
			: docsChanged.length > 0
				? { done: true, source: "diff", paths: docsChanged }
				: { done: false },
		red: redEvent
			? { done: true, genuine: redEvent.genuine, cmd: redEvent.cmd, exit: redEvent.exit }
			: { done: false },
		impl: { done: nonDocChanged.length > 0 },
		verify: verifyEvent ? { done: true, cmd: verifyEvent.cmd, exit: verifyEvent.exit } : { done: false },
	};
	const scopeEvent = events.filter((e) => e.event === "scope").at(-1) ?? null;
	const slice = scopeEvent
		? {
				declared: true,
				frozenPaths: scopeEvent.frozenPaths,
				allowedPaths: scopeEvent.allowedPaths,
			}
		: { declared: false };
	// the durable plan: a checkbox is a claim; [red:]-tagged items need the
	// ledger's proof (see planProgress)
	const reviewEvents = events.filter((e) => e.event === "review");
	const latestReview = reviewEvents.at(-1) ?? null;
	// a stale approval reopens the review everywhere: for grading purposes
	// it stops being the newest approval
	const reviewStale =
		latestReview?.verdict === "approved" &&
		latestReview.snapshot !== reviewSnapshot(cwd, config.baseRef);
	const gradableReviews = reviewStale
		? [...reviewEvents, { event: "review", verdict: "stale" }]
		: reviewEvents;
	const planPath = path.join(cwd, PLAN_REL);
	const plan = fs.existsSync(planPath)
		? (() => {
				const parsed = parsePlan(fs.readFileSync(planPath, "utf8"));
				const p = planProgress(
					parsed,
					events.filter((e) => e.event === "red"),
					gradableReviews,
				);
				const pick = (i) => ({ text: i.text, line: i.line, red: i.red, review: i.review });
				// a [review:]-tagged item is the closing review and closes only
				// through the ledger; untagged plans fall back to the LAST item
				// mentioning "review" — a mid-plan "review X" step never counts
				const tagged = parsed.items.find((i) => i.review) ?? null;
				const lastItem = parsed.items.at(-1) ?? null;
				const heuristic = lastItem && /\breview\b/i.test(lastItem.text) ? lastItem : null;
				const reviewItem = tagged ?? heuristic;
				const reviewDone = tagged
					? tagged.checked && latestReview?.verdict === "approved" && !reviewStale
					: (reviewItem?.checked ?? false);
				return {
					present: true,
					total: p.total,
					done: p.done,
					deferred: parsed.deferred.length,
					next: p.next ? pick(p.next) : null,
					unproven: p.unproven.map(pick),
					review: reviewItem ? { present: true, done: reviewDone } : { present: false },
				};
			})()
		: { present: false };
	const pr = statusPr(cwd);
	const trunc = (s) => (s.length > 72 ? `${s.slice(0, 69)}…` : s);

	let next;
	if (pr.state === "open" && pr.checks.failure > 0) {
		// a red required check on an open PR outranks everything — pr-green
		next = `drive PR #${pr.number}'s required checks terminal-green (pr-green playbook)`;
	} else if (!loop.docs.done) {
		next = "make the docs decision: edit the canonical docs, or record `stdd docs <decision>`";
	} else if (!loop.red.done) {
		next = "write the failing test and record it via `stdd red -- <cmd>`";
	} else if (!loop.impl.done) {
		next = "implement until the red test passes";
	} else if (!loop.verify.done) {
		next = "run the narrowest verify lane via `stdd verify -- <cmd>`";
	} else if (plan.present && plan.next) {
		if (plan.unproven.some((u) => u.line === plan.next.line)) {
			next = plan.next.review
				? `plan item "${trunc(plan.next.text)}" is checked but the review is unproven — run \`stdd review\``
				: `plan item "${trunc(plan.next.text)}" is checked but unproven — ` +
					`record \`stdd red -- <cmd containing "${plan.next.red}">\` or uncheck it`;
		} else if (plan.next.review) {
			next = `run \`stdd review\` — the closing review closes "${trunc(plan.next.text)}"`;
		} else {
			next = `continue the plan (${plan.done}/${plan.total} done) — next item: "${trunc(plan.next.text)}"`;
		}
	} else if (pr.state === "none") {
		// the closing review rides on a dispatch capability — with both routes
		// off the suggestion is omitted, never degraded to self-review; a
		// plan whose own review item is checked is not asked twice
		const caps = config.capabilities ?? {};
		const reviewed = plan.present && plan.review?.present && plan.review.done;
		const review =
			!reviewed && (caps.subagents || caps.crossCli)
				? "dispatch a fresh reviewer over the diff (delegate-slice playbook), then "
				: "";
		next = scopeEvent
			? `run \`stdd scope\` (slice postflight), then ${review}draft the evidence line via \`stdd evidence\` and open the PR`
			: `${review}draft the evidence line via \`stdd evidence\`, then open the PR`;
	} else if (pr.state === "open" && (pr.checks.failure > 0 || pr.checks.pending > 0)) {
		next = `drive PR #${pr.number}'s required checks terminal-green (pr-green playbook)`;
	} else if (pr.state === "open") {
		next = `PR #${pr.number} checks are green — done pending review and merge`;
	} else {
		next = `PR state unknown (${pr.reason}) — draft the evidence line via \`stdd evidence\` if no PR exists yet`;
	}

	const reviewState = latestReview
		? {
				verdict: latestReview.verdict,
				via: latestReview.via,
				blocking: (latestReview.findings ?? []).filter((f) => f.severity === "blocking").length,
				stale: reviewStale,
			}
		: null;
	if (asJson) {
		console.log(
			JSON.stringify({ branch, loop, slice, plan, review: reviewState, pr, next }, null, "\t"),
		);
		return;
	}
	const mark = (step) => (step.done ? "✓" : "✗");
	const docsDetail = docsEvent
		? ` (${docsEvent.decision}${docsEvent.paths?.length ? `: ${docsEvent.paths.join(", ")}` : ""})`
		: docsChanged.length > 0
			? ` (diff: ${docsChanged.join(", ")})`
			: changed === null
				? " — unknown (no resolvable baseRef)"
				: " — no docs decision recorded, no canonical docs in the diff";
	const redDetail = redEvent
		? ` (genuine: ${redEvent.genuine}, exit ${redEvent.exit}: ${redEvent.cmd})`
		: " — no red recorded";
	const implDetail = loop.impl.done
		? " (working tree has non-doc changes)"
		: " — no non-doc changes yet";
	const verifyDetail = verifyEvent
		? ` (exit 0: ${verifyEvent.cmd})`
		: " — no passing verify recorded since the last red";
	const prLine =
		pr.state === "open"
			? `#${pr.number} — ${pr.checks.failure} failing, ${pr.checks.pending} pending, ${pr.checks.success} green`
			: pr.state === "none"
				? `none for ${branch}`
				: `unknown (${pr.reason})`;
	console.log(
		[
			`loop:   docs ${mark(loop.docs)}${docsDetail}`,
			`        red  ${mark(loop.red)}${redDetail}`,
			`        impl ${mark(loop.impl)}${implDetail}`,
			`        verify ${mark(loop.verify)}${verifyDetail}`,
			...(scopeEvent
				? [
						`slice:  declared (frozen: ${scopeEvent.frozenPaths.join(", ") || "—"}; ` +
							`allowed: ${scopeEvent.allowedPaths.join(", ") || "—"}) — postflight: stdd scope`,
					]
				: []),
			...(plan.present
				? [
						`plan:   ${plan.total === 0 ? "no checklist items" : `${plan.done}/${plan.total} done`}` +
							(plan.deferred > 0 ? ` (${plan.deferred} deferred)` : "") +
							(plan.next
								? ` — next: "${trunc(plan.next.text)}"`
								: plan.total > 0
									? " — all items closed"
									: ""),
						...plan.unproven.map((u) =>
							u.review
								? `        unproven: "${trunc(u.text)}" — checked, but the newest recorded review is not an approval`
								: `        unproven: "${trunc(u.text)}" — checked, but no recorded red matches "${u.red}"`,
						),
					]
				: []),
			...(reviewState
				? [
						`review: ${
							reviewState.verdict === "approved"
								? `approved via ${reviewState.via}${reviewState.stale ? " — STALE, the checkout changed since" : ""}`
								: reviewState.verdict === "changes-requested"
									? `changes requested via ${reviewState.via} — ${reviewState.blocking} blocking`
									: `error via ${reviewState.via} — rerun \`stdd review\``
						}`,
					]
				: []),
			`pr:     ${prLine}`,
			`next:   ${next}`,
		].join("\n"),
	);
}

/**
 * `stdd status --gate` — the review state as an exit code for hooks.
 * Fails on broken claims (checked-but-unproven review, changes-requested,
 * error, stale approval, impossible route), never on unfinished work.
 */
function statusGate(cwd) {
	const config = loadConfig(cwd);
	const branch = requireBranch(cwd);
	const events = loadLedger(cwd, branch);
	const reasons = [];
	const via = config.review.via;
	if (via === "codex" && !config.capabilities.crossCli) {
		reasons.push('review.via is "codex" but the crossCli capability is off');
	}
	if (via === "subagent" && !config.capabilities.subagents) {
		reasons.push('review.via is "subagent" but the subagents capability is off');
	}
	const latest = events.filter((e) => e.event === "review").at(-1) ?? null;
	if (latest?.verdict === "changes-requested") {
		const blocking = (latest.findings ?? []).filter((f) => f.severity === "blocking").length;
		reasons.push(
			`the newest review requested changes (${blocking} blocking) — fix and rerun \`stdd review\``,
		);
	}
	if (latest?.verdict === "error") {
		reasons.push(`the newest review errored (${latest.reason ?? "unknown"}) — rerun \`stdd review\``);
	}
	if (latest?.verdict === "approved" && latest.snapshot !== reviewSnapshot(cwd, config.baseRef)) {
		reasons.push("the approved review is stale — the checkout changed since; rerun `stdd review`");
	}
	const planPath = path.join(cwd, PLAN_REL);
	if (fs.existsSync(planPath)) {
		const parsed = parsePlan(fs.readFileSync(planPath, "utf8"));
		const claimed = parsed.items.some((i) => i.review && i.checked);
		if (claimed && latest?.verdict !== "approved") {
			reasons.push("a [review:] item is checked but no approved review is recorded — run `stdd review`");
		}
	}
	if (reasons.length === 0) {
		console.log("stdd status --gate: ok");
		process.exit(0);
	}
	for (const r of reasons) console.log(`✗ ${r}`);
	process.exit(1);
}

/**
 * Draft the docs evidence line from the actual diff instead of recall.
 * Canonical docs changed → the finished line on stdout (substitution-safe);
 * none changed → the authored-sentinel templates on stderr, nonzero exit.
 */
function evidence(targetDir, baseRefFlag) {
	const config = loadConfig(targetDir);
	const base = baseRefFlag ?? config.baseRef;
	if (!base) {
		fail('evidence needs a base ref — pass --base <ref> or set "baseRef" in .stdd/config.json');
	}
	let changed;
	try {
		changed = execFileSync("git", ["-C", targetDir, "diff", "--name-only", `${base}...HEAD`], {
			encoding: "utf8",
			stdio: ["ignore", "pipe", "pipe"],
		})
			.split("\n")
			.filter(Boolean);
	} catch (err) {
		fail(`--base ${base}: git diff failed: ${err.stderr?.toString().trim() || err.message}`);
	}
	const canonical = config.canonicalDocs.map(globToRegExp);
	const docs = changed.filter((file) => canonical.some((re) => re.test(file)));
	// The ledger's recorded decision is read first; the diff is the
	// cross-check, and on contradiction the diff wins and the conflict is
	// reported. loadLedger needs a branch — outside a git repo there is no
	// ledger to consult, so degrade to diff-only.
	const evidenceBranch = currentBranch(targetDir);
	const recorded = evidenceBranch
		? (loadLedger(targetDir, evidenceBranch)
				.filter((e) => e.event === "docs")
				.at(-1) ?? null)
		: null;
	if (docs.length > 0) {
		if (recorded && recorded.decision !== "updated-first") {
			console.error(
				`stdd evidence: the ledger records "${recorded.decision}" but the diff changes ` +
					`canonical docs — the diff wins; the ledger claim is contradicted`,
			);
		}
		console.log(`Docs updated first: ${docs.join(", ")}`);
		return;
	}
	if (recorded?.decision === "checked") {
		console.log(`Docs checked, no change needed: ${recorded.paths.join(", ")} — ${recorded.reason}`);
		return;
	}
	if (recorded?.decision === "not-applicable") {
		console.log(`Docs not applicable: ${recorded.reason}`);
		return;
	}
	fail(
		`no canonical docs changed against ${base}${
			recorded ? ` — the ledger claims "updated-first" but the diff is contradicted` : ""
		} — author the evidence line yourself:\n` +
			"  Docs checked, no change needed: <docs + reason>\n" +
			"  Docs not applicable: <why implementation-only>",
	);
}

function checkPr(prBodyFile, baseRef, pr) {
	let body;
	let headRef = "HEAD";
	let okSuffix = "";
	if (pr) {
		if (prBodyFile) fail(`--pr replaces the <file|-> argument — drop "${prBodyFile}"`);
		if (baseRef) fail("--pr derives the base from the PR — drop --base");
		const live = resolveLivePr(pr);
		body = live.body;
		baseRef = live.baseRef;
		headRef = live.headRef;
		const shortHead = (headRef === "HEAD" ? git("rev-parse", "HEAD") : headRef).slice(0, 7);
		okSuffix = ` (PR #${live.number} body, base ${baseRef}, head ${shortHead})`;
	} else {
		body =
			prBodyFile === "-" || !prBodyFile
				? fs.readFileSync(0, "utf8")
				: fs.readFileSync(prBodyFile, "utf8");
	}
	const matches = findEvidenceLines(body);
	if (matches.length === 0) {
		let message =
			"PR body has no docs evidence line. Add exactly one of:\n" +
			"  Docs updated first: <docs>\n" +
			"  Docs checked, no change needed: <docs + reason>\n" +
			"  Docs not applicable: <why implementation-only>";
		for (const near of nearMissEvidenceLines(body)) {
			message +=
				`\n\nline ${near.line} is a near-miss:\n` +
				`  found: ${near.raw.trim()}\n` +
				`  fix:   ${near.suggestion}\n` +
				"  (the line must start at column 0 with the exact label, no markdown formatting)";
		}
		fail(message);
	}
	if (matches.length > 1) {
		fail(
			`PR body has ${matches.length} docs evidence lines ` +
				`(lines ${matches.map((m) => m.line).join(", ")}) — keep exactly one.`,
		);
	}
	if (matches[0].content === "") {
		fail(`"${matches[0].label}:" names no evidence — list the docs or the reason after the colon.`);
	}
	const repoDir = resolveRepoDir(process.cwd());
	if (baseRef) verifyEvidenceAgainstDiff(matches[0], baseRef, headRef, repoDir);
	// Advisory only — a ledger disagreement never changes the pass condition.
	const advisoryBranch = currentBranch(repoDir);
	const recorded = advisoryBranch
		? (loadLedger(repoDir, advisoryBranch)
				.filter((e) => e.event === "docs")
				.at(-1) ?? null)
		: null;
	if (recorded && LABEL_TO_DECISION[matches[0].label] !== recorded.decision) {
		console.error(
			`stdd check-pr: advisory — the ledger records the docs decision as ` +
				`"${recorded.decision}" but the PR body says "${matches[0].label}"`,
		);
	}
	console.log(`stdd check-pr: OK${okSuffix}`);
}

/** With --base: the evidence claim must be backed by the actual git diff. */
function verifyEvidenceAgainstDiff(
	{ label, content },
	baseRef,
	headRef = "HEAD",
	repoDir = process.cwd(),
) {
	const paths = extractDocPaths(content);
	if (label === "Docs updated first") {
		if (paths.length === 0) {
			const suggestion = sentinelSuggestion(content);
			fail(
				`"Docs updated first:" names no doc paths — list the changed docs.` +
					(suggestion ? `\nDid you mean:\n  ${suggestion}` : ""),
			);
		}
		let changed;
		try {
			changed = execFileSync("git", ["diff", "--name-only", `${baseRef}...${headRef}`], {
				encoding: "utf8",
				stdio: ["ignore", "pipe", "pipe"],
			})
				.split("\n")
				.filter(Boolean);
		} catch (err) {
			fail(`--base ${baseRef}: git diff failed: ${err.stderr?.toString().trim() || err.message}`);
		}
		const missing = paths.filter((p) => !changed.includes(p));
		if (missing.length > 0) {
			fail(`claimed as updated but not changed against ${baseRef}: ${missing.join(", ")}`);
		}
	} else if (label === "Docs checked, no change needed") {
		const absent = paths.filter((p) => !fs.existsSync(path.join(repoDir, ...p.split("/"))));
		if (absent.length > 0) {
			fail(`claimed as checked but does not exist in the tree: ${absent.join(", ")}`);
		}
	}
}

// --- argument parsing (strict: unknown flags are errors) ---
const [, , command, ...rest] = process.argv;

// Ledger commands parse their own arguments (`--` passthrough, repeated
// positionals) and exit here; the strict generic loop below never sees them.
if (command === "red" || command === "verify") {
	const sep = rest.indexOf("--");
	if (sep === -1 || sep === rest.length - 1) {
		fail(`${command} needs a command: stdd ${command} -- <cmd> [args…]`);
	}
	if (sep !== 0) fail(`unexpected argument before --: ${rest[0]}`);
	recordRun(resolveRepoDir(process.cwd()), command, rest.slice(sep + 1));
}
if (command === "docs") {
	let reason = null;
	const words = [];
	for (let i = 0; i < rest.length; i++) {
		const arg = rest[i];
		if (arg === "--reason" || arg.startsWith("--reason=")) {
			reason = arg.includes("=") ? arg.slice("--reason=".length) : (rest[++i] ?? "");
			if (!reason) fail("--reason requires a value");
		} else if (arg.startsWith("--")) {
			fail(`unknown flag: ${arg}`);
		} else {
			words.push(arg);
		}
	}
	recordDocs(resolveRepoDir(process.cwd()), words[0], words.slice(1), reason);
	process.exit(0);
}
if (command === "note") {
	const text = rest.join(" ").trim();
	if (!text) fail("note needs text: stdd note <text>");
	appendLedger(resolveRepoDir(process.cwd()), { event: "note", text });
	console.log("stdd note: recorded");
	process.exit(0);
}
if (command === "defer") {
	const text = rest.join(" ").trim();
	if (!text) fail("defer needs text: stdd defer <what is cut and why>");
	defer(resolveRepoDir(process.cwd()), text);
	process.exit(0);
}
if (command === "slice") {
	if (rest[0] !== "new") {
		fail(`unknown slice subcommand "${rest[0] ?? ""}" — use "stdd slice new"`);
	}
	let frozen = [];
	let allowed = [];
	for (let i = 1; i < rest.length; i++) {
		const arg = rest[i];
		if (arg === "--frozen" || arg.startsWith("--frozen=")) {
			const value = arg.includes("=") ? arg.slice("--frozen=".length) : (rest[++i] ?? "");
			frozen = value.split(",").filter(Boolean);
			if (frozen.length === 0) fail("--frozen requires globs, e.g. --frozen docs/**,migrations/**");
		} else if (arg === "--allowed" || arg.startsWith("--allowed=")) {
			const value = arg.includes("=") ? arg.slice("--allowed=".length) : (rest[++i] ?? "");
			allowed = value.split(",").filter(Boolean);
			if (allowed.length === 0) fail("--allowed requires globs, e.g. --allowed src/billing/**");
		} else {
			fail(`unexpected argument: ${arg}`);
		}
	}
	sliceNew(resolveRepoDir(process.cwd()), frozen, allowed);
	process.exit(0);
}
if (command === "scope") {
	if (rest.length > 0) fail(`unexpected argument: ${rest[0]}`);
	scopeCheck(resolveRepoDir(process.cwd()));
	process.exit(0);
}
if (command === "status") {
	const unknown = rest.filter((a) => a !== "--json" && a !== "--gate");
	if (unknown.length > 0) fail(`unexpected argument: ${unknown[0]}`);
	if (rest.includes("--gate")) statusGate(resolveRepoDir(process.cwd()));
	status(resolveRepoDir(process.cwd()), rest.includes("--json"));
	process.exit(0);
}
if (command === "review") {
	let via = null;
	let timeout = 600;
	let result = null;
	for (let i = 0; i < rest.length; i++) {
		const arg = rest[i];
		if (arg === "--via" || arg.startsWith("--via=")) {
			via = arg.includes("=") ? arg.slice("--via=".length) : (rest[++i] ?? "");
			if (!via) fail(`--via requires a value (${REVIEW_VIAS.join(", ")})`);
		} else if (arg === "--timeout" || arg.startsWith("--timeout=")) {
			const value = arg.includes("=") ? arg.slice("--timeout=".length) : (rest[++i] ?? "");
			timeout = Number(value);
			// integer seconds, bounded: spawnSync needs a sane uint32 of
			// milliseconds, and a parse-time failure must precede any side
			// effect (request event, brief file)
			if (!/^\d+$/.test(value) || !Number.isInteger(timeout) || timeout < 1 || timeout > 86_400)
				fail("--timeout requires whole seconds between 1 and 86400, e.g. --timeout 600");
		} else if (arg === "--result" || arg.startsWith("--result=")) {
			result = arg.includes("=") ? arg.slice("--result=".length) : (rest[++i] ?? "");
			if (!result) fail("--result requires a file path or - for stdin");
		} else {
			fail(`unexpected argument: ${arg}`);
		}
	}
	const cwd = resolveRepoDir(process.cwd());
	if (result !== null) {
		if (via !== null) fail("--result grades an existing request — --via belongs to the dispatch call");
		reviewSubmit(cwd, loadConfig(cwd), result);
	} else {
		reviewRun(cwd, via, timeout);
	}
	process.exit(0);
}
let tools = null;
let ci = null;
let baseRefArg = null;
let prArg = null;
let readinessOnly = false;
let hooksFlag = false;
let capabilitiesArg = null;
let sessionHookFlag = false;
let interviewFlag = false;
let watchFlag = false;
let intervalArg = 15;
let timeoutArg = 1800;
const positional = [];
for (let i = 0; i < rest.length; i++) {
	const arg = rest[i];
	if (arg === "--base" || arg.startsWith("--base=")) {
		if (command !== "check-pr" && command !== "evidence") {
			fail(`--base is only valid for "stdd check-pr" and "stdd evidence"`);
		}
		baseRefArg = arg.includes("=") ? arg.slice("--base=".length) : (rest[++i] ?? "");
		if (!baseRefArg) fail("--base requires a git ref, e.g. --base origin/main");
	} else if (arg === "--hooks") {
		if (command !== "init") fail(`--hooks is only valid for "stdd init"`);
		hooksFlag = true;
	} else if (arg === "--session-hook") {
		if (command !== "init") fail(`--session-hook is only valid for "stdd init"`);
		sessionHookFlag = true;
	} else if (arg === "--interview") {
		if (command !== "init") fail(`--interview is only valid for "stdd init"`);
		interviewFlag = true;
	} else if (arg === "--capabilities" || arg.startsWith("--capabilities=")) {
		if (command !== "init") fail(`--capabilities is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--capabilities=".length) : (rest[++i] ?? "");
		capabilitiesArg = value.split(",").filter(Boolean);
		if (capabilitiesArg.length === 0) {
			fail("--capabilities requires a value, e.g. --capabilities subagents,worktrees");
		}
		const unknown = capabilitiesArg.filter((c) => !KNOWN_CAPABILITIES.includes(c));
		if (unknown.length > 0) {
			fail(`unknown capability(ies): ${unknown.join(", ")} (known: ${KNOWN_CAPABILITIES.join(", ")})`);
		}
	} else if (arg === "--readiness") {
		if (command !== "doctor") fail(`--readiness is only valid for "stdd doctor"`);
		readinessOnly = true;
	} else if (arg === "--watch") {
		if (command !== "ci") fail(`--watch is only valid for "stdd ci"`);
		watchFlag = true;
	} else if (arg === "--interval" || arg.startsWith("--interval=")) {
		if (command !== "ci") fail(`--interval is only valid for "stdd ci"`);
		const value = arg.includes("=") ? arg.slice("--interval=".length) : (rest[++i] ?? "");
		intervalArg = Number(value);
		if (!Number.isFinite(intervalArg) || intervalArg < 0) {
			fail("--interval requires seconds, e.g. --interval 15");
		}
	} else if (arg === "--timeout" || arg.startsWith("--timeout=")) {
		if (command !== "ci") fail(`--timeout is only valid for "stdd ci"`);
		const value = arg.includes("=") ? arg.slice("--timeout=".length) : (rest[++i] ?? "");
		timeoutArg = Number(value);
		if (!Number.isFinite(timeoutArg) || timeoutArg < 0) {
			fail("--timeout requires seconds, e.g. --timeout 1800");
		}
	} else if (arg === "--pr" || arg.startsWith("--pr=")) {
		if (command !== "check-pr") fail(`--pr is only valid for "stdd check-pr"`);
		prArg = arg.includes("=") ? arg.slice("--pr=".length) : (rest[++i] ?? "");
		if (!prArg) fail("--pr requires a PR number, or . for the current branch's PR");
	} else if (arg === "--ci" || arg.startsWith("--ci=")) {
		if (command !== "init") fail(`--ci is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--ci=".length) : (rest[++i] ?? "");
		ci = value.split(",").filter(Boolean);
		if (ci.length === 0) fail("--ci requires a value, e.g. --ci github");
		const unknown = ci.filter((c) => !KNOWN_CI.includes(c));
		if (unknown.length > 0) {
			fail(`unknown ci provider(s): ${unknown.join(", ")} (known: ${KNOWN_CI.join(", ")})`);
		}
	} else if (arg === "--tools" || arg.startsWith("--tools=")) {
		if (command !== "init") fail(`--tools is only valid for "stdd init"`);
		const value = arg.includes("=") ? arg.slice("--tools=".length) : (rest[++i] ?? "");
		tools = value.split(",").filter(Boolean);
		if (tools.length === 0) fail("--tools requires a value, e.g. --tools claude,codex");
		const unknown = tools.filter((t) => !KNOWN_TOOLS.includes(t));
		if (unknown.length > 0) {
			fail(`unknown tool(s): ${unknown.join(", ")} (known: ${KNOWN_TOOLS.join(", ")})`);
		}
	} else if (arg.startsWith("--")) {
		fail(`unknown flag: ${arg}`);
	} else {
		positional.push(arg);
	}
}
if (positional.length > 1) fail(`unexpected argument: ${positional[1]}`);
const targetDir = path.resolve(positional[0] ?? ".");

switch (command) {
	case "init": {
		if (interviewFlag && (tools || ci || capabilitiesArg || hooksFlag || sessionHookFlag)) {
			fail("--interview replaces the other init flags — drop them and answer the questions instead");
		}
		const opts = interviewFlag
			? await interview()
			: {
					tools: tools ?? KNOWN_TOOLS,
					ci: ci ?? [],
					hooks: hooksFlag,
					sessionHook: sessionHookFlag,
					capabilitiesList: capabilitiesArg,
				};
		init(targetDir, opts);
		break;
	}
	case "check":
		check(targetDir);
		break;
	case "doctor":
		doctor(targetDir, readinessOnly);
		break;
	case "check-pr":
		checkPr(positional[0], baseRefArg, prArg);
		break;
	case "evidence":
		// Without an explicit dir, evidence anchors to the repo like the
		// recorders — its config and ledger live at the root .stdd/.
		evidence(positional[0] ? targetDir : resolveRepoDir(process.cwd()), baseRefArg);
		break;
	case "ci":
		await ciCommand(positional[0] ?? null, watchFlag, intervalArg, timeoutArg);
		break;
	case "--version":
	case "version":
		console.log(VERSION);
		break;
	default: {
		if (command) {
			const guess = didYouMean(command, [
				"init",
				"check",
				"check-pr",
				"evidence",
				"doctor",
				"status",
				"docs",
				"red",
				"verify",
				"note",
				"defer",
				"slice",
				"scope",
				"review",
				"ci",
				"version",
			]);
			console.error(`stdd: unknown command "${command}"${guess ? ` — did you mean "${guess}"?` : ""}`);
		}
		console.log(
			"Usage: stdd <init|check|check-pr|evidence|doctor|status|ci|docs|red|verify|note|defer|slice|scope|review> " +
				"[dir|pr-body-file|pr] [--tools claude,codex] [--ci github] [--hooks] [--base <ref>] " +
				"[--pr <n|.>] [--watch] [--readiness] [--json] [--gate] [--reason <why>] " +
				"[--via subagent|codex] [--result <file|->] [--timeout <s>] [-- <cmd>]",
		);
		process.exit(command ? 1 : 0);
	}
}
