#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compileCapabilities, DEFAULT_CONFIG, parseFrontmatter } from "../cli/lib.mjs";
import { renderAgentSkill } from "../sdk/adapters.mjs";
import {
	atomicWriteFile,
	closeHeldDirectory,
	ensureHeldChildDirectory,
	openHeldDirectory,
	quarantineStaleSkill,
	readHeldRegularFile,
	requireSafeDirectory,
	requireSafeRegularFile,
	requireSafeTree,
} from "../sdk/held-publication.mjs";
import { assertSkillName } from "../sdk/path.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const QUARANTINE_README =
	"STDD plugin build quarantine.\n\n" +
	"These stale generated skill directories were removed from the active skills registry but retained " +
	"because Node.js has no descriptor-relative unlink primitive. Inspect and remove this directory manually.\n";

function validateDefaultPrompts(manifest) {
	const prompts = manifest?.interface?.defaultPrompt;
	if (
		!Array.isArray(prompts) ||
		prompts.length === 0 ||
		prompts.length > 3 ||
		prompts.some((prompt) => typeof prompt !== "string" || prompt.trim() === "" || prompt.length > 128)
	) {
		throw new TypeError(
			"plugin interface.defaultPrompt must be an array of 1-3 non-empty strings up to 128 characters",
		);
	}
}

export function buildPlugin(root = ROOT) {
	const pluginsRoot = path.join(root, "plugins");
	const pluginRoot = path.join(root, "plugins", "stdd");
	const skillsRoot = path.join(pluginRoot, "skills");
	const manifestRoot = path.join(pluginRoot, ".codex-plugin");
	const manifestPath = path.join(pluginRoot, ".codex-plugin", "plugin.json");
	const hooksRoot = path.join(pluginRoot, "hooks");
	const scriptsRoot = path.join(pluginRoot, "scripts");
	if (process.platform !== "linux") {
		throw new Error(
			"secure plugin publication requires Linux held-directory support (/proc/self/fd); nothing was written",
		);
	}

	// Validate every existing publication boundary before reading templates
	// into an output plan. No manifest or skill is written until all active
	// and stale targets, plus the lifecycle bundle, have passed this preflight.
	requireSafeDirectory(pluginsRoot, "plugins directory");
	requireSafeDirectory(pluginRoot, "plugins/stdd");
	requireSafeDirectory(manifestRoot, "plugins/stdd/.codex-plugin");
	requireSafeRegularFile(manifestPath, "plugins/stdd/.codex-plugin/plugin.json");
	requireSafeDirectory(skillsRoot, "plugins/stdd/skills");
	requireSafeTree(hooksRoot, "plugins/stdd/hooks");
	requireSafeTree(scriptsRoot, "plugins/stdd/scripts");

	const playbooksRoot = path.join(root, "playbooks");
	requireSafeDirectory(playbooksRoot, "playbooks directory");
	const heldDirectories = [];
	try {
		const pluginHeld = openHeldDirectory(pluginRoot, "plugins/stdd");
		heldDirectories.push(pluginHeld);
		const manifestHeld = openHeldDirectory(manifestRoot, "plugins/stdd/.codex-plugin");
		heldDirectories.push(manifestHeld);
		const skillsHeld = openHeldDirectory(skillsRoot, "plugins/stdd/skills");
		heldDirectories.push(skillsHeld);
		const playbooksHeld = openHeldDirectory(playbooksRoot, "playbooks directory");
		heldDirectories.push(playbooksHeld);

		const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
		const manifest = JSON.parse(
			readHeldRegularFile(manifestHeld, "plugin.json", "plugins/stdd/.codex-plugin/plugin.json"),
		);
		validateDefaultPrompts(manifest);
		manifest.version = pkg.version;

		const stamp = `generated by stdd plugin build v${pkg.version} — do not edit`;
		const generatedNames = new Set();
		const generatedSkills = new Map();
		for (const file of fs.readdirSync(playbooksHeld.heldPath).filter((name) => name.endsWith(".md"))) {
			const source = readHeldRegularFile(playbooksHeld, file, `playbook ${file}`, {
				requireSingleLink: true,
			});
			const { meta, body } = parseFrontmatter(source);
			assertSkillName(meta.name, `playbook ${file} name`);
			if (generatedNames.has(meta.name)) {
				throw new Error(`duplicate plugin skill name ${JSON.stringify(meta.name)}`);
			}
			const output = renderAgentSkill({
				adapter: "codex",
				name: meta.name,
				description: meta.description,
				when: meta.when,
				body: compileCapabilities(body, DEFAULT_CONFIG.capabilities),
				stamp,
			});
			generatedNames.add(meta.name);
			generatedSkills.set(meta.name, output);
		}

		const existingSkillNames = new Set();
		const staleSkillNames = [];
		for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
			const skillDir = path.join(skillsRoot, entry.name);
			requireSafeDirectory(skillDir, `plugin skill ${entry.name}`);
			existingSkillNames.add(entry.name);
			if (generatedNames.has(entry.name)) {
				requireSafeRegularFile(path.join(skillDir, "SKILL.md"), `plugin skill ${entry.name}/SKILL.md`, {
					allowMissing: true,
				});
			} else {
				requireSafeTree(skillDir, `stale plugin skill ${entry.name}`);
				staleSkillNames.push(entry.name);
			}
		}

		const activeSkillDirectories = new Map();
		for (const name of generatedNames) {
			if (!existingSkillNames.has(name)) continue;
			const held = openHeldDirectory(path.join(skillsRoot, name), `plugin skill ${name}`);
			heldDirectories.push(held);
			activeSkillDirectories.set(name, held);
		}

		// Move stale load paths out of `skills/` before publishing any file
		// bytes. Node has no unlinkat(2)-equivalent, so recursive deletion
		// would reintroduce a final-basename race. Keep the verified inode in
		// a non-loadable, owner-private quarantine for explicit settlement.
		if (staleSkillNames.length > 0) {
			const quarantine = ensureHeldChildDirectory(
				pluginHeld,
				".stdd-plugin-quarantine",
				"plugins/stdd/.stdd-plugin-quarantine",
				0o700,
			);
			heldDirectories.push(quarantine);
			atomicWriteFile(
				quarantine,
				"README.txt",
				QUARANTINE_README,
				"plugins/stdd/.stdd-plugin-quarantine/README.txt",
			);
			for (const name of staleSkillNames) quarantineStaleSkill(skillsHeld, quarantine, name);
		}

		for (const name of generatedNames) {
			if (activeSkillDirectories.has(name)) continue;
			const held = ensureHeldChildDirectory(skillsHeld, name, `plugin skill ${name}`);
			heldDirectories.push(held);
			activeSkillDirectories.set(name, held);
		}

		for (const [name, output] of generatedSkills) {
			atomicWriteFile(
				activeSkillDirectories.get(name),
				"SKILL.md",
				output,
				`plugin skill ${name}/SKILL.md`,
			);
		}
		atomicWriteFile(
			manifestHeld,
			"plugin.json",
			`${JSON.stringify(manifest, null, "  ")}\n`,
			"plugins/stdd/.codex-plugin/plugin.json",
		);
		console.log(`Built STDD Codex plugin skills for v${pkg.version}`);
	} finally {
		for (const held of heldDirectories.reverse()) closeHeldDirectory(held);
	}
}

if (path.resolve(process.argv[1] ?? "") === fileURLToPath(import.meta.url)) buildPlugin();
