import { randomBytes } from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
	AGENT_ADAPTERS,
	assertSemanticVersion,
	CI_ADAPTERS,
	getAgentAdapter,
	renderAgentInstructions,
} from "../sdk/adapters.mjs";
import {
	publishHeldParentFile,
	sameFileIdentity,
	samePublicationObservation,
	samePublicationPayload,
} from "../sdk/held-publication.mjs";
import { assertSkillName, resolveRepoPath, resolveWritableRepoPath } from "../sdk/path.mjs";
import { isStddSourceCheckout } from "./claude-hooks.mjs";
import { openHeldLinuxRepoDirectory } from "./held-fs.mjs";
import { DEFAULT_CONFIG, parseFrontmatter, sha256 } from "./lib.mjs";
import { fail } from "./runtime.mjs";
import { MANIFEST_HASH_PATTERN } from "./state-validation.mjs";

const PKG_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const VERSION = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, "package.json"), "utf8")).version;
const KNOWN_TOOLS = Object.keys(AGENT_ADAPTERS);
const KNOWN_CI = Object.keys(CI_ADAPTERS);
const KNOWN_CAPABILITIES = Object.keys(DEFAULT_CONFIG.capabilities);
export const CLEANUP_JOURNAL_REL = ".stdd/cleanup-transaction.json";
const SHIPPED_PLAYBOOK_FILES = new Set(
	fs.readdirSync(path.join(PKG_ROOT, "playbooks")).filter((file) => file.endsWith(".md")),
);
// This append-only registry is package data: deleting a shipped playbook does
// not delete its ownership record, so existing installs can retire it safely
// without a release author remembering to move a basename between two lists.
const MANAGED_PLAYBOOK_REGISTRY = JSON.parse(
	fs.readFileSync(path.join(PKG_ROOT, "playbooks", "managed-playbooks.json"), "utf8"),
);
if (
	typeof MANAGED_PLAYBOOK_REGISTRY !== "object" ||
	MANAGED_PLAYBOOK_REGISTRY === null ||
	!Array.isArray(MANAGED_PLAYBOOK_REGISTRY.managed) ||
	MANAGED_PLAYBOOK_REGISTRY.managed.some(
		(file) =>
			typeof file !== "string" ||
			!file.endsWith(".md") ||
			path.posix.basename(file) !== file ||
			file === "." ||
			file === "..",
	) ||
	new Set(MANAGED_PLAYBOOK_REGISTRY.managed).size !== MANAGED_PLAYBOOK_REGISTRY.managed.length ||
	[...SHIPPED_PLAYBOOK_FILES].some((file) => !MANAGED_PLAYBOOK_REGISTRY.managed.includes(file))
) {
	throw new Error(
		"playbooks/managed-playbooks.json must be an append-only registry of shipped basenames",
	);
}
const KNOWN_MANAGED_PLAYBOOK_FILES = new Set(MANAGED_PLAYBOOK_REGISTRY.managed);
const STAMP = `generated by stdd v${VERSION} — do not edit, re-run \`stdd init\``;
const NPM_RUNNER = `npm exec --offline --package=@stdd/cli@${VERSION} -- stdd`;
const SOURCE_RUNNER = 'node "$(git rev-parse --show-toplevel)/cli/stdd.mjs"';

function validateAdapterSelection(field, values, known, { nonEmpty = false } = {}) {
	if (!Array.isArray(values)) throw new TypeError(`${field} must be an array`);
	if (nonEmpty && values.length === 0) {
		throw new TypeError(`${field} must be a non-empty array`);
	}
	if (values.some((id) => typeof id !== "string" || !known.includes(id))) {
		throw new TypeError(`${field} contains an unknown adapter ID`);
	}
	if (new Set(values).size !== values.length) {
		throw new TypeError(`${field} must not contain duplicate adapter IDs`);
	}
	return [...values];
}

function validateManifestTargets(value) {
	const required = ["tools", "ci", "hooks", "sessionHook", "stopHook"];
	if (typeof value !== "object" || value === null || Array.isArray(value)) {
		throw new TypeError("must be an object");
	}
	const keys = Object.keys(value);
	const missing = required.filter((key) => !Object.hasOwn(value, key));
	const unknown = keys.filter((key) => !required.includes(key));
	if (missing.length > 0 || unknown.length > 0) {
		throw new TypeError(
			`must contain exactly ${required.join(", ")}${
				missing.length > 0 ? `; missing ${missing.join(", ")}` : ""
			}${unknown.length > 0 ? `; unknown ${unknown.join(", ")}` : ""}`,
		);
	}
	const tools = validateAdapterSelection("tools", value.tools, KNOWN_TOOLS, {
		nonEmpty: true,
	});
	const ci = validateAdapterSelection("ci", value.ci, KNOWN_CI);
	for (const field of ["hooks", "sessionHook", "stopHook"]) {
		if (typeof value[field] !== "boolean") throw new TypeError(`${field} must be a boolean`);
	}
	return {
		tools,
		ci,
		hooks: value.hooks,
		sessionHook: value.sessionHook,
		stopHook: value.stopHook,
	};
}

function loadPlaybooks() {
	const dir = path.join(PKG_ROOT, "playbooks");
	return fs
		.readdirSync(dir)
		.filter((f) => f.endsWith(".md"))
		.map((f) => {
			const source = fs.readFileSync(path.join(dir, f), "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`playbook ${f} is missing required frontmatter (name, description)`);
			}
			try {
				assertSkillName(meta.name, `playbook ${f} name`);
			} catch (err) {
				fail(err.message);
			}
			return { file: f, source, meta, body };
		});
}

/**
 * Project recipes: repo-owned playbooks in `.stdd/playbooks/local/`, same
 * frontmatter contract as the kit's. Never generated, never overwritten.
 */
function loadLocalPlaybooks(targetDir) {
	let dir;
	try {
		dir = resolveWritableRepoPath(targetDir, ".stdd/playbooks/local", "local playbooks directory");
	} catch (err) {
		fail(err.message);
	}
	if (!fs.existsSync(dir)) return [];
	const playbooks = fs
		.readdirSync(dir, { withFileTypes: true })
		.filter((entry) => entry.name.endsWith(".md"))
		.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0))
		.map((entry) => {
			if (!entry.isFile()) fail(`local playbook local/${entry.name} must be a regular file`);
			const f = entry.name;
			let filePath;
			try {
				filePath = resolveWritableRepoPath(
					targetDir,
					`.stdd/playbooks/local/${f}`,
					`local playbook local/${f}`,
				);
			} catch (err) {
				fail(err.message);
			}
			const source = fs.readFileSync(filePath, "utf8");
			const { meta, body } = parseFrontmatter(source);
			if (!meta.name || !meta.description) {
				fail(`local playbook local/${f} is missing required frontmatter (name, description)`);
			}
			try {
				assertSkillName(meta.name, `local playbook local/${f} name`);
			} catch (err) {
				fail(err.message);
			}
			return { file: f, source, meta, body };
		});
	const byName = new Map();
	for (const playbook of playbooks) {
		const previous = byName.get(playbook.meta.name);
		if (previous) {
			fail(
				`duplicate local playbook name "${playbook.meta.name}" in .stdd/playbooks/local/${previous.file} and .stdd/playbooks/local/${playbook.file}; rename one recipe or give it a unique frontmatter name`,
			);
		}
		byName.set(playbook.meta.name, playbook);
	}
	return playbooks;
}

function isRecognizedGeneratedOutput(file) {
	const exact = new Set([
		".stdd/method.md",
		...Object.values(AGENT_ADAPTERS).map((adapter) => adapter.snippetFile),
		...Object.values(CI_ADAPTERS)
			.map((adapter) => adapter.outputFile)
			.filter((output) => output !== null),
		...[...KNOWN_MANAGED_PLAYBOOK_FILES].map((name) => `.stdd/playbooks/${name}`),
	]);
	if (exact.has(file)) return true;

	for (const adapter of Object.values(AGENT_ADAPTERS)) {
		const prefix = `${adapter.skillRoot}/`;
		if (!file.startsWith(prefix)) continue;
		const parts = file.slice(prefix.length).split("/");
		if (parts.length === 2 && parts[1] === "SKILL.md") {
			try {
				assertSkillName(parts[0], "manifest generated skill name");
				return true;
			} catch {
				return false;
			}
		}
	}

	if (!MANIFEST_QUARANTINE_BASENAME.test(path.posix.basename(file))) return false;
	const parent = path.posix.dirname(file);
	const exactParents = new Set([...exact].map((output) => path.posix.dirname(output)));
	if (exactParents.has(parent)) return true;
	for (const adapter of Object.values(AGENT_ADAPTERS)) {
		const prefix = `${adapter.skillRoot}/`;
		if (!parent.startsWith(prefix)) continue;
		const skillName = parent.slice(prefix.length);
		try {
			assertSkillName(skillName, "manifest quarantined skill name");
			return true;
		} catch {
			return false;
		}
	}
	return false;
}

/**
 * Read and validate the generated-file manifest once for every caller.
 * Returns null when the manifest is absent and throws an actionable shape
 * or path error for a present manifest that cannot be trusted.
 */
function readManifestDocument(targetDir) {
	let manifestPath;
	try {
		manifestPath = resolveWritableRepoPath(targetDir, ".stdd/manifest.json", "manifest path");
	} catch (err) {
		throw new TypeError(`has an unsafe path: ${err.message}`);
	}
	if (!fs.existsSync(manifestPath)) return null;
	let parsed;
	try {
		parsed = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
	} catch (err) {
		throw new TypeError(`is not valid JSON: ${err.message}`);
	}
	if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
		throw new TypeError("must contain a JSON object");
	}
	if (!Object.hasOwn(parsed, "generatedBy") || parsed.generatedBy !== "stdd") {
		throw new TypeError('generatedBy must equal "stdd"');
	}
	if (!Object.hasOwn(parsed, "version")) {
		throw new TypeError("version must be a semantic version");
	}
	assertSemanticVersion(parsed.version, "version");
	if (
		!Object.hasOwn(parsed, "files") ||
		typeof parsed.files !== "object" ||
		parsed.files === null ||
		Array.isArray(parsed.files)
	) {
		throw new TypeError("files must be an object");
	}
	const files = Object.create(null);
	for (const file of Object.keys(parsed.files)) {
		try {
			resolveWritableRepoPath(targetDir, file, `manifest path ${JSON.stringify(file)}`);
		} catch (err) {
			throw new TypeError(`has an unsafe path: ${err.message}`);
		}
		if (!isRecognizedGeneratedOutput(file)) {
			throw new TypeError(
				`files[${JSON.stringify(file)}] is not a recognized STDD-generated output path`,
			);
		}
		const hash = parsed.files[file];
		if (typeof hash !== "string" || !MANIFEST_HASH_PATTERN.test(hash)) {
			throw new TypeError(
				`files[${JSON.stringify(file)}] must be an exact sha256:<64 lowercase hex> hash`,
			);
		}
		files[file] = hash;
	}
	const normalized = { ...parsed, files };
	if (Object.hasOwn(parsed, "targets")) {
		try {
			normalized.targets = validateManifestTargets(parsed.targets);
		} catch (err) {
			throw new TypeError(`targets ${err.message}`);
		}
	}
	return normalized;
}

/** Files recorded by the previous init, or an empty map when none exists. */
function readManifestFiles(targetDir) {
	try {
		return readManifestDocument(targetDir)?.files ?? Object.create(null);
	} catch (err) {
		fail(`.stdd/manifest.json ${err.message}`);
	}
}

function writeCleanupJournal(targetDir, journal) {
	const journalPath = resolveRepoPath(targetDir, CLEANUP_JOURNAL_REL, "cleanup journal path");
	publishHeldParentFile({
		openDirectory: () => openHeldLinuxRepoDirectory(targetDir, ".stdd", "cleanup journal parent"),
		logicalTargetPath: journalPath,
		content: `${JSON.stringify(journal, null, "\t")}\n`,
		mode: 0o600,
		tempPrefix: ".cleanup-journal-",
		identityError: "cleanup journal parent or published identity changed during publication",
	});
}

function readCleanupJournal(targetDir) {
	const journalPath = resolveRepoPath(targetDir, CLEANUP_JOURNAL_REL, "cleanup journal path");
	const parentPath = path.dirname(journalPath);
	let before;
	try {
		before = fs.lstatSync(journalPath);
	} catch (err) {
		if (err.code === "ENOENT") return null;
		throw err;
	}
	let parentDescriptor = null;
	let journalDescriptor = null;
	let text;
	try {
		const parentBefore = fs.lstatSync(parentPath);
		if (parentBefore.isSymbolicLink() || !parentBefore.isDirectory()) {
			throw new Error("cleanup journal parent must be a non-symlinked directory");
		}
		parentDescriptor = fs.openSync(
			parentPath,
			fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW,
		);
		const parentOpened = fs.fstatSync(parentDescriptor);
		if (!sameFileIdentity(parentBefore, parentOpened)) {
			throw new Error("cleanup journal parent changed before it could be opened");
		}
		const descriptorPath =
			process.platform === "linux"
				? path.join(`/proc/self/fd/${parentDescriptor}`, path.basename(journalPath))
				: journalPath;
		journalDescriptor = fs.openSync(descriptorPath, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
		const opened = fs.fstatSync(journalDescriptor);
		const currentUid = typeof process.getuid === "function" ? process.getuid() : null;
		const safeShape = (stat) =>
			stat.isFile() &&
			!stat.isSymbolicLink() &&
			(stat.mode & 0o777) === 0o600 &&
			stat.nlink === 1 &&
			(currentUid === null || stat.uid === currentUid);
		if (!safeShape(before) || !safeShape(opened) || !sameFileIdentity(before, opened)) {
			throw new Error(
				"cleanup journal must be one unchanged regular file owned by the current user, single-linked, and exactly mode 0600",
			);
		}
		text = fs.readFileSync(journalDescriptor, "utf8");
		const openedAfter = fs.fstatSync(journalDescriptor);
		const after = fs.lstatSync(journalPath);
		const parentAfter = fs.lstatSync(parentPath);
		if (
			!safeShape(openedAfter) ||
			!safeShape(after) ||
			!sameFileIdentity(opened, openedAfter) ||
			!sameFileIdentity(opened, after) ||
			!sameFileIdentity(parentOpened, parentAfter)
		) {
			throw new Error("cleanup journal or its parent changed while it was read");
		}
	} finally {
		if (journalDescriptor !== null) {
			try {
				fs.closeSync(journalDescriptor);
			} catch {}
		}
		if (parentDescriptor !== null) {
			try {
				fs.closeSync(parentDescriptor);
			} catch {}
		}
	}
	const parsed = JSON.parse(text);
	if (
		typeof parsed !== "object" ||
		parsed === null ||
		parsed.version !== 1 ||
		!Array.isArray(parsed.entries) ||
		parsed.entries.length === 0
	) {
		throw new Error("cleanup journal has an invalid schema");
	}
	for (const entry of parsed.entries) {
		if (
			typeof entry !== "object" ||
			entry === null ||
			!["planned", "quarantined", "unresolved"].includes(entry.phase) ||
			typeof entry.source !== "string" ||
			typeof entry.quarantine !== "string" ||
			typeof entry.parentDev !== "string" ||
			typeof entry.parentIno !== "string" ||
			typeof entry.fileDev !== "string" ||
			typeof entry.fileIno !== "string" ||
			typeof entry.keepSource !== "boolean" ||
			typeof entry.reason !== "string" ||
			entry.source === entry.quarantine ||
			!MANIFEST_HASH_PATTERN.test(entry.hash)
		) {
			throw new Error("cleanup journal has an invalid entry");
		}
		// Entry paths are validated lexically here. Recovery separately proves
		// the current no-symlink walk and captured parent identity; a hostile
		// post-crash symlink is unresolved state, not a malformed journal.
		const source = resolveRepoPath(targetDir, entry.source, "cleanup journal source");
		const quarantine = resolveRepoPath(targetDir, entry.quarantine, "cleanup journal quarantine");
		if (path.dirname(source) !== path.dirname(quarantine)) {
			throw new Error("cleanup journal source and quarantine must share a parent");
		}
		if (!MANIFEST_QUARANTINE_BASENAME.test(path.posix.basename(entry.quarantine))) {
			throw new Error("cleanup journal has an invalid quarantine name");
		}
	}
	return parsed;
}

const CLEANUP_JOURNAL_QUARANTINE_README = `STDD cleanup journal quarantine — do not load

This owner-private, same-device directory outside the checkout contains a
zero-length tombstone from an identity-bound cleanup journal settlement.
STDD never deletes quarantine pathnames automatically because a final
basename can be replaced concurrently. Inspect and remove this directory
manually when convenient.
`;

function openCleanupJournalQuarantine(targetDir, sourceDevice, currentUid) {
	const realRepo = fs.realpathSync(targetDir);
	const candidates = [...new Set([fs.realpathSync(path.resolve(os.tmpdir())), path.dirname(realRepo)])];
	let lastError = null;
	for (const candidate of candidates) {
		if (candidate === realRepo || candidate.startsWith(`${realRepo}${path.sep}`)) continue;
		let tempDescriptor = null;
		let quarantineDescriptor = null;
		try {
			tempDescriptor = fs.openSync(
				candidate,
				fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW,
			);
			const tempIdentity = fs.fstatSync(tempDescriptor);
			const heldTemp = `/proc/self/fd/${tempDescriptor}`;
			if (
				!tempIdentity.isDirectory() ||
				tempIdentity.dev !== sourceDevice ||
				fs.realpathSync(heldTemp) !== candidate
			) {
				fs.closeSync(tempDescriptor);
				continue;
			}
			const heldQuarantinePath = fs.mkdtempSync(path.join(heldTemp, "stdd-cleanup-journal-quarantine-"));
			const quarantinePath = fs.realpathSync(heldQuarantinePath);
			if (path.dirname(quarantinePath) !== candidate) {
				throw new Error("cleanup journal quarantine escaped its held temp parent");
			}
			fs.chmodSync(heldQuarantinePath, 0o700);
			fs.writeFileSync(path.join(heldQuarantinePath, "README.txt"), CLEANUP_JOURNAL_QUARANTINE_README, {
				mode: 0o600,
				flag: "wx",
			});
			quarantineDescriptor = fs.openSync(
				heldQuarantinePath,
				fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW,
			);
			const quarantineIdentity = fs.fstatSync(quarantineDescriptor);
			const heldQuarantine = `/proc/self/fd/${quarantineDescriptor}`;
			if (
				!quarantineIdentity.isDirectory() ||
				quarantineIdentity.dev !== sourceDevice ||
				(quarantineIdentity.mode & 0o777) !== 0o700 ||
				(currentUid !== null && quarantineIdentity.uid !== currentUid) ||
				fs.realpathSync(heldQuarantine) !== quarantinePath
			) {
				throw new Error("cleanup journal quarantine identity changed while it was opened");
			}
			return {
				tempDescriptor,
				tempIdentity,
				quarantineDescriptor,
				quarantineIdentity,
				heldQuarantine,
			};
		} catch (err) {
			lastError = err;
			if (quarantineDescriptor !== null) fs.closeSync(quarantineDescriptor);
			if (tempDescriptor !== null) fs.closeSync(tempDescriptor);
		}
	}
	throw new Error(
		`cleanup journal needs an owner-private same-device quarantine outside the checkout${
			lastError ? `: ${lastError.message}` : ""
		}`,
	);
}

function clearCleanupJournal(targetDir) {
	if (process.platform !== "linux") {
		throw new Error(
			"cleanup journal clear needs Linux held-parent support; the journal was preserved for manual recovery",
		);
	}
	let heldDirectory = null;
	let journalDescriptor = null;
	let quarantine = null;
	let tombstonePath = null;
	const currentUid = typeof process.getuid === "function" ? process.getuid() : null;
	const safeJournal = (stat) =>
		stat.isFile() &&
		!stat.isSymbolicLink() &&
		stat.nlink === 1 &&
		(stat.mode & 0o777) === 0o600 &&
		(currentUid === null || stat.uid === currentUid);
	try {
		heldDirectory = openHeldLinuxRepoDirectory(targetDir, ".stdd", "cleanup journal parent");
		const heldJournalPath = path.join(heldDirectory.heldPath, path.basename(CLEANUP_JOURNAL_REL));
		let before;
		try {
			before = fs.lstatSync(heldJournalPath);
		} catch (err) {
			if (err.code === "ENOENT") return;
			throw err;
		}
		journalDescriptor = fs.openSync(heldJournalPath, fs.constants.O_RDWR | fs.constants.O_NOFOLLOW);
		const opened = fs.fstatSync(journalDescriptor);
		const atOpen = fs.lstatSync(heldJournalPath);
		const parentAtOpen = fs.fstatSync(heldDirectory.descriptor);
		if (
			!safeJournal(before) ||
			!safeJournal(opened) ||
			!safeJournal(atOpen) ||
			!samePublicationObservation(before, opened) ||
			!samePublicationObservation(opened, atOpen) ||
			!sameFileIdentity(heldDirectory.identity, parentAtOpen)
		) {
			throw new Error("cleanup journal changed before it could be cleared");
		}

		// Allocate and bind a same-device quarantine before zeroization. If no
		// outside-checkout parent can support an atomic inode move, preserve
		// the still-readable WAL for deterministic recovery.
		quarantine = openCleanupJournalQuarantine(targetDir, opened.dev, currentUid);
		const zeroes = Buffer.alloc(64 * 1024);
		let remaining = opened.size;
		while (remaining > 0) {
			const length = Math.min(remaining, zeroes.length);
			const written = fs.writeSync(journalDescriptor, zeroes, 0, length, null);
			if (written <= 0) throw new Error("cleanup journal could not be overwritten before clear");
			remaining -= written;
		}
		fs.fsyncSync(journalDescriptor);
		fs.ftruncateSync(journalDescriptor, 0);
		fs.fsyncSync(journalDescriptor);
		const wiped = fs.fstatSync(journalDescriptor);
		const wipedAtSource = fs.lstatSync(heldJournalPath);
		if (
			!safeJournal(wiped) ||
			wiped.size !== 0 ||
			!sameFileIdentity(opened, wiped) ||
			!samePublicationObservation(wiped, wipedAtSource)
		) {
			throw new Error("cleanup journal changed while its bytes were cleared");
		}

		tombstonePath = path.join(
			quarantine.heldQuarantine,
			`cleanup-journal-${randomBytes(16).toString("hex")}.tombstone`,
		);
		const beforeMove = fs.fstatSync(journalDescriptor);
		const sourceBeforeMove = fs.lstatSync(heldJournalPath);
		if (
			!samePublicationObservation(wiped, beforeMove) ||
			!samePublicationObservation(beforeMove, sourceBeforeMove)
		) {
			throw new Error("cleanup journal changed before its quarantine move");
		}
		fs.renameSync(heldJournalPath, tombstonePath);
		fs.fsyncSync(heldDirectory.descriptor);
		fs.fsyncSync(quarantine.quarantineDescriptor);

		const afterMove = fs.fstatSync(journalDescriptor);
		const atTombstone = fs.lstatSync(tombstonePath);
		const quarantineAfterMove = fs.fstatSync(quarantine.quarantineDescriptor);
		const tempAfterMove = fs.fstatSync(quarantine.tempDescriptor);
		if (
			!safeJournal(afterMove) ||
			!safeJournal(atTombstone) ||
			!samePublicationPayload(beforeMove, afterMove) ||
			!samePublicationObservation(afterMove, atTombstone) ||
			!sameFileIdentity(quarantine.quarantineIdentity, quarantineAfterMove) ||
			!sameFileIdentity(quarantine.tempIdentity, tempAfterMove)
		) {
			throw new Error("cleanup journal changed while it was cleared");
		}
		try {
			fs.lstatSync(heldJournalPath);
			throw new Error("cleanup journal changed while it was cleared");
		} catch (err) {
			if (err.code !== "ENOENT") throw err;
		}
		const logicalParent = fs.lstatSync(heldDirectory.logicalPath);
		const heldParent = fs.fstatSync(heldDirectory.descriptor);
		if (
			!sameFileIdentity(heldDirectory.identity, logicalParent) ||
			!sameFileIdentity(heldDirectory.identity, heldParent)
		) {
			throw new Error("cleanup journal parent changed while the journal was cleared");
		}

		fs.closeSync(journalDescriptor);
		journalDescriptor = null;
		const tombstoneAfterClose = fs.lstatSync(tombstonePath);
		const quarantineAfterClose = fs.fstatSync(quarantine.quarantineDescriptor);
		const tempAfterClose = fs.fstatSync(quarantine.tempDescriptor);
		if (
			!safeJournal(tombstoneAfterClose) ||
			!samePublicationObservation(afterMove, tombstoneAfterClose) ||
			!sameFileIdentity(quarantine.quarantineIdentity, quarantineAfterClose) ||
			!sameFileIdentity(quarantine.tempIdentity, tempAfterClose)
		) {
			throw new Error("cleanup journal changed while it was cleared");
		}
		try {
			fs.lstatSync(heldJournalPath);
			throw new Error("cleanup journal changed while it was cleared");
		} catch (err) {
			if (err.code !== "ENOENT") throw err;
		}
	} catch (err) {
		if (err.code === "ENOENT" || err.code === "ELOOP") {
			throw new Error("cleanup journal changed while it was cleared");
		}
		throw err;
	} finally {
		if (journalDescriptor !== null) {
			try {
				fs.closeSync(journalDescriptor);
			} catch {
				// The exact journal inode remains preserved; never chase a basename.
			}
		}
		if (quarantine !== null) {
			try {
				fs.closeSync(quarantine.quarantineDescriptor);
			} catch {}
			try {
				fs.closeSync(quarantine.tempDescriptor);
			} catch {}
		}
		if (heldDirectory !== null) {
			try {
				fs.closeSync(heldDirectory.descriptor);
			} catch {
				// The held parent has already proved success or an indeterminate clear.
			}
		}
	}
}

function inspectCleanupEntryState(targetDir, entry) {
	try {
		const source = resolveWritableRepoPath(targetDir, entry.source, "cleanup state source");
		const quarantine = resolveWritableRepoPath(targetDir, entry.quarantine, "cleanup state quarantine");
		const parentPath = path.dirname(source);
		const parent = fs.lstatSync(parentPath);
		if (
			String(parent.dev) !== entry.parentDev ||
			String(parent.ino) !== entry.parentIno ||
			!parent.isDirectory() ||
			parent.isSymbolicLink()
		) {
			throw new Error("logical parent no longer maps to the journaled directory identity");
		}
		const inspectPath = (candidate) => {
			let descriptor = null;
			try {
				const before = fs.lstatSync(candidate);
				if (before.isSymbolicLink() || !before.isFile()) {
					throw new Error("is not a non-symlinked regular file");
				}
				descriptor = fs.openSync(candidate, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
				const opened = fs.fstatSync(descriptor);
				const bytes = fs.readFileSync(descriptor);
				const after = fs.lstatSync(candidate);
				if (!opened.isFile() || !sameFileIdentity(before, opened) || !sameFileIdentity(opened, after)) {
					throw new Error("changed while its identity was verified");
				}
				return {
					exists: true,
					exactIdentity: String(opened.dev) === entry.fileDev && String(opened.ino) === entry.fileIno,
					hash: sha256(bytes),
				};
			} catch (err) {
				if (err.code === "ENOENT") return { exists: false };
				throw err;
			} finally {
				if (descriptor !== null) {
					try {
						fs.closeSync(descriptor);
					} catch {}
				}
			}
		};
		const sourceState = inspectPath(source);
		const quarantineState = inspectPath(quarantine);
		const parentAfter = fs.lstatSync(parentPath);
		if (!sameFileIdentity(parent, parentAfter)) {
			throw new Error("logical parent changed while cleanup state was inspected");
		}
		if (quarantineState.exists && quarantineState.exactIdentity && quarantineState.hash === entry.hash) {
			return {
				kind: "quarantined",
				keepSource: sourceState.exists,
			};
		}
		if (
			sourceState.exists &&
			sourceState.exactIdentity &&
			sourceState.hash === entry.hash &&
			!quarantineState.exists
		) {
			return { kind: "restored" };
		}
		throw new Error(
			`cannot prove the journaled file inode at either path (source=${
				sourceState.exists ? "other" : "missing"
			}, quarantine=${quarantineState.exists ? "other" : "missing"})`,
		);
	} catch (err) {
		return { kind: "unresolved", reason: err.message };
	}
}

function cleanupJournalCommitted(targetDir, journal) {
	try {
		const manifest = readManifestDocument(targetDir);
		if (!manifest) return false;
		return journal.entries.every((entry) => {
			const state = inspectCleanupEntryState(targetDir, entry);
			return (
				entry.phase === "quarantined" &&
				state.kind === "quarantined" &&
				state.keepSource === entry.keepSource &&
				Object.hasOwn(manifest.files, entry.quarantine) &&
				manifest.files[entry.quarantine] === entry.hash &&
				(entry.keepSource
					? Object.hasOwn(manifest.files, entry.source) && manifest.files[entry.source] === entry.hash
					: !Object.hasOwn(manifest.files, entry.source))
			);
		});
	} catch {
		return false;
	}
}

function rollbackCleanupEntryThroughHeldParent(targetDir, entry) {
	if (process.platform !== "linux") {
		throw new Error(
			"safe cleanup rollback needs Linux held-parent support; the journal was preserved for manual recovery",
		);
	}
	const source = resolveWritableRepoPath(targetDir, entry.source, "cleanup rollback source");
	const quarantine = resolveWritableRepoPath(targetDir, entry.quarantine, "cleanup rollback quarantine");
	const parentPath = path.dirname(source);
	if (parentPath !== path.dirname(quarantine)) {
		throw new Error("cleanup rollback paths no longer share one parent");
	}
	let parentDescriptor = null;
	try {
		parentDescriptor = fs.openSync(
			parentPath,
			fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW,
		);
		const parent = fs.fstatSync(parentDescriptor);
		if (
			!parent.isDirectory() ||
			String(parent.dev) !== entry.parentDev ||
			String(parent.ino) !== entry.parentIno
		) {
			throw new Error("logical parent no longer maps to the journaled directory identity");
		}
		const heldParent = `/proc/self/fd/${parentDescriptor}`;
		// Fail before mutation when procfs cannot supply the stable pathname
		// bridge used by Node's synchronous rename API.
		fs.realpathSync(heldParent);
		const heldSource = path.join(heldParent, path.basename(source));
		const heldQuarantine = path.join(heldParent, path.basename(quarantine));
		const inspectHeld = (candidate) => {
			let descriptor = null;
			try {
				const before = fs.lstatSync(candidate);
				if (before.isSymbolicLink() || !before.isFile()) {
					throw new Error("held cleanup path is not a non-symlinked regular file");
				}
				descriptor = fs.openSync(candidate, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
				const opened = fs.fstatSync(descriptor);
				const bytes = fs.readFileSync(descriptor);
				const after = fs.lstatSync(candidate);
				if (!opened.isFile() || !sameFileIdentity(before, opened) || !sameFileIdentity(opened, after)) {
					throw new Error("held cleanup path changed while it was verified");
				}
				return {
					exists: true,
					exact:
						String(opened.dev) === entry.fileDev &&
						String(opened.ino) === entry.fileIno &&
						sha256(bytes) === entry.hash,
				};
			} catch (err) {
				if (err.code === "ENOENT") return { exists: false, exact: false };
				throw err;
			} finally {
				if (descriptor !== null) {
					try {
						fs.closeSync(descriptor);
					} catch {}
				}
			}
		};
		const sourceBefore = inspectHeld(heldSource);
		const quarantineBefore = inspectHeld(heldQuarantine);
		if (sourceBefore.exact && !quarantineBefore.exists) {
			// Already restored by an earlier partial rollback.
		} else if (!sourceBefore.exists && quarantineBefore.exact) {
			fs.renameSync(heldQuarantine, heldSource);
		} else {
			throw new Error(
				sourceBefore.exists
					? "both the quarantine and another source object are live"
					: "the exact journaled inode is not available at its quarantine",
			);
		}
		const sourceAfter = inspectHeld(heldSource);
		const quarantineAfter = inspectHeld(heldQuarantine);
		const heldParentAfter = fs.fstatSync(parentDescriptor);
		if (!sourceAfter.exact || quarantineAfter.exists || !sameFileIdentity(parent, heldParentAfter)) {
			throw new Error("held-parent rollback did not restore the exact journaled inode");
		}
		const logicalParentAfter = fs.lstatSync(parentPath);
		if (
			logicalParentAfter.isSymbolicLink() ||
			!logicalParentAfter.isDirectory() ||
			!sameFileIdentity(parent, logicalParentAfter)
		) {
			throw new Error(
				"logical parent changed during held-parent rollback; no outside path was modified",
			);
		}
	} finally {
		if (parentDescriptor !== null) {
			try {
				fs.closeSync(parentDescriptor);
			} catch {}
		}
	}
}

function rollbackCleanupJournal(targetDir, journal) {
	const unresolved = [];
	for (const entry of [...journal.entries].reverse()) {
		try {
			rollbackCleanupEntryThroughHeldParent(targetDir, entry);
			entry.phase = "planned";
			entry.keepSource = false;
			entry.reason = "";
		} catch (err) {
			entry.phase = "unresolved";
			entry.reason = err.message;
			unresolved.push(`${entry.source}: ${err.message}`);
		}
	}
	if (unresolved.length > 0) {
		try {
			writeCleanupJournal(targetDir, journal);
		} catch (err) {
			unresolved.push(`journal phase update: ${err.message}`);
		}
	}
	return unresolved;
}

function recoverCleanupJournal(targetDir) {
	let journal;
	try {
		journal = readCleanupJournal(targetDir);
	} catch (err) {
		fail(`${CLEANUP_JOURNAL_REL} is invalid — ${err.message}; inspect it before retrying init`);
	}
	if (!journal) return;
	if (cleanupJournalCommitted(targetDir, journal)) {
		clearCleanupJournal(targetDir);
		return;
	}
	const unresolved = rollbackCleanupJournal(targetDir, journal);
	if (unresolved.length > 0) {
		fail(
			`${CLEANUP_JOURNAL_REL} has unresolved cleanup state — ${unresolved.join(
				"; ",
			)}; restore the named paths before retrying init`,
		);
	}
	clearCleanupJournal(targetDir);
}

function publishManifestDurably(targetDir, manifest, state) {
	const manifestPath = resolveRepoPath(targetDir, ".stdd/manifest.json", "manifest path");
	if (process.platform !== "linux") {
		throw new Error(
			"secure manifest publication is unsupported on this platform because no held-parent pathname bridge is available",
		);
	}
	publishHeldParentFile({
		openDirectory: () => openHeldLinuxRepoDirectory(targetDir, ".stdd", "manifest parent"),
		logicalTargetPath: manifestPath,
		content: `${JSON.stringify(manifest, null, "\t")}\n`,
		mode: 0o600,
		tempPrefix: ".manifest-",
		identityError: "manifest parent or published identity changed during durable publication",
		onRenameAttempt: () => {
			state.renameAttempted = true;
		},
	});
	state.durable = true;
}

const MANIFEST_QUARANTINE_BASENAME = /^\.stdd-cleanup-[0-9a-f]{32}\.tmp$/;

/**
 * Read one manifest-tracked output without following a symlink or trusting a
 * check-then-read path race. Callers receive a finding, never a filesystem
 * exception. `missing` remains distinct so check keeps its established hint.
 */
function inspectManifestOutput(targetDir, file) {
	let filePath;
	try {
		filePath = resolveWritableRepoPath(targetDir, file, `manifest path ${JSON.stringify(file)}`);
	} catch (err) {
		return { kind: "invalid", reason: err.message };
	}

	let before;
	try {
		before = fs.lstatSync(filePath);
	} catch (err) {
		if (err.code === "ENOENT") return { kind: "missing" };
		return { kind: "invalid", reason: `metadata could not be read safely: ${err.message}` };
	}
	if (before.isSymbolicLink()) {
		return { kind: "invalid", reason: "is a symlink, not a regular file" };
	}
	if (!before.isFile()) {
		return {
			kind: "invalid",
			reason: before.isDirectory() ? "is a directory, not a regular file" : "is a non-regular file",
		};
	}

	let descriptor = null;
	let result;
	try {
		descriptor = fs.openSync(filePath, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
		const opened = fs.fstatSync(descriptor);
		if (!opened.isFile()) {
			result = {
				kind: "invalid",
				reason: "was replaced during inspection with a non-regular file",
			};
		} else {
			const bytes = fs.readFileSync(descriptor);
			const after = fs.lstatSync(filePath);
			// Re-run the path walk after reading: a parent directory may have
			// become a symlink after the initial resolution.
			resolveWritableRepoPath(targetDir, file, `manifest path ${JSON.stringify(file)}`);
			const realRoot = fs.realpathSync(targetDir);
			const realFile = fs.realpathSync(filePath);
			const fromRoot = path.relative(realRoot, realFile);
			const escaped =
				fromRoot === ".." || fromRoot.startsWith(`..${path.sep}`) || path.isAbsolute(fromRoot);
			const finalStat = fs.lstatSync(filePath);
			if (
				escaped ||
				after.isSymbolicLink() ||
				!after.isFile() ||
				!sameFileIdentity(opened, after) ||
				finalStat.isSymbolicLink() ||
				!finalStat.isFile() ||
				!sameFileIdentity(opened, finalStat)
			) {
				result = {
					kind: "invalid",
					reason: escaped
						? "resolved outside the repository during inspection"
						: "was replaced during inspection",
				};
			} else {
				result = {
					kind: "ok",
					filePath,
					bytes,
					identity: opened,
					realParentPath: path.dirname(realFile),
				};
			}
		}
	} catch (err) {
		result = {
			kind: "invalid",
			reason:
				err.code === "ENOENT"
					? "was replaced or removed during inspection"
					: `could not be read safely: ${err.message}`,
		};
	} finally {
		if (descriptor !== null) {
			try {
				fs.closeSync(descriptor);
			} catch (err) {
				result = {
					kind: "invalid",
					reason: `could not be closed safely after reading: ${err.message}`,
				};
			}
		}
	}
	return result;
}

/**
 * Quarantine and remove a verified output through a held parent directory.
 * Linux procfs gives pathname operations a stable dirfd-like anchor. Other
 * runtimes fail closed and preserve the output for manual cleanup.
 */
function removeInspectedManifestOutput(inspected, expectedHash, quarantineName) {
	if (process.platform !== "linux") {
		return { removed: false, reason: "atomic parent-bound cleanup is unavailable on this platform" };
	}
	let parentDescriptor = null;
	let fileDescriptor = null;
	let quarantinePath = null;
	let sourcePath = null;
	let renamed = false;
	const settleRenamedQuarantine = (cause) => {
		try {
			const sourceExists = fs.existsSync(sourcePath);
			if (!sourceExists) {
				let rolledBack = false;
				try {
					fs.renameSync(quarantinePath, sourcePath);
					rolledBack = true;
					const restored = fs.lstatSync(sourcePath);
					if (
						restored.isFile() &&
						!restored.isSymbolicLink() &&
						sameFileIdentity(inspected.identity, restored)
					) {
						return {
							removed: false,
							reason: "the quarantined output was restored after a cleanup verification failure",
							error: cause,
						};
					}
				} catch {
					// The caller owns a durable journal containing both exact
					// paths and identities and will settle or block.
				}
				if (rolledBack) {
					return {
						removed: false,
						reason: "cleanup rollback restored a changed object at the original path",
					};
				}
			}
			return {
				removed: true,
				quarantineName,
				keepSource: fs.existsSync(sourcePath),
				warning: `cleanup verification failed after quarantine: ${cause.message}`,
			};
		} catch (err) {
			// Settlement is deliberately total: even hostile probe faults are
			// converted into durable unresolved state by the caller.
			return {
				removed: false,
				unresolved: true,
				quarantineName,
				reason: `cleanup settlement could not inspect its paths: ${err.message}`,
			};
		}
	};
	try {
		const parentPath = path.dirname(inspected.filePath);
		parentDescriptor = fs.openSync(
			parentPath,
			fs.constants.O_RDONLY | fs.constants.O_DIRECTORY | fs.constants.O_NOFOLLOW,
		);
		const heldParent = `/proc/self/fd/${parentDescriptor}`;
		if (fs.realpathSync(heldParent) !== inspected.realParentPath) {
			return { removed: false, reason: "parent directory was replaced after inspection" };
		}
		sourcePath = path.join(heldParent, path.basename(inspected.filePath));
		fileDescriptor = fs.openSync(sourcePath, fs.constants.O_RDONLY | fs.constants.O_NOFOLLOW);
		const current = fs.fstatSync(fileDescriptor);
		if (!current.isFile() || !sameFileIdentity(inspected.identity, current)) {
			return { removed: false, reason: "output was replaced after inspection" };
		}
		if (sha256(fs.readFileSync(fileDescriptor)) !== expectedHash) {
			return { removed: false, reason: "output changed after inspection" };
		}

		quarantinePath = path.join(heldParent, quarantineName);
		fs.renameSync(sourcePath, quarantinePath);
		renamed = true;
		const quarantined = fs.lstatSync(quarantinePath);
		if (
			quarantined.isSymbolicLink() ||
			!quarantined.isFile() ||
			!sameFileIdentity(current, quarantined)
		) {
			return settleRenamedQuarantine(new Error("output was replaced at the quarantine boundary"));
		}
		if (fs.realpathSync(heldParent) !== inspected.realParentPath) {
			return settleRenamedQuarantine(
				new Error("generated cleanup parent directory changed during quarantine"),
			);
		}
		quarantinePath = null;
		return { removed: true, quarantineName };
	} catch (err) {
		if (renamed) return settleRenamedQuarantine(err);
		return { removed: false, reason: `parent-bound cleanup failed: ${err.message}`, error: err };
	} finally {
		if (fileDescriptor !== null) {
			try {
				fs.closeSync(fileDescriptor);
			} catch {
				// The path operation has already settled; descriptor cleanup is best effort.
			}
		}
		if (parentDescriptor !== null) {
			try {
				fs.closeSync(parentDescriptor);
			} catch {
				// The path operation has already settled; descriptor cleanup is best effort.
			}
		}
	}
}

/**
 * Retire obsolete generated outputs and durably publish the replacement manifest.
 * Mutates `generated` with preserved/quarantined entries; failures terminate through `fail`.
 */
export function finalizeGeneratedFiles(targetDir, { oldFiles, generated, targets }) {
	// A profile or tool change may stop generating a file a previous init
	// wrote. Remove it only when still byte-identical to what init wrote —
	// a hand-edited file is never deleted. Cleanup precedes the replacement
	// manifest: on failure the previous manifest remains authoritative and
	// still accounts for every discoverable old output.
	const cleanupJournal = { version: 1, entries: [] };
	const manifestPublication = { renameAttempted: false, durable: false };
	try {
		for (const [file, hash] of Object.entries(oldFiles)) {
			if (Object.hasOwn(generated, file)) continue;
			const inspected = inspectManifestOutput(targetDir, file);
			if (inspected.kind === "missing") continue;
			if (inspected.kind === "invalid") {
				generated[file] = hash;
				console.error(
					`Preserved unsafe formerly generated output ${file}; it cannot be safely inspected (${inspected.reason}) and remains manifest-tracked until removed or relocated`,
				);
				continue;
			}
			if (
				MANIFEST_QUARANTINE_BASENAME.test(path.posix.basename(file)) &&
				sha256(inspected.bytes) === hash
			) {
				// A prior init already retired this output from its agent/CI load
				// path. Keep the identity-safe quarantine stable across re-init;
				// repeatedly renaming it would create churn without making a
				// pathname unlink any safer.
				generated[file] = hash;
				continue;
			}
			if (sha256(inspected.bytes) === hash) {
				if (process.platform !== "linux") {
					generated[file] = hash;
					console.error(
						`Preserved unsafe formerly generated output ${file}; atomic parent-bound cleanup is unavailable on this platform and it remains manifest-tracked until removed or relocated`,
					);
					continue;
				}
				const parentStat = fs.lstatSync(path.dirname(inspected.filePath));
				if (
					parentStat.isSymbolicLink() ||
					!parentStat.isDirectory() ||
					fs.realpathSync(path.dirname(inspected.filePath)) !== inspected.realParentPath
				) {
					generated[file] = hash;
					console.error(
						`Preserved unsafe formerly generated output ${file}; parent directory changed after inspection and it remains manifest-tracked until removed or relocated`,
					);
					continue;
				}
				const quarantineName = `.stdd-cleanup-${randomBytes(16).toString("hex")}.tmp`;
				const parent = path.posix.dirname(file);
				const quarantineFile = parent === "." ? quarantineName : `${parent}/${quarantineName}`;
				const entry = {
					source: file,
					quarantine: quarantineFile,
					hash,
					parentDev: String(parentStat.dev),
					parentIno: String(parentStat.ino),
					fileDev: String(inspected.identity.dev),
					fileIno: String(inspected.identity.ino),
					phase: "planned",
					keepSource: false,
					reason: "",
				};
				cleanupJournal.entries.push(entry);
				// This fsynced planned record is the write-ahead boundary: no
				// rename may happen unless recovery already knows both names and
				// both captured identities.
				writeCleanupJournal(targetDir, cleanupJournal);
				const removal = removeInspectedManifestOutput(inspected, hash, quarantineName);
				if (removal.unresolved) {
					entry.phase = "unresolved";
					entry.reason = removal.reason;
					try {
						writeCleanupJournal(targetDir, cleanupJournal);
					} catch {}
					throw new Error(removal.reason);
				}
				const state = inspectCleanupEntryState(targetDir, entry);
				if (removal.error) throw removal.error;
				if (!removal.removed) {
					if (state.kind !== "restored") {
						entry.phase = "unresolved";
						entry.reason =
							state.kind === "unresolved"
								? state.reason
								: "cleanup returned without a provably restored source";
						try {
							writeCleanupJournal(targetDir, cleanupJournal);
						} catch {}
						throw new Error(entry.reason);
					}
					cleanupJournal.entries.pop();
					if (cleanupJournal.entries.length > 0) writeCleanupJournal(targetDir, cleanupJournal);
					else clearCleanupJournal(targetDir);
					generated[file] = hash;
					console.error(
						`Preserved unsafe formerly generated output ${file}; ${removal.reason} and it remains manifest-tracked until removed or relocated`,
					);
					continue;
				}
				if (state.kind !== "quarantined") {
					entry.phase = "unresolved";
					entry.reason =
						state.kind === "unresolved"
							? state.reason
							: "cleanup did not leave the exact inode at its journaled quarantine";
					try {
						writeCleanupJournal(targetDir, cleanupJournal);
					} catch {}
					throw new Error(entry.reason);
				}
				entry.phase = "quarantined";
				entry.keepSource = state.keepSource;
				entry.reason = removal.warning ?? "";
				writeCleanupJournal(targetDir, cleanupJournal);
				generated[quarantineFile] = hash;
				if (state.keepSource) generated[file] = hash;
				if (removal.warning) console.error(`${file}: ${removal.warning}`);
				console.log(
					`Quarantined ${file} as ${quarantineFile} (no longer loaded by this profile; retained for identity-safe cleanup)`,
				);
			} else {
				// Preserve user edits, but never let a native agent keep loading an
				// unmanifested former output. Retaining the old expected hash makes
				// check/doctor report the file stale until its owner moves or removes it.
				generated[file] = hash;
				console.error(
					`Preserved modified formerly generated file ${file}; it remains manifest-tracked and stale until removed or relocated`,
				);
			}
		}

		// targets are remembered so `stdd configure` can recompile the same
		// outputs without re-asking what this repo generates. Publish last with a
		// same-directory atomic rename: a failed write never truncates the prior
		// manifest or authenticates only part of this generation.
		const manifest = {
			generatedBy: "stdd",
			version: VERSION,
			files: generated,
			targets: {
				tools: targets.tools,
				ci: targets.ci,
				hooks: targets.hooks,
				sessionHook: targets.sessionHook,
				stopHook: targets.stopHook,
			},
		};
		publishManifestDurably(targetDir, manifest, manifestPublication);
		if (cleanupJournal.entries.length > 0) clearCleanupJournal(targetDir);
	} catch (err) {
		const unresolved = [];
		if (cleanupJournal.entries.length > 0) {
			const preexistingUnresolved = cleanupJournal.entries.filter(
				(entry) => entry.phase === "unresolved",
			);
			if (preexistingUnresolved.length > 0) {
				unresolved.push(
					...preexistingUnresolved.map(
						(entry) => `${entry.source}: ${entry.reason || "cleanup settlement is unresolved"}`,
					),
				);
				try {
					writeCleanupJournal(targetDir, cleanupJournal);
				} catch (journalError) {
					unresolved.push(`journal phase update: ${journalError.message}`);
				}
			} else if (manifestPublication.renameAttempted) {
				unresolved.push(
					"manifest publication crossed its rename boundary; the journal stays authoritative until next-init recovery",
				);
			} else {
				unresolved.push(...rollbackCleanupJournal(targetDir, cleanupJournal));
				if (unresolved.length === 0) {
					try {
						clearCleanupJournal(targetDir);
					} catch (clearError) {
						unresolved.push(`journal cleanup: ${clearError.message}`);
					}
				}
			}
		}
		if (unresolved.length > 0) {
			fail(`${err.message}; ${CLEANUP_JOURNAL_REL} remains for recovery — ${unresolved.join("; ")}`);
		}
		fail(err.message);
	}
}

const NO_PROJECT_LOG_METHOD_PREAMBLE = `# Repository policy: no project log

This repository sets \`projectLog.enabled\` to \`false\`. It does not use a
project log. Do not create or search dated decision, design, or deferred-work
archives. Keep current behavior in canonical docs; use PR descriptions and git
history for rationale and decisions.

This repository policy overrides generic project-log examples later in this
method.

---

`;

function renderInstalledMethod(source, projectLogEnabled) {
	return projectLogEnabled ? source : `${NO_PROJECT_LOG_METHOD_PREAMBLE}${source}`;
}

/** Managed outputs that remain discoverable even when a partial init never
 * published its manifest, or an older buggy cleanup forgot one. */
function discoverGeneratedOutputs(targetDir) {
	const found = new Set();
	const addIfPresent = (relative) => {
		const candidate = path.join(targetDir, relative);
		try {
			fs.lstatSync(candidate);
			found.add(relative);
		} catch (err) {
			if (err.code !== "ENOENT") found.add(relative);
		}
	};

	addIfPresent(".stdd/method.md");
	for (const adapter of Object.values(AGENT_ADAPTERS)) addIfPresent(adapter.snippetFile);
	const shippedPlaybooks = loadPlaybooks();
	const reservedSkillNames = new Set([
		...shippedPlaybooks.map((playbook) => playbook.meta.name),
		...loadLocalPlaybooks(targetDir).map((playbook) => playbook.meta.name),
	]);
	for (const playbook of shippedPlaybooks) addIfPresent(`.stdd/playbooks/${playbook.file}`);
	for (const adapter of Object.values(CI_ADAPTERS)) {
		if (adapter.outputFile) addIfPresent(adapter.outputFile);
	}

	for (const adapter of Object.values(AGENT_ADAPTERS)) {
		// Shipped and validated local skill names reserve generated-output paths. Surface an
		// exact final object even when it cannot be opened as a stamped regular
		// file; absence remains normal, and unrelated user skill names are
		// still considered only when their contents carry the generated stamp.
		for (const name of reservedSkillNames) {
			addIfPresent(`${adapter.skillRoot}/${name}/SKILL.md`);
		}
		const skillsRoot = path.join(targetDir, adapter.skillRoot);
		let entries;
		try {
			entries = fs.readdirSync(skillsRoot, { withFileTypes: true });
		} catch (err) {
			if (err.code !== "ENOENT") found.add(adapter.skillRoot);
			continue;
		}
		for (const entry of entries) {
			if (!entry.isDirectory()) continue;
			const relative = `${adapter.skillRoot}/${entry.name}/SKILL.md`;
			const skillPath = path.join(targetDir, relative);
			try {
				if (
					fs.lstatSync(skillPath).isFile() &&
					/<!-- generated by stdd v[^\s]+ —/u.test(fs.readFileSync(skillPath, "utf8"))
				) {
					found.add(relative);
				}
			} catch {
				// A broken generated-looking skill path is still surfaced when
				// the manifest names it; unknown user-owned entries stay alone.
			}
		}
	}
	return [...found].sort();
}

/**
 * Generated-file drift, as `{ file, message }` findings. With a manifest
 * (written by `stdd init`), every generated file is verified by content
 * hash and managed outputs may not exist outside its inventory. Without a
 * manifest, any generated output is a failed or legacy partial install that
 * must be regenerated before it can be trusted.
 */
function scanGeneratedDrift(targetDir, config) {
	const stale = [];
	try {
		const cleanupJournal = readCleanupJournal(targetDir);
		if (cleanupJournal) {
			stale.push({
				file: CLEANUP_JOURNAL_REL,
				message:
					"pending generated-output cleanup transaction — run stdd init to recover or inspect its unresolved paths",
			});
		}
	} catch (err) {
		stale.push({
			file: CLEANUP_JOURNAL_REL,
			message: `invalid cleanup transaction journal (${err.message}) — inspect it before running stdd init`,
		});
	}
	let manifest;
	try {
		manifest = readManifestDocument(targetDir);
	} catch (err) {
		return [
			...stale,
			{
				file: ".stdd/manifest.json",
				message: `${err.message} — re-run stdd init`,
			},
		];
	}
	if (manifest) {
		let installedMethodBytes = null;
		if (manifest.version !== VERSION) {
			stale.push({
				file: ".stdd/manifest.json",
				message: `written by stdd v${manifest.version}, CLI is v${VERSION} — re-run stdd init`,
			});
		}
		for (const [file, hash] of Object.entries(manifest.files)) {
			const inspected = inspectManifestOutput(targetDir, file);
			if (inspected.kind === "missing") {
				stale.push({
					file,
					message: "listed in .stdd/manifest.json but missing — re-run stdd init",
				});
			} else if (inspected.kind === "invalid") {
				stale.push({
					file,
					message: `cannot be safely inspected as a readable regular file (${inspected.reason}) — remove it or re-run stdd init`,
				});
			} else {
				if (file === ".stdd/method.md") installedMethodBytes = inspected.bytes;
				if (sha256(inspected.bytes) === hash) continue;
				stale.push({
					file,
					message: "edited by hand or stale — re-run stdd init",
				});
			}
		}
		for (const file of discoverGeneratedOutputs(targetDir)) {
			if (!Object.hasOwn(manifest.files, file)) {
				stale.push({
					file,
					message:
						"looks generated by stdd but is not listed in .stdd/manifest.json — remove it or re-run stdd init",
				});
			}
		}
		if (installedMethodBytes !== null) {
			const canonicalMethod = Buffer.from(
				renderInstalledMethod(
					fs.readFileSync(path.join(PKG_ROOT, "method", "README.md"), "utf8"),
					config.projectLog.enabled,
				),
			);
			if (!installedMethodBytes.equals(canonicalMethod)) {
				stale.push({
					file: ".stdd/method.md",
					message: "does not match the canonical method shipped by this CLI — re-run stdd init",
				});
			}
		}
		const automationRunner = isStddSourceCheckout(targetDir) ? SOURCE_RUNNER : NPM_RUNNER;
		for (const tool of manifest.targets?.tools ?? []) {
			const adapter = getAgentAdapter(tool);
			const inspected = inspectManifestOutput(targetDir, adapter.snippetFile);
			if (inspected.kind !== "ok") continue;
			const expectedSnippet = Buffer.from(
				renderAgentInstructions({
					adapter,
					stamp: STAMP,
					npmRunner: automationRunner,
					crossCli: config.capabilities.crossCli,
					projectLogEnabled: config.projectLog.enabled,
				}),
			);
			if (
				!inspected.bytes.equals(expectedSnippet) &&
				!stale.some((finding) => finding.file === adapter.snippetFile)
			) {
				stale.push({
					file: adapter.snippetFile,
					message: "does not match the current repository policy — re-run stdd init",
				});
			}
		}
		return stale;
	}

	const partial = discoverGeneratedOutputs(targetDir);
	if (partial.length > 0) {
		for (const file of partial) {
			const inspected = inspectManifestOutput(targetDir, file);
			if (inspected.kind === "invalid") {
				stale.push({
					file,
					message: `unsafe object occupies an exact generated-output path (${inspected.reason}) — remove it or re-run stdd init`,
				});
			}
		}
		stale.push({
			file: ".stdd/manifest.json",
			message: `is missing for a partial install with generated output ${partial[0]} — re-run stdd init`,
		});
	}
	return stale;
}

export {
	KNOWN_CAPABILITIES,
	KNOWN_CI,
	KNOWN_TOOLS,
	loadLocalPlaybooks,
	loadPlaybooks,
	NPM_RUNNER,
	PKG_ROOT,
	readManifestDocument,
	readManifestFiles,
	recoverCleanupJournal,
	renderInstalledMethod,
	SOURCE_RUNNER,
	STAMP,
	scanGeneratedDrift,
	VERSION,
	validateAdapterSelection,
};
